// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.4
// source: billing_accounts.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BillingAccountsService_CreateBillingAccount_FullMethodName = "/da.proto.BillingAccountsService/CreateBillingAccount"
	BillingAccountsService_ReadBillingAccount_FullMethodName   = "/da.proto.BillingAccountsService/ReadBillingAccount"
)

// BillingAccountsServiceClient is the client API for BillingAccountsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// billing accounts service
type BillingAccountsServiceClient interface {
	// create billing account
	CreateBillingAccount(ctx context.Context, in *CreateBillingAccountRequest, opts ...grpc.CallOption) (*CreateBillingAccountResponse, error)
	// read billing account
	ReadBillingAccount(ctx context.Context, in *ReadBillingAccountRequest, opts ...grpc.CallOption) (*ReadBillingAccountResponse, error)
}

type billingAccountsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBillingAccountsServiceClient(cc grpc.ClientConnInterface) BillingAccountsServiceClient {
	return &billingAccountsServiceClient{cc}
}

func (c *billingAccountsServiceClient) CreateBillingAccount(ctx context.Context, in *CreateBillingAccountRequest, opts ...grpc.CallOption) (*CreateBillingAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBillingAccountResponse)
	err := c.cc.Invoke(ctx, BillingAccountsService_CreateBillingAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *billingAccountsServiceClient) ReadBillingAccount(ctx context.Context, in *ReadBillingAccountRequest, opts ...grpc.CallOption) (*ReadBillingAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadBillingAccountResponse)
	err := c.cc.Invoke(ctx, BillingAccountsService_ReadBillingAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BillingAccountsServiceServer is the server API for BillingAccountsService service.
// All implementations must embed UnimplementedBillingAccountsServiceServer
// for forward compatibility.
//
// billing accounts service
type BillingAccountsServiceServer interface {
	// create billing account
	CreateBillingAccount(context.Context, *CreateBillingAccountRequest) (*CreateBillingAccountResponse, error)
	// read billing account
	ReadBillingAccount(context.Context, *ReadBillingAccountRequest) (*ReadBillingAccountResponse, error)
	mustEmbedUnimplementedBillingAccountsServiceServer()
}

// UnimplementedBillingAccountsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBillingAccountsServiceServer struct{}

func (UnimplementedBillingAccountsServiceServer) CreateBillingAccount(context.Context, *CreateBillingAccountRequest) (*CreateBillingAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBillingAccount not implemented")
}
func (UnimplementedBillingAccountsServiceServer) ReadBillingAccount(context.Context, *ReadBillingAccountRequest) (*ReadBillingAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadBillingAccount not implemented")
}
func (UnimplementedBillingAccountsServiceServer) mustEmbedUnimplementedBillingAccountsServiceServer() {
}
func (UnimplementedBillingAccountsServiceServer) testEmbeddedByValue() {}

// UnsafeBillingAccountsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BillingAccountsServiceServer will
// result in compilation errors.
type UnsafeBillingAccountsServiceServer interface {
	mustEmbedUnimplementedBillingAccountsServiceServer()
}

func RegisterBillingAccountsServiceServer(s grpc.ServiceRegistrar, srv BillingAccountsServiceServer) {
	// If the following call pancis, it indicates UnimplementedBillingAccountsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BillingAccountsService_ServiceDesc, srv)
}

func _BillingAccountsService_CreateBillingAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBillingAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingAccountsServiceServer).CreateBillingAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingAccountsService_CreateBillingAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingAccountsServiceServer).CreateBillingAccount(ctx, req.(*CreateBillingAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BillingAccountsService_ReadBillingAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadBillingAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BillingAccountsServiceServer).ReadBillingAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BillingAccountsService_ReadBillingAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BillingAccountsServiceServer).ReadBillingAccount(ctx, req.(*ReadBillingAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BillingAccountsService_ServiceDesc is the grpc.ServiceDesc for BillingAccountsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BillingAccountsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "da.proto.BillingAccountsService",
	HandlerType: (*BillingAccountsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBillingAccount",
			Handler:    _BillingAccountsService_CreateBillingAccount_Handler,
		},
		{
			MethodName: "ReadBillingAccount",
			Handler:    _BillingAccountsService_ReadBillingAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "billing_accounts.proto",
}
