// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.4
// source: billing_subscription.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscriptionStatus int32

const (
	SubscriptionStatus_SUBSCRIPTION_STATUS_UNSPECIFIED     SubscriptionStatus = 0
	SubscriptionStatus_SUBSCRIPTION_STATUS_ACTIVE          SubscriptionStatus = 1
	SubscriptionStatus_SUBSCRIPTION_STATUS_CANCELLED       SubscriptionStatus = 2
	SubscriptionStatus_SUBSCRIPTION_STATUS_EXPIRED         SubscriptionStatus = 3
	SubscriptionStatus_SUBSCRIPTION_STATUS_PAST_DUE        SubscriptionStatus = 4
	SubscriptionStatus_SUBSCRIPTION_STATUS_TRIALING        SubscriptionStatus = 5
	SubscriptionStatus_SUBSCRIPTION_STATUS_PENDING_PAYMENT SubscriptionStatus = 6
)

// Enum value maps for SubscriptionStatus.
var (
	SubscriptionStatus_name = map[int32]string{
		0: "SUBSCRIPTION_STATUS_UNSPECIFIED",
		1: "SUBSCRIPTION_STATUS_ACTIVE",
		2: "SUBSCRIPTION_STATUS_CANCELLED",
		3: "SUBSCRIPTION_STATUS_EXPIRED",
		4: "SUBSCRIPTION_STATUS_PAST_DUE",
		5: "SUBSCRIPTION_STATUS_TRIALING",
		6: "SUBSCRIPTION_STATUS_PENDING_PAYMENT",
	}
	SubscriptionStatus_value = map[string]int32{
		"SUBSCRIPTION_STATUS_UNSPECIFIED":     0,
		"SUBSCRIPTION_STATUS_ACTIVE":          1,
		"SUBSCRIPTION_STATUS_CANCELLED":       2,
		"SUBSCRIPTION_STATUS_EXPIRED":         3,
		"SUBSCRIPTION_STATUS_PAST_DUE":        4,
		"SUBSCRIPTION_STATUS_TRIALING":        5,
		"SUBSCRIPTION_STATUS_PENDING_PAYMENT": 6,
	}
)

func (x SubscriptionStatus) Enum() *SubscriptionStatus {
	p := new(SubscriptionStatus)
	*p = x
	return p
}

func (x SubscriptionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SubscriptionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_billing_subscription_proto_enumTypes[0].Descriptor()
}

func (SubscriptionStatus) Type() protoreflect.EnumType {
	return &file_billing_subscription_proto_enumTypes[0]
}

func (x SubscriptionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SubscriptionStatus.Descriptor instead.
func (SubscriptionStatus) EnumDescriptor() ([]byte, []int) {
	return file_billing_subscription_proto_rawDescGZIP(), []int{0}
}

type Subscription struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PlanName           string                 `protobuf:"bytes,2,opt,name=plan_name,json=planName,proto3" json:"plan_name,omitempty"`
	PlanId             string                 `protobuf:"bytes,3,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	Status             SubscriptionStatus     `protobuf:"varint,4,opt,name=status,proto3,enum=da.proto.SubscriptionStatus" json:"status,omitempty"`
	CurrentPeriodStart string                 `protobuf:"bytes,5,opt,name=current_period_start,json=currentPeriodStart,proto3" json:"current_period_start,omitempty"`
	CurrentPeriodEnd   string                 `protobuf:"bytes,6,opt,name=current_period_end,json=currentPeriodEnd,proto3" json:"current_period_end,omitempty"`
	TrialStart         string                 `protobuf:"bytes,7,opt,name=trial_start,json=trialStart,proto3" json:"trial_start,omitempty"`
	TrialEnd           string                 `protobuf:"bytes,8,opt,name=trial_end,json=trialEnd,proto3" json:"trial_end,omitempty"`
	CreatedAt          string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Subscription) Reset() {
	*x = Subscription{}
	mi := &file_billing_subscription_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subscription) ProtoMessage() {}

func (x *Subscription) ProtoReflect() protoreflect.Message {
	mi := &file_billing_subscription_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subscription.ProtoReflect.Descriptor instead.
func (*Subscription) Descriptor() ([]byte, []int) {
	return file_billing_subscription_proto_rawDescGZIP(), []int{0}
}

func (x *Subscription) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Subscription) GetPlanName() string {
	if x != nil {
		return x.PlanName
	}
	return ""
}

func (x *Subscription) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *Subscription) GetStatus() SubscriptionStatus {
	if x != nil {
		return x.Status
	}
	return SubscriptionStatus_SUBSCRIPTION_STATUS_UNSPECIFIED
}

func (x *Subscription) GetCurrentPeriodStart() string {
	if x != nil {
		return x.CurrentPeriodStart
	}
	return ""
}

func (x *Subscription) GetCurrentPeriodEnd() string {
	if x != nil {
		return x.CurrentPeriodEnd
	}
	return ""
}

func (x *Subscription) GetTrialStart() string {
	if x != nil {
		return x.TrialStart
	}
	return ""
}

func (x *Subscription) GetTrialEnd() string {
	if x != nil {
		return x.TrialEnd
	}
	return ""
}

func (x *Subscription) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CheckoutInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckoutUrl   string                 `protobuf:"bytes,1,opt,name=checkout_url,json=checkoutUrl,proto3" json:"checkout_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckoutInfo) Reset() {
	*x = CheckoutInfo{}
	mi := &file_billing_subscription_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckoutInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckoutInfo) ProtoMessage() {}

func (x *CheckoutInfo) ProtoReflect() protoreflect.Message {
	mi := &file_billing_subscription_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckoutInfo.ProtoReflect.Descriptor instead.
func (*CheckoutInfo) Descriptor() ([]byte, []int) {
	return file_billing_subscription_proto_rawDescGZIP(), []int{1}
}

func (x *CheckoutInfo) GetCheckoutUrl() string {
	if x != nil {
		return x.CheckoutUrl
	}
	return ""
}

type SubscribeToPlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanId        string                 `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	UsersCount    int64                  `protobuf:"varint,2,opt,name=users_count,json=usersCount,proto3" json:"users_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeToPlanRequest) Reset() {
	*x = SubscribeToPlanRequest{}
	mi := &file_billing_subscription_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeToPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeToPlanRequest) ProtoMessage() {}

func (x *SubscribeToPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_subscription_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeToPlanRequest.ProtoReflect.Descriptor instead.
func (*SubscribeToPlanRequest) Descriptor() ([]byte, []int) {
	return file_billing_subscription_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeToPlanRequest) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *SubscribeToPlanRequest) GetUsersCount() int64 {
	if x != nil {
		return x.UsersCount
	}
	return 0
}

type UpdateSubscriptionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserCount      int64                  `protobuf:"varint,1,opt,name=user_count,json=userCount,proto3" json:"user_count,omitempty"`
	SubscriptionId string                 `protobuf:"bytes,2,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateSubscriptionRequest) Reset() {
	*x = UpdateSubscriptionRequest{}
	mi := &file_billing_subscription_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSubscriptionRequest) ProtoMessage() {}

func (x *UpdateSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_subscription_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*UpdateSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_billing_subscription_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateSubscriptionRequest) GetUserCount() int64 {
	if x != nil {
		return x.UserCount
	}
	return 0
}

func (x *UpdateSubscriptionRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

type UpdateSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSubscriptionResponse) Reset() {
	*x = UpdateSubscriptionResponse{}
	mi := &file_billing_subscription_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSubscriptionResponse) ProtoMessage() {}

func (x *UpdateSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_subscription_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*UpdateSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_billing_subscription_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateSubscriptionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SubscribeToPlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckoutInfo  *CheckoutInfo          `protobuf:"bytes,1,opt,name=checkout_info,json=checkoutInfo,proto3" json:"checkout_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeToPlanResponse) Reset() {
	*x = SubscribeToPlanResponse{}
	mi := &file_billing_subscription_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeToPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeToPlanResponse) ProtoMessage() {}

func (x *SubscribeToPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_subscription_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeToPlanResponse.ProtoReflect.Descriptor instead.
func (*SubscribeToPlanResponse) Descriptor() ([]byte, []int) {
	return file_billing_subscription_proto_rawDescGZIP(), []int{5}
}

func (x *SubscribeToPlanResponse) GetCheckoutInfo() *CheckoutInfo {
	if x != nil {
		return x.CheckoutInfo
	}
	return nil
}

type CancelSubscriptionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionId string                 `protobuf:"bytes,1,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CancelSubscriptionRequest) Reset() {
	*x = CancelSubscriptionRequest{}
	mi := &file_billing_subscription_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSubscriptionRequest) ProtoMessage() {}

func (x *CancelSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_billing_subscription_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*CancelSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_billing_subscription_proto_rawDescGZIP(), []int{6}
}

func (x *CancelSubscriptionRequest) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

type CancelSubscriptionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelSubscriptionResponse) Reset() {
	*x = CancelSubscriptionResponse{}
	mi := &file_billing_subscription_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelSubscriptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelSubscriptionResponse) ProtoMessage() {}

func (x *CancelSubscriptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_billing_subscription_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelSubscriptionResponse.ProtoReflect.Descriptor instead.
func (*CancelSubscriptionResponse) Descriptor() ([]byte, []int) {
	return file_billing_subscription_proto_rawDescGZIP(), []int{7}
}

func (x *CancelSubscriptionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_billing_subscription_proto protoreflect.FileDescriptor

const file_billing_subscription_proto_rawDesc = "" +
	"\n" +
	"\x1abilling_subscription.proto\x12\bda.proto\"\xc7\x02\n" +
	"\fSubscription\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tplan_name\x18\x02 \x01(\tR\bplanName\x12\x17\n" +
	"\aplan_id\x18\x03 \x01(\tR\x06planId\x124\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1c.da.proto.SubscriptionStatusR\x06status\x120\n" +
	"\x14current_period_start\x18\x05 \x01(\tR\x12currentPeriodStart\x12,\n" +
	"\x12current_period_end\x18\x06 \x01(\tR\x10currentPeriodEnd\x12\x1f\n" +
	"\vtrial_start\x18\a \x01(\tR\n" +
	"trialStart\x12\x1b\n" +
	"\ttrial_end\x18\b \x01(\tR\btrialEnd\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\"1\n" +
	"\fCheckoutInfo\x12!\n" +
	"\fcheckout_url\x18\x01 \x01(\tR\vcheckoutUrl\"R\n" +
	"\x16SubscribeToPlanRequest\x12\x17\n" +
	"\aplan_id\x18\x01 \x01(\tR\x06planId\x12\x1f\n" +
	"\vusers_count\x18\x02 \x01(\x03R\n" +
	"usersCount\"c\n" +
	"\x19UpdateSubscriptionRequest\x12\x1d\n" +
	"\n" +
	"user_count\x18\x01 \x01(\x03R\tuserCount\x12'\n" +
	"\x0fsubscription_id\x18\x02 \x01(\tR\x0esubscriptionId\"6\n" +
	"\x1aUpdateSubscriptionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"V\n" +
	"\x17SubscribeToPlanResponse\x12;\n" +
	"\rcheckout_info\x18\x01 \x01(\v2\x16.da.proto.CheckoutInfoR\fcheckoutInfo\"D\n" +
	"\x19CancelSubscriptionRequest\x12'\n" +
	"\x0fsubscription_id\x18\x01 \x01(\tR\x0esubscriptionId\"6\n" +
	"\x1aCancelSubscriptionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*\x8a\x02\n" +
	"\x12SubscriptionStatus\x12#\n" +
	"\x1fSUBSCRIPTION_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aSUBSCRIPTION_STATUS_ACTIVE\x10\x01\x12!\n" +
	"\x1dSUBSCRIPTION_STATUS_CANCELLED\x10\x02\x12\x1f\n" +
	"\x1bSUBSCRIPTION_STATUS_EXPIRED\x10\x03\x12 \n" +
	"\x1cSUBSCRIPTION_STATUS_PAST_DUE\x10\x04\x12 \n" +
	"\x1cSUBSCRIPTION_STATUS_TRIALING\x10\x05\x12'\n" +
	"#SUBSCRIPTION_STATUS_PENDING_PAYMENT\x10\x062\xaf\x02\n" +
	"\x13SubscriptionService\x12V\n" +
	"\x0fSubscribeToPlan\x12 .da.proto.SubscribeToPlanRequest\x1a!.da.proto.SubscribeToPlanResponse\x12_\n" +
	"\x12UpdateSubscription\x12#.da.proto.UpdateSubscriptionRequest\x1a$.da.proto.UpdateSubscriptionResponse\x12_\n" +
	"\x12CancelSubscription\x12#.da.proto.CancelSubscriptionRequest\x1a$.da.proto.CancelSubscriptionResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_billing_subscription_proto_rawDescOnce sync.Once
	file_billing_subscription_proto_rawDescData []byte
)

func file_billing_subscription_proto_rawDescGZIP() []byte {
	file_billing_subscription_proto_rawDescOnce.Do(func() {
		file_billing_subscription_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_billing_subscription_proto_rawDesc), len(file_billing_subscription_proto_rawDesc)))
	})
	return file_billing_subscription_proto_rawDescData
}

var file_billing_subscription_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_billing_subscription_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_billing_subscription_proto_goTypes = []any{
	(SubscriptionStatus)(0),            // 0: da.proto.SubscriptionStatus
	(*Subscription)(nil),               // 1: da.proto.Subscription
	(*CheckoutInfo)(nil),               // 2: da.proto.CheckoutInfo
	(*SubscribeToPlanRequest)(nil),     // 3: da.proto.SubscribeToPlanRequest
	(*UpdateSubscriptionRequest)(nil),  // 4: da.proto.UpdateSubscriptionRequest
	(*UpdateSubscriptionResponse)(nil), // 5: da.proto.UpdateSubscriptionResponse
	(*SubscribeToPlanResponse)(nil),    // 6: da.proto.SubscribeToPlanResponse
	(*CancelSubscriptionRequest)(nil),  // 7: da.proto.CancelSubscriptionRequest
	(*CancelSubscriptionResponse)(nil), // 8: da.proto.CancelSubscriptionResponse
}
var file_billing_subscription_proto_depIdxs = []int32{
	0, // 0: da.proto.Subscription.status:type_name -> da.proto.SubscriptionStatus
	2, // 1: da.proto.SubscribeToPlanResponse.checkout_info:type_name -> da.proto.CheckoutInfo
	3, // 2: da.proto.SubscriptionService.SubscribeToPlan:input_type -> da.proto.SubscribeToPlanRequest
	4, // 3: da.proto.SubscriptionService.UpdateSubscription:input_type -> da.proto.UpdateSubscriptionRequest
	7, // 4: da.proto.SubscriptionService.CancelSubscription:input_type -> da.proto.CancelSubscriptionRequest
	6, // 5: da.proto.SubscriptionService.SubscribeToPlan:output_type -> da.proto.SubscribeToPlanResponse
	5, // 6: da.proto.SubscriptionService.UpdateSubscription:output_type -> da.proto.UpdateSubscriptionResponse
	8, // 7: da.proto.SubscriptionService.CancelSubscription:output_type -> da.proto.CancelSubscriptionResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_billing_subscription_proto_init() }
func file_billing_subscription_proto_init() {
	if File_billing_subscription_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_billing_subscription_proto_rawDesc), len(file_billing_subscription_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_billing_subscription_proto_goTypes,
		DependencyIndexes: file_billing_subscription_proto_depIdxs,
		EnumInfos:         file_billing_subscription_proto_enumTypes,
		MessageInfos:      file_billing_subscription_proto_msgTypes,
	}.Build()
	File_billing_subscription_proto = out.File
	file_billing_subscription_proto_goTypes = nil
	file_billing_subscription_proto_depIdxs = nil
}
