// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.4
// source: call_analytics_export.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CallAnalyticsExportService_ExportAnalytics_FullMethodName = "/da.proto.CallAnalyticsExportService/ExportAnalytics"
)

// CallAnalyticsExportServiceClient is the client API for CallAnalyticsExportService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CallAnalyticsExportServiceClient interface {
	ExportAnalytics(ctx context.Context, in *ExportAnalyticsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExportChunk], error)
}

type callAnalyticsExportServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCallAnalyticsExportServiceClient(cc grpc.ClientConnInterface) CallAnalyticsExportServiceClient {
	return &callAnalyticsExportServiceClient{cc}
}

func (c *callAnalyticsExportServiceClient) ExportAnalytics(ctx context.Context, in *ExportAnalyticsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExportChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CallAnalyticsExportService_ServiceDesc.Streams[0], CallAnalyticsExportService_ExportAnalytics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExportAnalyticsRequest, ExportChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CallAnalyticsExportService_ExportAnalyticsClient = grpc.ServerStreamingClient[ExportChunk]

// CallAnalyticsExportServiceServer is the server API for CallAnalyticsExportService service.
// All implementations must embed UnimplementedCallAnalyticsExportServiceServer
// for forward compatibility.
type CallAnalyticsExportServiceServer interface {
	ExportAnalytics(*ExportAnalyticsRequest, grpc.ServerStreamingServer[ExportChunk]) error
	mustEmbedUnimplementedCallAnalyticsExportServiceServer()
}

// UnimplementedCallAnalyticsExportServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCallAnalyticsExportServiceServer struct{}

func (UnimplementedCallAnalyticsExportServiceServer) ExportAnalytics(*ExportAnalyticsRequest, grpc.ServerStreamingServer[ExportChunk]) error {
	return status.Errorf(codes.Unimplemented, "method ExportAnalytics not implemented")
}
func (UnimplementedCallAnalyticsExportServiceServer) mustEmbedUnimplementedCallAnalyticsExportServiceServer() {
}
func (UnimplementedCallAnalyticsExportServiceServer) testEmbeddedByValue() {}

// UnsafeCallAnalyticsExportServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CallAnalyticsExportServiceServer will
// result in compilation errors.
type UnsafeCallAnalyticsExportServiceServer interface {
	mustEmbedUnimplementedCallAnalyticsExportServiceServer()
}

func RegisterCallAnalyticsExportServiceServer(s grpc.ServiceRegistrar, srv CallAnalyticsExportServiceServer) {
	// If the following call pancis, it indicates UnimplementedCallAnalyticsExportServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CallAnalyticsExportService_ServiceDesc, srv)
}

func _CallAnalyticsExportService_ExportAnalytics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExportAnalyticsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CallAnalyticsExportServiceServer).ExportAnalytics(m, &grpc.GenericServerStream[ExportAnalyticsRequest, ExportChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CallAnalyticsExportService_ExportAnalyticsServer = grpc.ServerStreamingServer[ExportChunk]

// CallAnalyticsExportService_ServiceDesc is the grpc.ServiceDesc for CallAnalyticsExportService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CallAnalyticsExportService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "da.proto.CallAnalyticsExportService",
	HandlerType: (*CallAnalyticsExportServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExportAnalytics",
			Handler:       _CallAnalyticsExportService_ExportAnalytics_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "call_analytics_export.proto",
}
