// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.4
// source: call_analytics_realtime.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CallAnalyticsRealtimeService_StreamRealtimeAnalytics_FullMethodName = "/da.proto.CallAnalyticsRealtimeService/StreamRealtimeAnalytics"
)

// CallAnalyticsRealtimeServiceClient is the client API for CallAnalyticsRealtimeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CallAnalyticsRealtimeServiceClient interface {
	StreamRealtimeAnalytics(ctx context.Context, in *RealtimeAnalyticsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RealtimeMetricUpdate], error)
}

type callAnalyticsRealtimeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCallAnalyticsRealtimeServiceClient(cc grpc.ClientConnInterface) CallAnalyticsRealtimeServiceClient {
	return &callAnalyticsRealtimeServiceClient{cc}
}

func (c *callAnalyticsRealtimeServiceClient) StreamRealtimeAnalytics(ctx context.Context, in *RealtimeAnalyticsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[RealtimeMetricUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CallAnalyticsRealtimeService_ServiceDesc.Streams[0], CallAnalyticsRealtimeService_StreamRealtimeAnalytics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RealtimeAnalyticsRequest, RealtimeMetricUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CallAnalyticsRealtimeService_StreamRealtimeAnalyticsClient = grpc.ServerStreamingClient[RealtimeMetricUpdate]

// CallAnalyticsRealtimeServiceServer is the server API for CallAnalyticsRealtimeService service.
// All implementations must embed UnimplementedCallAnalyticsRealtimeServiceServer
// for forward compatibility.
type CallAnalyticsRealtimeServiceServer interface {
	StreamRealtimeAnalytics(*RealtimeAnalyticsRequest, grpc.ServerStreamingServer[RealtimeMetricUpdate]) error
	mustEmbedUnimplementedCallAnalyticsRealtimeServiceServer()
}

// UnimplementedCallAnalyticsRealtimeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCallAnalyticsRealtimeServiceServer struct{}

func (UnimplementedCallAnalyticsRealtimeServiceServer) StreamRealtimeAnalytics(*RealtimeAnalyticsRequest, grpc.ServerStreamingServer[RealtimeMetricUpdate]) error {
	return status.Errorf(codes.Unimplemented, "method StreamRealtimeAnalytics not implemented")
}
func (UnimplementedCallAnalyticsRealtimeServiceServer) mustEmbedUnimplementedCallAnalyticsRealtimeServiceServer() {
}
func (UnimplementedCallAnalyticsRealtimeServiceServer) testEmbeddedByValue() {}

// UnsafeCallAnalyticsRealtimeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CallAnalyticsRealtimeServiceServer will
// result in compilation errors.
type UnsafeCallAnalyticsRealtimeServiceServer interface {
	mustEmbedUnimplementedCallAnalyticsRealtimeServiceServer()
}

func RegisterCallAnalyticsRealtimeServiceServer(s grpc.ServiceRegistrar, srv CallAnalyticsRealtimeServiceServer) {
	// If the following call pancis, it indicates UnimplementedCallAnalyticsRealtimeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CallAnalyticsRealtimeService_ServiceDesc, srv)
}

func _CallAnalyticsRealtimeService_StreamRealtimeAnalytics_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RealtimeAnalyticsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CallAnalyticsRealtimeServiceServer).StreamRealtimeAnalytics(m, &grpc.GenericServerStream[RealtimeAnalyticsRequest, RealtimeMetricUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CallAnalyticsRealtimeService_StreamRealtimeAnalyticsServer = grpc.ServerStreamingServer[RealtimeMetricUpdate]

// CallAnalyticsRealtimeService_ServiceDesc is the grpc.ServiceDesc for CallAnalyticsRealtimeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CallAnalyticsRealtimeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "da.proto.CallAnalyticsRealtimeService",
	HandlerType: (*CallAnalyticsRealtimeServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamRealtimeAnalytics",
			Handler:       _CallAnalyticsRealtimeService_StreamRealtimeAnalytics_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "call_analytics_realtime.proto",
}
