// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.4
// source: campaigns.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Campaign drives a broadcast send across one channel to an audience.
// Channel-specific payload lives in `payload` JSONB so the same model serves
// WhatsApp template sends, SMS blasts, and (later) email blasts.
type Campaign struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrgId         string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	WorkspaceId   string                 `protobuf:"bytes,3,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Channel       string                 `protobuf:"bytes,6,opt,name=channel,proto3" json:"channel,omitempty"` // "whatsapp" | "sms" | "email"
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`   // "draft" | "scheduled" | "running" | "paused" | "completed" | "cancelled"
	Audience      *CampaignAudience      `protobuf:"bytes,8,opt,name=audience,proto3" json:"audience,omitempty"`
	Schedule      *CampaignSchedule      `protobuf:"bytes,9,opt,name=schedule,proto3" json:"schedule,omitempty"`
	Payload       *structpb.Struct       `protobuf:"bytes,10,opt,name=payload,proto3" json:"payload,omitempty"` // channel-specific (e.g. WA template ref + parameters)
	Stats         *CampaignStats         `protobuf:"bytes,11,opt,name=stats,proto3" json:"stats,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,12,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Campaign) Reset() {
	*x = Campaign{}
	mi := &file_campaigns_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Campaign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Campaign) ProtoMessage() {}

func (x *Campaign) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Campaign.ProtoReflect.Descriptor instead.
func (*Campaign) Descriptor() ([]byte, []int) {
	return file_campaigns_proto_rawDescGZIP(), []int{0}
}

func (x *Campaign) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Campaign) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *Campaign) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *Campaign) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Campaign) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Campaign) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *Campaign) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Campaign) GetAudience() *CampaignAudience {
	if x != nil {
		return x.Audience
	}
	return nil
}

func (x *Campaign) GetSchedule() *CampaignSchedule {
	if x != nil {
		return x.Schedule
	}
	return nil
}

func (x *Campaign) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Campaign) GetStats() *CampaignStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *Campaign) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Campaign) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Campaign) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CampaignAudience resolves to a concrete recipient list at send time.
// v1 supports two shapes:
//   - object_query: filter against Object Core records of a given type_slug.
//   - explicit:     a fixed list of object_ids (e.g. uploaded CSV).
type CampaignAudience struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`                            // "object_query" | "explicit"
	TypeSlug      string                 `protobuf:"bytes,2,opt,name=type_slug,json=typeSlug,proto3" json:"type_slug,omitempty"`    // for object_query, e.g. "contact"
	Filter        *structpb.Struct       `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`                        // for object_query, JSONB-shaped filter
	ObjectIds     []string               `protobuf:"bytes,4,rep,name=object_ids,json=objectIds,proto3" json:"object_ids,omitempty"` // for explicit
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CampaignAudience) Reset() {
	*x = CampaignAudience{}
	mi := &file_campaigns_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CampaignAudience) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CampaignAudience) ProtoMessage() {}

func (x *CampaignAudience) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CampaignAudience.ProtoReflect.Descriptor instead.
func (*CampaignAudience) Descriptor() ([]byte, []int) {
	return file_campaigns_proto_rawDescGZIP(), []int{1}
}

func (x *CampaignAudience) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *CampaignAudience) GetTypeSlug() string {
	if x != nil {
		return x.TypeSlug
	}
	return ""
}

func (x *CampaignAudience) GetFilter() *structpb.Struct {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *CampaignAudience) GetObjectIds() []string {
	if x != nil {
		return x.ObjectIds
	}
	return nil
}

// CampaignSchedule controls when sends happen.
// One-shot sends use Temporal workflow.Sleep until start_at; recurring sends
// use Temporal Schedules (cron-style) on the same task queue.
type CampaignSchedule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`                      // "immediate" | "scheduled_once" | "recurring"
	StartAt       *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"` // for scheduled_once
	Cron          string                 `protobuf:"bytes,3,opt,name=cron,proto3" json:"cron,omitempty"`                      // for recurring, e.g. "0 9 * * MON"
	Timezone      string                 `protobuf:"bytes,4,opt,name=timezone,proto3" json:"timezone,omitempty"`              // IANA tz (e.g. "Africa/Nairobi") for cron interpretation
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CampaignSchedule) Reset() {
	*x = CampaignSchedule{}
	mi := &file_campaigns_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CampaignSchedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CampaignSchedule) ProtoMessage() {}

func (x *CampaignSchedule) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CampaignSchedule.ProtoReflect.Descriptor instead.
func (*CampaignSchedule) Descriptor() ([]byte, []int) {
	return file_campaigns_proto_rawDescGZIP(), []int{2}
}

func (x *CampaignSchedule) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *CampaignSchedule) GetStartAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartAt
	}
	return nil
}

func (x *CampaignSchedule) GetCron() string {
	if x != nil {
		return x.Cron
	}
	return ""
}

func (x *CampaignSchedule) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type CampaignStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudienceSize  int64                  `protobuf:"varint,1,opt,name=audience_size,json=audienceSize,proto3" json:"audience_size,omitempty"`
	Queued        int64                  `protobuf:"varint,2,opt,name=queued,proto3" json:"queued,omitempty"`
	Sent          int64                  `protobuf:"varint,3,opt,name=sent,proto3" json:"sent,omitempty"`
	Delivered     int64                  `protobuf:"varint,4,opt,name=delivered,proto3" json:"delivered,omitempty"`
	Read          int64                  `protobuf:"varint,5,opt,name=read,proto3" json:"read,omitempty"`
	Failed        int64                  `protobuf:"varint,6,opt,name=failed,proto3" json:"failed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CampaignStats) Reset() {
	*x = CampaignStats{}
	mi := &file_campaigns_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CampaignStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CampaignStats) ProtoMessage() {}

func (x *CampaignStats) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CampaignStats.ProtoReflect.Descriptor instead.
func (*CampaignStats) Descriptor() ([]byte, []int) {
	return file_campaigns_proto_rawDescGZIP(), []int{3}
}

func (x *CampaignStats) GetAudienceSize() int64 {
	if x != nil {
		return x.AudienceSize
	}
	return 0
}

func (x *CampaignStats) GetQueued() int64 {
	if x != nil {
		return x.Queued
	}
	return 0
}

func (x *CampaignStats) GetSent() int64 {
	if x != nil {
		return x.Sent
	}
	return 0
}

func (x *CampaignStats) GetDelivered() int64 {
	if x != nil {
		return x.Delivered
	}
	return 0
}

func (x *CampaignStats) GetRead() int64 {
	if x != nil {
		return x.Read
	}
	return 0
}

func (x *CampaignStats) GetFailed() int64 {
	if x != nil {
		return x.Failed
	}
	return 0
}

// CampaignRecipient is one row of a campaign's audience post-resolution.
type CampaignRecipient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CampaignId    string                 `protobuf:"bytes,2,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	OrgId         string                 `protobuf:"bytes,3,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	ObjectId      string                 `protobuf:"bytes,4,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`       // the Object Core record this row targets
	ContactRef    string                 `protobuf:"bytes,5,opt,name=contact_ref,json=contactRef,proto3" json:"contact_ref,omitempty"` // resolved phone/email used to send (snapshot)
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`                           // "queued" | "sent" | "delivered" | "read" | "failed"
	ExternalId    string                 `protobuf:"bytes,7,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"` // provider message ID (for delivery webhooks)
	Error         string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	DeliveredAt   *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=delivered_at,json=deliveredAt,proto3" json:"delivered_at,omitempty"`
	ReadAt        *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=read_at,json=readAt,proto3" json:"read_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CampaignRecipient) Reset() {
	*x = CampaignRecipient{}
	mi := &file_campaigns_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CampaignRecipient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CampaignRecipient) ProtoMessage() {}

func (x *CampaignRecipient) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CampaignRecipient.ProtoReflect.Descriptor instead.
func (*CampaignRecipient) Descriptor() ([]byte, []int) {
	return file_campaigns_proto_rawDescGZIP(), []int{4}
}

func (x *CampaignRecipient) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CampaignRecipient) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *CampaignRecipient) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *CampaignRecipient) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *CampaignRecipient) GetContactRef() string {
	if x != nil {
		return x.ContactRef
	}
	return ""
}

func (x *CampaignRecipient) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CampaignRecipient) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *CampaignRecipient) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CampaignRecipient) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *CampaignRecipient) GetDeliveredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeliveredAt
	}
	return nil
}

func (x *CampaignRecipient) GetReadAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReadAt
	}
	return nil
}

// WhatsAppTemplate is a local copy of a Meta-approved template.
// Synced from Meta either manually (admin paste) or via a periodic job; we
// don't trust ourselves to know template state without Meta's stamp.
type WhatsAppTemplate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrgId          string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Name           string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`         // Meta template name
	Language       string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"` // e.g. "en_US"
	Category       string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"` // MARKETING | UTILITY | AUTHENTICATION
	Status         string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`     // APPROVED | PENDING | REJECTED
	Header         string                 `protobuf:"bytes,7,opt,name=header,proto3" json:"header,omitempty"`
	Body           string                 `protobuf:"bytes,8,opt,name=body,proto3" json:"body,omitempty"`
	Footer         string                 `protobuf:"bytes,9,opt,name=footer,proto3" json:"footer,omitempty"`
	PhoneNumberId  string                 `protobuf:"bytes,10,opt,name=phone_number_id,json=phoneNumberId,proto3" json:"phone_number_id,omitempty"`
	WabaId         string                 `protobuf:"bytes,11,opt,name=waba_id,json=wabaId,proto3" json:"waba_id,omitempty"`
	MetaTemplateId string                 `protobuf:"bytes,12,opt,name=meta_template_id,json=metaTemplateId,proto3" json:"meta_template_id,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WhatsAppTemplate) Reset() {
	*x = WhatsAppTemplate{}
	mi := &file_campaigns_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhatsAppTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhatsAppTemplate) ProtoMessage() {}

func (x *WhatsAppTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhatsAppTemplate.ProtoReflect.Descriptor instead.
func (*WhatsAppTemplate) Descriptor() ([]byte, []int) {
	return file_campaigns_proto_rawDescGZIP(), []int{5}
}

func (x *WhatsAppTemplate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WhatsAppTemplate) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *WhatsAppTemplate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WhatsAppTemplate) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *WhatsAppTemplate) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *WhatsAppTemplate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WhatsAppTemplate) GetHeader() string {
	if x != nil {
		return x.Header
	}
	return ""
}

func (x *WhatsAppTemplate) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *WhatsAppTemplate) GetFooter() string {
	if x != nil {
		return x.Footer
	}
	return ""
}

func (x *WhatsAppTemplate) GetPhoneNumberId() string {
	if x != nil {
		return x.PhoneNumberId
	}
	return ""
}

func (x *WhatsAppTemplate) GetWabaId() string {
	if x != nil {
		return x.WabaId
	}
	return ""
}

func (x *WhatsAppTemplate) GetMetaTemplateId() string {
	if x != nil {
		return x.MetaTemplateId
	}
	return ""
}

func (x *WhatsAppTemplate) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *WhatsAppTemplate) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateCampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Campaign      *Campaign              `protobuf:"bytes,1,opt,name=campaign,proto3" json:"campaign,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCampaignRequest) Reset() {
	*x = CreateCampaignRequest{}
	mi := &file_campaigns_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCampaignRequest) ProtoMessage() {}

func (x *CreateCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCampaignRequest.ProtoReflect.Descriptor instead.
func (*CreateCampaignRequest) Descriptor() ([]byte, []int) {
	return file_campaigns_proto_rawDescGZIP(), []int{6}
}

func (x *CreateCampaignRequest) GetCampaign() *Campaign {
	if x != nil {
		return x.Campaign
	}
	return nil
}

type GetCampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCampaignRequest) Reset() {
	*x = GetCampaignRequest{}
	mi := &file_campaigns_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCampaignRequest) ProtoMessage() {}

func (x *GetCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCampaignRequest.ProtoReflect.Descriptor instead.
func (*GetCampaignRequest) Descriptor() ([]byte, []int) {
	return file_campaigns_proto_rawDescGZIP(), []int{7}
}

func (x *GetCampaignRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListCampaignsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Channel       string                 `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCampaignsRequest) Reset() {
	*x = ListCampaignsRequest{}
	mi := &file_campaigns_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCampaignsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCampaignsRequest) ProtoMessage() {}

func (x *ListCampaignsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCampaignsRequest.ProtoReflect.Descriptor instead.
func (*ListCampaignsRequest) Descriptor() ([]byte, []int) {
	return file_campaigns_proto_rawDescGZIP(), []int{8}
}

func (x *ListCampaignsRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *ListCampaignsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListCampaignsRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *ListCampaignsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListCampaignsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListCampaignsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Campaigns     []*Campaign            `protobuf:"bytes,1,rep,name=campaigns,proto3" json:"campaigns,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCampaignsResponse) Reset() {
	*x = ListCampaignsResponse{}
	mi := &file_campaigns_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCampaignsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCampaignsResponse) ProtoMessage() {}

func (x *ListCampaignsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCampaignsResponse.ProtoReflect.Descriptor instead.
func (*ListCampaignsResponse) Descriptor() ([]byte, []int) {
	return file_campaigns_proto_rawDescGZIP(), []int{9}
}

func (x *ListCampaignsResponse) GetCampaigns() []*Campaign {
	if x != nil {
		return x.Campaigns
	}
	return nil
}

func (x *ListCampaignsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListCampaignsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateCampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Campaign      *Campaign              `protobuf:"bytes,1,opt,name=campaign,proto3" json:"campaign,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCampaignRequest) Reset() {
	*x = UpdateCampaignRequest{}
	mi := &file_campaigns_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCampaignRequest) ProtoMessage() {}

func (x *UpdateCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCampaignRequest.ProtoReflect.Descriptor instead.
func (*UpdateCampaignRequest) Descriptor() ([]byte, []int) {
	return file_campaigns_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateCampaignRequest) GetCampaign() *Campaign {
	if x != nil {
		return x.Campaign
	}
	return nil
}

type DeleteCampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCampaignRequest) Reset() {
	*x = DeleteCampaignRequest{}
	mi := &file_campaigns_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCampaignRequest) ProtoMessage() {}

func (x *DeleteCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCampaignRequest.ProtoReflect.Descriptor instead.
func (*DeleteCampaignRequest) Descriptor() ([]byte, []int) {
	return file_campaigns_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteCampaignRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteCampaignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCampaignResponse) Reset() {
	*x = DeleteCampaignResponse{}
	mi := &file_campaigns_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCampaignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCampaignResponse) ProtoMessage() {}

func (x *DeleteCampaignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCampaignResponse.ProtoReflect.Descriptor instead.
func (*DeleteCampaignResponse) Descriptor() ([]byte, []int) {
	return file_campaigns_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteCampaignResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type LaunchCampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaunchCampaignRequest) Reset() {
	*x = LaunchCampaignRequest{}
	mi := &file_campaigns_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchCampaignRequest) ProtoMessage() {}

func (x *LaunchCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchCampaignRequest.ProtoReflect.Descriptor instead.
func (*LaunchCampaignRequest) Descriptor() ([]byte, []int) {
	return file_campaigns_proto_rawDescGZIP(), []int{13}
}

func (x *LaunchCampaignRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type LaunchCampaignResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status             string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	TemporalWorkflowId string                 `protobuf:"bytes,3,opt,name=temporal_workflow_id,json=temporalWorkflowId,proto3" json:"temporal_workflow_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *LaunchCampaignResponse) Reset() {
	*x = LaunchCampaignResponse{}
	mi := &file_campaigns_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchCampaignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchCampaignResponse) ProtoMessage() {}

func (x *LaunchCampaignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchCampaignResponse.ProtoReflect.Descriptor instead.
func (*LaunchCampaignResponse) Descriptor() ([]byte, []int) {
	return file_campaigns_proto_rawDescGZIP(), []int{14}
}

func (x *LaunchCampaignResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LaunchCampaignResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LaunchCampaignResponse) GetTemporalWorkflowId() string {
	if x != nil {
		return x.TemporalWorkflowId
	}
	return ""
}

type PauseCampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseCampaignRequest) Reset() {
	*x = PauseCampaignRequest{}
	mi := &file_campaigns_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseCampaignRequest) ProtoMessage() {}

func (x *PauseCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseCampaignRequest.ProtoReflect.Descriptor instead.
func (*PauseCampaignRequest) Descriptor() ([]byte, []int) {
	return file_campaigns_proto_rawDescGZIP(), []int{15}
}

func (x *PauseCampaignRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PauseCampaignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseCampaignResponse) Reset() {
	*x = PauseCampaignResponse{}
	mi := &file_campaigns_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseCampaignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseCampaignResponse) ProtoMessage() {}

func (x *PauseCampaignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseCampaignResponse.ProtoReflect.Descriptor instead.
func (*PauseCampaignResponse) Descriptor() ([]byte, []int) {
	return file_campaigns_proto_rawDescGZIP(), []int{16}
}

func (x *PauseCampaignResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PauseCampaignResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CancelCampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelCampaignRequest) Reset() {
	*x = CancelCampaignRequest{}
	mi := &file_campaigns_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelCampaignRequest) ProtoMessage() {}

func (x *CancelCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelCampaignRequest.ProtoReflect.Descriptor instead.
func (*CancelCampaignRequest) Descriptor() ([]byte, []int) {
	return file_campaigns_proto_rawDescGZIP(), []int{17}
}

func (x *CancelCampaignRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CancelCampaignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelCampaignResponse) Reset() {
	*x = CancelCampaignResponse{}
	mi := &file_campaigns_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelCampaignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelCampaignResponse) ProtoMessage() {}

func (x *CancelCampaignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelCampaignResponse.ProtoReflect.Descriptor instead.
func (*CancelCampaignResponse) Descriptor() ([]byte, []int) {
	return file_campaigns_proto_rawDescGZIP(), []int{18}
}

func (x *CancelCampaignResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CancelCampaignResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListRecipientsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecipientsRequest) Reset() {
	*x = ListRecipientsRequest{}
	mi := &file_campaigns_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecipientsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecipientsRequest) ProtoMessage() {}

func (x *ListRecipientsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecipientsRequest.ProtoReflect.Descriptor instead.
func (*ListRecipientsRequest) Descriptor() ([]byte, []int) {
	return file_campaigns_proto_rawDescGZIP(), []int{19}
}

func (x *ListRecipientsRequest) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *ListRecipientsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListRecipientsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRecipientsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListRecipientsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Recipients    []*CampaignRecipient   `protobuf:"bytes,1,rep,name=recipients,proto3" json:"recipients,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRecipientsResponse) Reset() {
	*x = ListRecipientsResponse{}
	mi := &file_campaigns_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRecipientsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRecipientsResponse) ProtoMessage() {}

func (x *ListRecipientsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRecipientsResponse.ProtoReflect.Descriptor instead.
func (*ListRecipientsResponse) Descriptor() ([]byte, []int) {
	return file_campaigns_proto_rawDescGZIP(), []int{20}
}

func (x *ListRecipientsResponse) GetRecipients() []*CampaignRecipient {
	if x != nil {
		return x.Recipients
	}
	return nil
}

func (x *ListRecipientsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListRecipientsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpsertWhatsAppTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      *WhatsAppTemplate      `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertWhatsAppTemplateRequest) Reset() {
	*x = UpsertWhatsAppTemplateRequest{}
	mi := &file_campaigns_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertWhatsAppTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertWhatsAppTemplateRequest) ProtoMessage() {}

func (x *UpsertWhatsAppTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertWhatsAppTemplateRequest.ProtoReflect.Descriptor instead.
func (*UpsertWhatsAppTemplateRequest) Descriptor() ([]byte, []int) {
	return file_campaigns_proto_rawDescGZIP(), []int{21}
}

func (x *UpsertWhatsAppTemplateRequest) GetTemplate() *WhatsAppTemplate {
	if x != nil {
		return x.Template
	}
	return nil
}

type GetWhatsAppTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWhatsAppTemplateRequest) Reset() {
	*x = GetWhatsAppTemplateRequest{}
	mi := &file_campaigns_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWhatsAppTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWhatsAppTemplateRequest) ProtoMessage() {}

func (x *GetWhatsAppTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWhatsAppTemplateRequest.ProtoReflect.Descriptor instead.
func (*GetWhatsAppTemplateRequest) Descriptor() ([]byte, []int) {
	return file_campaigns_proto_rawDescGZIP(), []int{22}
}

func (x *GetWhatsAppTemplateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListWhatsAppTemplatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	PhoneNumberId string                 `protobuf:"bytes,2,opt,name=phone_number_id,json=phoneNumberId,proto3" json:"phone_number_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWhatsAppTemplatesRequest) Reset() {
	*x = ListWhatsAppTemplatesRequest{}
	mi := &file_campaigns_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWhatsAppTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWhatsAppTemplatesRequest) ProtoMessage() {}

func (x *ListWhatsAppTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWhatsAppTemplatesRequest.ProtoReflect.Descriptor instead.
func (*ListWhatsAppTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_campaigns_proto_rawDescGZIP(), []int{23}
}

func (x *ListWhatsAppTemplatesRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListWhatsAppTemplatesRequest) GetPhoneNumberId() string {
	if x != nil {
		return x.PhoneNumberId
	}
	return ""
}

type ListWhatsAppTemplatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Templates     []*WhatsAppTemplate    `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWhatsAppTemplatesResponse) Reset() {
	*x = ListWhatsAppTemplatesResponse{}
	mi := &file_campaigns_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWhatsAppTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWhatsAppTemplatesResponse) ProtoMessage() {}

func (x *ListWhatsAppTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWhatsAppTemplatesResponse.ProtoReflect.Descriptor instead.
func (*ListWhatsAppTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_campaigns_proto_rawDescGZIP(), []int{24}
}

func (x *ListWhatsAppTemplatesResponse) GetTemplates() []*WhatsAppTemplate {
	if x != nil {
		return x.Templates
	}
	return nil
}

type DeleteWhatsAppTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWhatsAppTemplateRequest) Reset() {
	*x = DeleteWhatsAppTemplateRequest{}
	mi := &file_campaigns_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWhatsAppTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWhatsAppTemplateRequest) ProtoMessage() {}

func (x *DeleteWhatsAppTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWhatsAppTemplateRequest.ProtoReflect.Descriptor instead.
func (*DeleteWhatsAppTemplateRequest) Descriptor() ([]byte, []int) {
	return file_campaigns_proto_rawDescGZIP(), []int{25}
}

func (x *DeleteWhatsAppTemplateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteWhatsAppTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWhatsAppTemplateResponse) Reset() {
	*x = DeleteWhatsAppTemplateResponse{}
	mi := &file_campaigns_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWhatsAppTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWhatsAppTemplateResponse) ProtoMessage() {}

func (x *DeleteWhatsAppTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWhatsAppTemplateResponse.ProtoReflect.Descriptor instead.
func (*DeleteWhatsAppTemplateResponse) Descriptor() ([]byte, []int) {
	return file_campaigns_proto_rawDescGZIP(), []int{26}
}

func (x *DeleteWhatsAppTemplateResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_campaigns_proto protoreflect.FileDescriptor

const file_campaigns_proto_rawDesc = "" +
	"\n" +
	"\x0fcampaigns.proto\x12\bda.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa3\x04\n" +
	"\bCampaign\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12!\n" +
	"\fworkspace_id\x18\x03 \x01(\tR\vworkspaceId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x18\n" +
	"\achannel\x18\x06 \x01(\tR\achannel\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x126\n" +
	"\baudience\x18\b \x01(\v2\x1a.da.proto.CampaignAudienceR\baudience\x126\n" +
	"\bschedule\x18\t \x01(\v2\x1a.da.proto.CampaignScheduleR\bschedule\x121\n" +
	"\apayload\x18\n" +
	" \x01(\v2\x17.google.protobuf.StructR\apayload\x12-\n" +
	"\x05stats\x18\v \x01(\v2\x17.da.proto.CampaignStatsR\x05stats\x12\x1d\n" +
	"\n" +
	"created_by\x18\f \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x93\x01\n" +
	"\x10CampaignAudience\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1b\n" +
	"\ttype_slug\x18\x02 \x01(\tR\btypeSlug\x12/\n" +
	"\x06filter\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06filter\x12\x1d\n" +
	"\n" +
	"object_ids\x18\x04 \x03(\tR\tobjectIds\"\x8d\x01\n" +
	"\x10CampaignSchedule\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x125\n" +
	"\bstart_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\astartAt\x12\x12\n" +
	"\x04cron\x18\x03 \x01(\tR\x04cron\x12\x1a\n" +
	"\btimezone\x18\x04 \x01(\tR\btimezone\"\xaa\x01\n" +
	"\rCampaignStats\x12#\n" +
	"\raudience_size\x18\x01 \x01(\x03R\faudienceSize\x12\x16\n" +
	"\x06queued\x18\x02 \x01(\x03R\x06queued\x12\x12\n" +
	"\x04sent\x18\x03 \x01(\x03R\x04sent\x12\x1c\n" +
	"\tdelivered\x18\x04 \x01(\x03R\tdelivered\x12\x12\n" +
	"\x04read\x18\x05 \x01(\x03R\x04read\x12\x16\n" +
	"\x06failed\x18\x06 \x01(\x03R\x06failed\"\x91\x03\n" +
	"\x11CampaignRecipient\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcampaign_id\x18\x02 \x01(\tR\n" +
	"campaignId\x12\x15\n" +
	"\x06org_id\x18\x03 \x01(\tR\x05orgId\x12\x1b\n" +
	"\tobject_id\x18\x04 \x01(\tR\bobjectId\x12\x1f\n" +
	"\vcontact_ref\x18\x05 \x01(\tR\n" +
	"contactRef\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1f\n" +
	"\vexternal_id\x18\a \x01(\tR\n" +
	"externalId\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\x123\n" +
	"\asent_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x12=\n" +
	"\fdelivered_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\vdeliveredAt\x123\n" +
	"\aread_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\x06readAt\"\xc2\x03\n" +
	"\x10WhatsAppTemplate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x16\n" +
	"\x06header\x18\a \x01(\tR\x06header\x12\x12\n" +
	"\x04body\x18\b \x01(\tR\x04body\x12\x16\n" +
	"\x06footer\x18\t \x01(\tR\x06footer\x12&\n" +
	"\x0fphone_number_id\x18\n" +
	" \x01(\tR\rphoneNumberId\x12\x17\n" +
	"\awaba_id\x18\v \x01(\tR\x06wabaId\x12(\n" +
	"\x10meta_template_id\x18\f \x01(\tR\x0emetaTemplateId\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"G\n" +
	"\x15CreateCampaignRequest\x12.\n" +
	"\bcampaign\x18\x01 \x01(\v2\x12.da.proto.CampaignR\bcampaign\"$\n" +
	"\x12GetCampaignRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xa7\x01\n" +
	"\x14ListCampaignsRequest\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\achannel\x18\x03 \x01(\tR\achannel\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x05 \x01(\tR\tpageToken\"\x87\x01\n" +
	"\x15ListCampaignsResponse\x120\n" +
	"\tcampaigns\x18\x01 \x03(\v2\x12.da.proto.CampaignR\tcampaigns\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\"G\n" +
	"\x15UpdateCampaignRequest\x12.\n" +
	"\bcampaign\x18\x01 \x01(\v2\x12.da.proto.CampaignR\bcampaign\"'\n" +
	"\x15DeleteCampaignRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"(\n" +
	"\x16DeleteCampaignResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"'\n" +
	"\x15LaunchCampaignRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"r\n" +
	"\x16LaunchCampaignResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x120\n" +
	"\x14temporal_workflow_id\x18\x03 \x01(\tR\x12temporalWorkflowId\"&\n" +
	"\x14PauseCampaignRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"?\n" +
	"\x15PauseCampaignResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"'\n" +
	"\x15CancelCampaignRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"@\n" +
	"\x16CancelCampaignResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\x8c\x01\n" +
	"\x15ListRecipientsRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"\x93\x01\n" +
	"\x16ListRecipientsResponse\x12;\n" +
	"\n" +
	"recipients\x18\x01 \x03(\v2\x1b.da.proto.CampaignRecipientR\n" +
	"recipients\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\"W\n" +
	"\x1dUpsertWhatsAppTemplateRequest\x126\n" +
	"\btemplate\x18\x01 \x01(\v2\x1a.da.proto.WhatsAppTemplateR\btemplate\",\n" +
	"\x1aGetWhatsAppTemplateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"^\n" +
	"\x1cListWhatsAppTemplatesRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12&\n" +
	"\x0fphone_number_id\x18\x02 \x01(\tR\rphoneNumberId\"Y\n" +
	"\x1dListWhatsAppTemplatesResponse\x128\n" +
	"\ttemplates\x18\x01 \x03(\v2\x1a.da.proto.WhatsAppTemplateR\ttemplates\"/\n" +
	"\x1dDeleteWhatsAppTemplateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"0\n" +
	"\x1eDeleteWhatsAppTemplateResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xe7\b\n" +
	"\x0fCampaignService\x12E\n" +
	"\x0eCreateCampaign\x12\x1f.da.proto.CreateCampaignRequest\x1a\x12.da.proto.Campaign\x12?\n" +
	"\vGetCampaign\x12\x1c.da.proto.GetCampaignRequest\x1a\x12.da.proto.Campaign\x12P\n" +
	"\rListCampaigns\x12\x1e.da.proto.ListCampaignsRequest\x1a\x1f.da.proto.ListCampaignsResponse\x12E\n" +
	"\x0eUpdateCampaign\x12\x1f.da.proto.UpdateCampaignRequest\x1a\x12.da.proto.Campaign\x12S\n" +
	"\x0eDeleteCampaign\x12\x1f.da.proto.DeleteCampaignRequest\x1a .da.proto.DeleteCampaignResponse\x12S\n" +
	"\x0eLaunchCampaign\x12\x1f.da.proto.LaunchCampaignRequest\x1a .da.proto.LaunchCampaignResponse\x12P\n" +
	"\rPauseCampaign\x12\x1e.da.proto.PauseCampaignRequest\x1a\x1f.da.proto.PauseCampaignResponse\x12S\n" +
	"\x0eCancelCampaign\x12\x1f.da.proto.CancelCampaignRequest\x1a .da.proto.CancelCampaignResponse\x12S\n" +
	"\x0eListRecipients\x12\x1f.da.proto.ListRecipientsRequest\x1a .da.proto.ListRecipientsResponse\x12]\n" +
	"\x16UpsertWhatsAppTemplate\x12'.da.proto.UpsertWhatsAppTemplateRequest\x1a\x1a.da.proto.WhatsAppTemplate\x12W\n" +
	"\x13GetWhatsAppTemplate\x12$.da.proto.GetWhatsAppTemplateRequest\x1a\x1a.da.proto.WhatsAppTemplate\x12h\n" +
	"\x15ListWhatsAppTemplates\x12&.da.proto.ListWhatsAppTemplatesRequest\x1a'.da.proto.ListWhatsAppTemplatesResponse\x12k\n" +
	"\x16DeleteWhatsAppTemplate\x12'.da.proto.DeleteWhatsAppTemplateRequest\x1a(.da.proto.DeleteWhatsAppTemplateResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_campaigns_proto_rawDescOnce sync.Once
	file_campaigns_proto_rawDescData []byte
)

func file_campaigns_proto_rawDescGZIP() []byte {
	file_campaigns_proto_rawDescOnce.Do(func() {
		file_campaigns_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_campaigns_proto_rawDesc), len(file_campaigns_proto_rawDesc)))
	})
	return file_campaigns_proto_rawDescData
}

var file_campaigns_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_campaigns_proto_goTypes = []any{
	(*Campaign)(nil),                       // 0: da.proto.Campaign
	(*CampaignAudience)(nil),               // 1: da.proto.CampaignAudience
	(*CampaignSchedule)(nil),               // 2: da.proto.CampaignSchedule
	(*CampaignStats)(nil),                  // 3: da.proto.CampaignStats
	(*CampaignRecipient)(nil),              // 4: da.proto.CampaignRecipient
	(*WhatsAppTemplate)(nil),               // 5: da.proto.WhatsAppTemplate
	(*CreateCampaignRequest)(nil),          // 6: da.proto.CreateCampaignRequest
	(*GetCampaignRequest)(nil),             // 7: da.proto.GetCampaignRequest
	(*ListCampaignsRequest)(nil),           // 8: da.proto.ListCampaignsRequest
	(*ListCampaignsResponse)(nil),          // 9: da.proto.ListCampaignsResponse
	(*UpdateCampaignRequest)(nil),          // 10: da.proto.UpdateCampaignRequest
	(*DeleteCampaignRequest)(nil),          // 11: da.proto.DeleteCampaignRequest
	(*DeleteCampaignResponse)(nil),         // 12: da.proto.DeleteCampaignResponse
	(*LaunchCampaignRequest)(nil),          // 13: da.proto.LaunchCampaignRequest
	(*LaunchCampaignResponse)(nil),         // 14: da.proto.LaunchCampaignResponse
	(*PauseCampaignRequest)(nil),           // 15: da.proto.PauseCampaignRequest
	(*PauseCampaignResponse)(nil),          // 16: da.proto.PauseCampaignResponse
	(*CancelCampaignRequest)(nil),          // 17: da.proto.CancelCampaignRequest
	(*CancelCampaignResponse)(nil),         // 18: da.proto.CancelCampaignResponse
	(*ListRecipientsRequest)(nil),          // 19: da.proto.ListRecipientsRequest
	(*ListRecipientsResponse)(nil),         // 20: da.proto.ListRecipientsResponse
	(*UpsertWhatsAppTemplateRequest)(nil),  // 21: da.proto.UpsertWhatsAppTemplateRequest
	(*GetWhatsAppTemplateRequest)(nil),     // 22: da.proto.GetWhatsAppTemplateRequest
	(*ListWhatsAppTemplatesRequest)(nil),   // 23: da.proto.ListWhatsAppTemplatesRequest
	(*ListWhatsAppTemplatesResponse)(nil),  // 24: da.proto.ListWhatsAppTemplatesResponse
	(*DeleteWhatsAppTemplateRequest)(nil),  // 25: da.proto.DeleteWhatsAppTemplateRequest
	(*DeleteWhatsAppTemplateResponse)(nil), // 26: da.proto.DeleteWhatsAppTemplateResponse
	(*structpb.Struct)(nil),                // 27: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),          // 28: google.protobuf.Timestamp
}
var file_campaigns_proto_depIdxs = []int32{
	1,  // 0: da.proto.Campaign.audience:type_name -> da.proto.CampaignAudience
	2,  // 1: da.proto.Campaign.schedule:type_name -> da.proto.CampaignSchedule
	27, // 2: da.proto.Campaign.payload:type_name -> google.protobuf.Struct
	3,  // 3: da.proto.Campaign.stats:type_name -> da.proto.CampaignStats
	28, // 4: da.proto.Campaign.created_at:type_name -> google.protobuf.Timestamp
	28, // 5: da.proto.Campaign.updated_at:type_name -> google.protobuf.Timestamp
	27, // 6: da.proto.CampaignAudience.filter:type_name -> google.protobuf.Struct
	28, // 7: da.proto.CampaignSchedule.start_at:type_name -> google.protobuf.Timestamp
	28, // 8: da.proto.CampaignRecipient.sent_at:type_name -> google.protobuf.Timestamp
	28, // 9: da.proto.CampaignRecipient.delivered_at:type_name -> google.protobuf.Timestamp
	28, // 10: da.proto.CampaignRecipient.read_at:type_name -> google.protobuf.Timestamp
	28, // 11: da.proto.WhatsAppTemplate.created_at:type_name -> google.protobuf.Timestamp
	28, // 12: da.proto.WhatsAppTemplate.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 13: da.proto.CreateCampaignRequest.campaign:type_name -> da.proto.Campaign
	0,  // 14: da.proto.ListCampaignsResponse.campaigns:type_name -> da.proto.Campaign
	0,  // 15: da.proto.UpdateCampaignRequest.campaign:type_name -> da.proto.Campaign
	4,  // 16: da.proto.ListRecipientsResponse.recipients:type_name -> da.proto.CampaignRecipient
	5,  // 17: da.proto.UpsertWhatsAppTemplateRequest.template:type_name -> da.proto.WhatsAppTemplate
	5,  // 18: da.proto.ListWhatsAppTemplatesResponse.templates:type_name -> da.proto.WhatsAppTemplate
	6,  // 19: da.proto.CampaignService.CreateCampaign:input_type -> da.proto.CreateCampaignRequest
	7,  // 20: da.proto.CampaignService.GetCampaign:input_type -> da.proto.GetCampaignRequest
	8,  // 21: da.proto.CampaignService.ListCampaigns:input_type -> da.proto.ListCampaignsRequest
	10, // 22: da.proto.CampaignService.UpdateCampaign:input_type -> da.proto.UpdateCampaignRequest
	11, // 23: da.proto.CampaignService.DeleteCampaign:input_type -> da.proto.DeleteCampaignRequest
	13, // 24: da.proto.CampaignService.LaunchCampaign:input_type -> da.proto.LaunchCampaignRequest
	15, // 25: da.proto.CampaignService.PauseCampaign:input_type -> da.proto.PauseCampaignRequest
	17, // 26: da.proto.CampaignService.CancelCampaign:input_type -> da.proto.CancelCampaignRequest
	19, // 27: da.proto.CampaignService.ListRecipients:input_type -> da.proto.ListRecipientsRequest
	21, // 28: da.proto.CampaignService.UpsertWhatsAppTemplate:input_type -> da.proto.UpsertWhatsAppTemplateRequest
	22, // 29: da.proto.CampaignService.GetWhatsAppTemplate:input_type -> da.proto.GetWhatsAppTemplateRequest
	23, // 30: da.proto.CampaignService.ListWhatsAppTemplates:input_type -> da.proto.ListWhatsAppTemplatesRequest
	25, // 31: da.proto.CampaignService.DeleteWhatsAppTemplate:input_type -> da.proto.DeleteWhatsAppTemplateRequest
	0,  // 32: da.proto.CampaignService.CreateCampaign:output_type -> da.proto.Campaign
	0,  // 33: da.proto.CampaignService.GetCampaign:output_type -> da.proto.Campaign
	9,  // 34: da.proto.CampaignService.ListCampaigns:output_type -> da.proto.ListCampaignsResponse
	0,  // 35: da.proto.CampaignService.UpdateCampaign:output_type -> da.proto.Campaign
	12, // 36: da.proto.CampaignService.DeleteCampaign:output_type -> da.proto.DeleteCampaignResponse
	14, // 37: da.proto.CampaignService.LaunchCampaign:output_type -> da.proto.LaunchCampaignResponse
	16, // 38: da.proto.CampaignService.PauseCampaign:output_type -> da.proto.PauseCampaignResponse
	18, // 39: da.proto.CampaignService.CancelCampaign:output_type -> da.proto.CancelCampaignResponse
	20, // 40: da.proto.CampaignService.ListRecipients:output_type -> da.proto.ListRecipientsResponse
	5,  // 41: da.proto.CampaignService.UpsertWhatsAppTemplate:output_type -> da.proto.WhatsAppTemplate
	5,  // 42: da.proto.CampaignService.GetWhatsAppTemplate:output_type -> da.proto.WhatsAppTemplate
	24, // 43: da.proto.CampaignService.ListWhatsAppTemplates:output_type -> da.proto.ListWhatsAppTemplatesResponse
	26, // 44: da.proto.CampaignService.DeleteWhatsAppTemplate:output_type -> da.proto.DeleteWhatsAppTemplateResponse
	32, // [32:45] is the sub-list for method output_type
	19, // [19:32] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_campaigns_proto_init() }
func file_campaigns_proto_init() {
	if File_campaigns_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_campaigns_proto_rawDesc), len(file_campaigns_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_campaigns_proto_goTypes,
		DependencyIndexes: file_campaigns_proto_depIdxs,
		MessageInfos:      file_campaigns_proto_msgTypes,
	}.Build()
	File_campaigns_proto = out.File
	file_campaigns_proto_goTypes = nil
	file_campaigns_proto_depIdxs = nil
}
