// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.4
// source: campaigns.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CampaignService_CreateCampaign_FullMethodName         = "/da.proto.CampaignService/CreateCampaign"
	CampaignService_GetCampaign_FullMethodName            = "/da.proto.CampaignService/GetCampaign"
	CampaignService_ListCampaigns_FullMethodName          = "/da.proto.CampaignService/ListCampaigns"
	CampaignService_UpdateCampaign_FullMethodName         = "/da.proto.CampaignService/UpdateCampaign"
	CampaignService_DeleteCampaign_FullMethodName         = "/da.proto.CampaignService/DeleteCampaign"
	CampaignService_LaunchCampaign_FullMethodName         = "/da.proto.CampaignService/LaunchCampaign"
	CampaignService_PauseCampaign_FullMethodName          = "/da.proto.CampaignService/PauseCampaign"
	CampaignService_CancelCampaign_FullMethodName         = "/da.proto.CampaignService/CancelCampaign"
	CampaignService_ListRecipients_FullMethodName         = "/da.proto.CampaignService/ListRecipients"
	CampaignService_UpsertWhatsAppTemplate_FullMethodName = "/da.proto.CampaignService/UpsertWhatsAppTemplate"
	CampaignService_GetWhatsAppTemplate_FullMethodName    = "/da.proto.CampaignService/GetWhatsAppTemplate"
	CampaignService_ListWhatsAppTemplates_FullMethodName  = "/da.proto.CampaignService/ListWhatsAppTemplates"
	CampaignService_DeleteWhatsAppTemplate_FullMethodName = "/da.proto.CampaignService/DeleteWhatsAppTemplate"
)

// CampaignServiceClient is the client API for CampaignService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CampaignServiceClient interface {
	// Campaign CRUD
	CreateCampaign(ctx context.Context, in *CreateCampaignRequest, opts ...grpc.CallOption) (*Campaign, error)
	GetCampaign(ctx context.Context, in *GetCampaignRequest, opts ...grpc.CallOption) (*Campaign, error)
	ListCampaigns(ctx context.Context, in *ListCampaignsRequest, opts ...grpc.CallOption) (*ListCampaignsResponse, error)
	UpdateCampaign(ctx context.Context, in *UpdateCampaignRequest, opts ...grpc.CallOption) (*Campaign, error)
	DeleteCampaign(ctx context.Context, in *DeleteCampaignRequest, opts ...grpc.CallOption) (*DeleteCampaignResponse, error)
	// Lifecycle
	LaunchCampaign(ctx context.Context, in *LaunchCampaignRequest, opts ...grpc.CallOption) (*LaunchCampaignResponse, error)
	PauseCampaign(ctx context.Context, in *PauseCampaignRequest, opts ...grpc.CallOption) (*PauseCampaignResponse, error)
	CancelCampaign(ctx context.Context, in *CancelCampaignRequest, opts ...grpc.CallOption) (*CancelCampaignResponse, error)
	// Recipients
	ListRecipients(ctx context.Context, in *ListRecipientsRequest, opts ...grpc.CallOption) (*ListRecipientsResponse, error)
	// WhatsApp template registry (local mirror)
	UpsertWhatsAppTemplate(ctx context.Context, in *UpsertWhatsAppTemplateRequest, opts ...grpc.CallOption) (*WhatsAppTemplate, error)
	GetWhatsAppTemplate(ctx context.Context, in *GetWhatsAppTemplateRequest, opts ...grpc.CallOption) (*WhatsAppTemplate, error)
	ListWhatsAppTemplates(ctx context.Context, in *ListWhatsAppTemplatesRequest, opts ...grpc.CallOption) (*ListWhatsAppTemplatesResponse, error)
	DeleteWhatsAppTemplate(ctx context.Context, in *DeleteWhatsAppTemplateRequest, opts ...grpc.CallOption) (*DeleteWhatsAppTemplateResponse, error)
}

type campaignServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCampaignServiceClient(cc grpc.ClientConnInterface) CampaignServiceClient {
	return &campaignServiceClient{cc}
}

func (c *campaignServiceClient) CreateCampaign(ctx context.Context, in *CreateCampaignRequest, opts ...grpc.CallOption) (*Campaign, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Campaign)
	err := c.cc.Invoke(ctx, CampaignService_CreateCampaign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignServiceClient) GetCampaign(ctx context.Context, in *GetCampaignRequest, opts ...grpc.CallOption) (*Campaign, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Campaign)
	err := c.cc.Invoke(ctx, CampaignService_GetCampaign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignServiceClient) ListCampaigns(ctx context.Context, in *ListCampaignsRequest, opts ...grpc.CallOption) (*ListCampaignsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCampaignsResponse)
	err := c.cc.Invoke(ctx, CampaignService_ListCampaigns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignServiceClient) UpdateCampaign(ctx context.Context, in *UpdateCampaignRequest, opts ...grpc.CallOption) (*Campaign, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Campaign)
	err := c.cc.Invoke(ctx, CampaignService_UpdateCampaign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignServiceClient) DeleteCampaign(ctx context.Context, in *DeleteCampaignRequest, opts ...grpc.CallOption) (*DeleteCampaignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCampaignResponse)
	err := c.cc.Invoke(ctx, CampaignService_DeleteCampaign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignServiceClient) LaunchCampaign(ctx context.Context, in *LaunchCampaignRequest, opts ...grpc.CallOption) (*LaunchCampaignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LaunchCampaignResponse)
	err := c.cc.Invoke(ctx, CampaignService_LaunchCampaign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignServiceClient) PauseCampaign(ctx context.Context, in *PauseCampaignRequest, opts ...grpc.CallOption) (*PauseCampaignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PauseCampaignResponse)
	err := c.cc.Invoke(ctx, CampaignService_PauseCampaign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignServiceClient) CancelCampaign(ctx context.Context, in *CancelCampaignRequest, opts ...grpc.CallOption) (*CancelCampaignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelCampaignResponse)
	err := c.cc.Invoke(ctx, CampaignService_CancelCampaign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignServiceClient) ListRecipients(ctx context.Context, in *ListRecipientsRequest, opts ...grpc.CallOption) (*ListRecipientsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRecipientsResponse)
	err := c.cc.Invoke(ctx, CampaignService_ListRecipients_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignServiceClient) UpsertWhatsAppTemplate(ctx context.Context, in *UpsertWhatsAppTemplateRequest, opts ...grpc.CallOption) (*WhatsAppTemplate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WhatsAppTemplate)
	err := c.cc.Invoke(ctx, CampaignService_UpsertWhatsAppTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignServiceClient) GetWhatsAppTemplate(ctx context.Context, in *GetWhatsAppTemplateRequest, opts ...grpc.CallOption) (*WhatsAppTemplate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WhatsAppTemplate)
	err := c.cc.Invoke(ctx, CampaignService_GetWhatsAppTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignServiceClient) ListWhatsAppTemplates(ctx context.Context, in *ListWhatsAppTemplatesRequest, opts ...grpc.CallOption) (*ListWhatsAppTemplatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWhatsAppTemplatesResponse)
	err := c.cc.Invoke(ctx, CampaignService_ListWhatsAppTemplates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *campaignServiceClient) DeleteWhatsAppTemplate(ctx context.Context, in *DeleteWhatsAppTemplateRequest, opts ...grpc.CallOption) (*DeleteWhatsAppTemplateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteWhatsAppTemplateResponse)
	err := c.cc.Invoke(ctx, CampaignService_DeleteWhatsAppTemplate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CampaignServiceServer is the server API for CampaignService service.
// All implementations must embed UnimplementedCampaignServiceServer
// for forward compatibility.
type CampaignServiceServer interface {
	// Campaign CRUD
	CreateCampaign(context.Context, *CreateCampaignRequest) (*Campaign, error)
	GetCampaign(context.Context, *GetCampaignRequest) (*Campaign, error)
	ListCampaigns(context.Context, *ListCampaignsRequest) (*ListCampaignsResponse, error)
	UpdateCampaign(context.Context, *UpdateCampaignRequest) (*Campaign, error)
	DeleteCampaign(context.Context, *DeleteCampaignRequest) (*DeleteCampaignResponse, error)
	// Lifecycle
	LaunchCampaign(context.Context, *LaunchCampaignRequest) (*LaunchCampaignResponse, error)
	PauseCampaign(context.Context, *PauseCampaignRequest) (*PauseCampaignResponse, error)
	CancelCampaign(context.Context, *CancelCampaignRequest) (*CancelCampaignResponse, error)
	// Recipients
	ListRecipients(context.Context, *ListRecipientsRequest) (*ListRecipientsResponse, error)
	// WhatsApp template registry (local mirror)
	UpsertWhatsAppTemplate(context.Context, *UpsertWhatsAppTemplateRequest) (*WhatsAppTemplate, error)
	GetWhatsAppTemplate(context.Context, *GetWhatsAppTemplateRequest) (*WhatsAppTemplate, error)
	ListWhatsAppTemplates(context.Context, *ListWhatsAppTemplatesRequest) (*ListWhatsAppTemplatesResponse, error)
	DeleteWhatsAppTemplate(context.Context, *DeleteWhatsAppTemplateRequest) (*DeleteWhatsAppTemplateResponse, error)
	mustEmbedUnimplementedCampaignServiceServer()
}

// UnimplementedCampaignServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCampaignServiceServer struct{}

func (UnimplementedCampaignServiceServer) CreateCampaign(context.Context, *CreateCampaignRequest) (*Campaign, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCampaign not implemented")
}
func (UnimplementedCampaignServiceServer) GetCampaign(context.Context, *GetCampaignRequest) (*Campaign, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCampaign not implemented")
}
func (UnimplementedCampaignServiceServer) ListCampaigns(context.Context, *ListCampaignsRequest) (*ListCampaignsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCampaigns not implemented")
}
func (UnimplementedCampaignServiceServer) UpdateCampaign(context.Context, *UpdateCampaignRequest) (*Campaign, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCampaign not implemented")
}
func (UnimplementedCampaignServiceServer) DeleteCampaign(context.Context, *DeleteCampaignRequest) (*DeleteCampaignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCampaign not implemented")
}
func (UnimplementedCampaignServiceServer) LaunchCampaign(context.Context, *LaunchCampaignRequest) (*LaunchCampaignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LaunchCampaign not implemented")
}
func (UnimplementedCampaignServiceServer) PauseCampaign(context.Context, *PauseCampaignRequest) (*PauseCampaignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PauseCampaign not implemented")
}
func (UnimplementedCampaignServiceServer) CancelCampaign(context.Context, *CancelCampaignRequest) (*CancelCampaignResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelCampaign not implemented")
}
func (UnimplementedCampaignServiceServer) ListRecipients(context.Context, *ListRecipientsRequest) (*ListRecipientsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRecipients not implemented")
}
func (UnimplementedCampaignServiceServer) UpsertWhatsAppTemplate(context.Context, *UpsertWhatsAppTemplateRequest) (*WhatsAppTemplate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertWhatsAppTemplate not implemented")
}
func (UnimplementedCampaignServiceServer) GetWhatsAppTemplate(context.Context, *GetWhatsAppTemplateRequest) (*WhatsAppTemplate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWhatsAppTemplate not implemented")
}
func (UnimplementedCampaignServiceServer) ListWhatsAppTemplates(context.Context, *ListWhatsAppTemplatesRequest) (*ListWhatsAppTemplatesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWhatsAppTemplates not implemented")
}
func (UnimplementedCampaignServiceServer) DeleteWhatsAppTemplate(context.Context, *DeleteWhatsAppTemplateRequest) (*DeleteWhatsAppTemplateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteWhatsAppTemplate not implemented")
}
func (UnimplementedCampaignServiceServer) mustEmbedUnimplementedCampaignServiceServer() {}
func (UnimplementedCampaignServiceServer) testEmbeddedByValue()                         {}

// UnsafeCampaignServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CampaignServiceServer will
// result in compilation errors.
type UnsafeCampaignServiceServer interface {
	mustEmbedUnimplementedCampaignServiceServer()
}

func RegisterCampaignServiceServer(s grpc.ServiceRegistrar, srv CampaignServiceServer) {
	// If the following call pancis, it indicates UnimplementedCampaignServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CampaignService_ServiceDesc, srv)
}

func _CampaignService_CreateCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCampaignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignServiceServer).CreateCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignService_CreateCampaign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignServiceServer).CreateCampaign(ctx, req.(*CreateCampaignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignService_GetCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCampaignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignServiceServer).GetCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignService_GetCampaign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignServiceServer).GetCampaign(ctx, req.(*GetCampaignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignService_ListCampaigns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCampaignsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignServiceServer).ListCampaigns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignService_ListCampaigns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignServiceServer).ListCampaigns(ctx, req.(*ListCampaignsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignService_UpdateCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCampaignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignServiceServer).UpdateCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignService_UpdateCampaign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignServiceServer).UpdateCampaign(ctx, req.(*UpdateCampaignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignService_DeleteCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCampaignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignServiceServer).DeleteCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignService_DeleteCampaign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignServiceServer).DeleteCampaign(ctx, req.(*DeleteCampaignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignService_LaunchCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LaunchCampaignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignServiceServer).LaunchCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignService_LaunchCampaign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignServiceServer).LaunchCampaign(ctx, req.(*LaunchCampaignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignService_PauseCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseCampaignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignServiceServer).PauseCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignService_PauseCampaign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignServiceServer).PauseCampaign(ctx, req.(*PauseCampaignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignService_CancelCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelCampaignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignServiceServer).CancelCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignService_CancelCampaign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignServiceServer).CancelCampaign(ctx, req.(*CancelCampaignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignService_ListRecipients_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRecipientsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignServiceServer).ListRecipients(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignService_ListRecipients_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignServiceServer).ListRecipients(ctx, req.(*ListRecipientsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignService_UpsertWhatsAppTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertWhatsAppTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignServiceServer).UpsertWhatsAppTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignService_UpsertWhatsAppTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignServiceServer).UpsertWhatsAppTemplate(ctx, req.(*UpsertWhatsAppTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignService_GetWhatsAppTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWhatsAppTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignServiceServer).GetWhatsAppTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignService_GetWhatsAppTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignServiceServer).GetWhatsAppTemplate(ctx, req.(*GetWhatsAppTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignService_ListWhatsAppTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWhatsAppTemplatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignServiceServer).ListWhatsAppTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignService_ListWhatsAppTemplates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignServiceServer).ListWhatsAppTemplates(ctx, req.(*ListWhatsAppTemplatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CampaignService_DeleteWhatsAppTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWhatsAppTemplateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CampaignServiceServer).DeleteWhatsAppTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CampaignService_DeleteWhatsAppTemplate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CampaignServiceServer).DeleteWhatsAppTemplate(ctx, req.(*DeleteWhatsAppTemplateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CampaignService_ServiceDesc is the grpc.ServiceDesc for CampaignService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CampaignService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "da.proto.CampaignService",
	HandlerType: (*CampaignServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCampaign",
			Handler:    _CampaignService_CreateCampaign_Handler,
		},
		{
			MethodName: "GetCampaign",
			Handler:    _CampaignService_GetCampaign_Handler,
		},
		{
			MethodName: "ListCampaigns",
			Handler:    _CampaignService_ListCampaigns_Handler,
		},
		{
			MethodName: "UpdateCampaign",
			Handler:    _CampaignService_UpdateCampaign_Handler,
		},
		{
			MethodName: "DeleteCampaign",
			Handler:    _CampaignService_DeleteCampaign_Handler,
		},
		{
			MethodName: "LaunchCampaign",
			Handler:    _CampaignService_LaunchCampaign_Handler,
		},
		{
			MethodName: "PauseCampaign",
			Handler:    _CampaignService_PauseCampaign_Handler,
		},
		{
			MethodName: "CancelCampaign",
			Handler:    _CampaignService_CancelCampaign_Handler,
		},
		{
			MethodName: "ListRecipients",
			Handler:    _CampaignService_ListRecipients_Handler,
		},
		{
			MethodName: "UpsertWhatsAppTemplate",
			Handler:    _CampaignService_UpsertWhatsAppTemplate_Handler,
		},
		{
			MethodName: "GetWhatsAppTemplate",
			Handler:    _CampaignService_GetWhatsAppTemplate_Handler,
		},
		{
			MethodName: "ListWhatsAppTemplates",
			Handler:    _CampaignService_ListWhatsAppTemplates_Handler,
		},
		{
			MethodName: "DeleteWhatsAppTemplate",
			Handler:    _CampaignService_DeleteWhatsAppTemplate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "campaigns.proto",
}
