// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.4
// source: groups_association.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GroupAssociation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	ContactId     string                 `protobuf:"bytes,3,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupAssociation) Reset() {
	*x = GroupAssociation{}
	mi := &file_groups_association_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupAssociation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupAssociation) ProtoMessage() {}

func (x *GroupAssociation) ProtoReflect() protoreflect.Message {
	mi := &file_groups_association_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupAssociation.ProtoReflect.Descriptor instead.
func (*GroupAssociation) Descriptor() ([]byte, []int) {
	return file_groups_association_proto_rawDescGZIP(), []int{0}
}

func (x *GroupAssociation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GroupAssociation) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupAssociation) GetContactId() string {
	if x != nil {
		return x.ContactId
	}
	return ""
}

type CreateGroupAssociationRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GroupAssociation *GroupAssociation      `protobuf:"bytes,1,opt,name=group_association,json=groupAssociation,proto3" json:"group_association,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateGroupAssociationRequest) Reset() {
	*x = CreateGroupAssociationRequest{}
	mi := &file_groups_association_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupAssociationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupAssociationRequest) ProtoMessage() {}

func (x *CreateGroupAssociationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_groups_association_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupAssociationRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupAssociationRequest) Descriptor() ([]byte, []int) {
	return file_groups_association_proto_rawDescGZIP(), []int{1}
}

func (x *CreateGroupAssociationRequest) GetGroupAssociation() *GroupAssociation {
	if x != nil {
		return x.GroupAssociation
	}
	return nil
}

type CreateGroupAssociationResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GroupAssociation *GroupAssociation      `protobuf:"bytes,1,opt,name=group_association,json=groupAssociation,proto3" json:"group_association,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateGroupAssociationResponse) Reset() {
	*x = CreateGroupAssociationResponse{}
	mi := &file_groups_association_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupAssociationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupAssociationResponse) ProtoMessage() {}

func (x *CreateGroupAssociationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_groups_association_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupAssociationResponse.ProtoReflect.Descriptor instead.
func (*CreateGroupAssociationResponse) Descriptor() ([]byte, []int) {
	return file_groups_association_proto_rawDescGZIP(), []int{2}
}

func (x *CreateGroupAssociationResponse) GetGroupAssociation() *GroupAssociation {
	if x != nil {
		return x.GroupAssociation
	}
	return nil
}

type ReadGroupAssociationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContactId     string                 `protobuf:"bytes,1,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadGroupAssociationRequest) Reset() {
	*x = ReadGroupAssociationRequest{}
	mi := &file_groups_association_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadGroupAssociationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadGroupAssociationRequest) ProtoMessage() {}

func (x *ReadGroupAssociationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_groups_association_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadGroupAssociationRequest.ProtoReflect.Descriptor instead.
func (*ReadGroupAssociationRequest) Descriptor() ([]byte, []int) {
	return file_groups_association_proto_rawDescGZIP(), []int{3}
}

func (x *ReadGroupAssociationRequest) GetContactId() string {
	if x != nil {
		return x.ContactId
	}
	return ""
}

type ReadGroupAssociationResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	GroupAssociations []*GroupAssociation    `protobuf:"bytes,1,rep,name=group_associations,json=groupAssociations,proto3" json:"group_associations,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReadGroupAssociationResponse) Reset() {
	*x = ReadGroupAssociationResponse{}
	mi := &file_groups_association_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadGroupAssociationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadGroupAssociationResponse) ProtoMessage() {}

func (x *ReadGroupAssociationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_groups_association_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadGroupAssociationResponse.ProtoReflect.Descriptor instead.
func (*ReadGroupAssociationResponse) Descriptor() ([]byte, []int) {
	return file_groups_association_proto_rawDescGZIP(), []int{4}
}

func (x *ReadGroupAssociationResponse) GetGroupAssociations() []*GroupAssociation {
	if x != nil {
		return x.GroupAssociations
	}
	return nil
}

type UpdateGroupAssociationRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	GroupAssociation *GroupAssociation      `protobuf:"bytes,1,opt,name=group_association,json=groupAssociation,proto3" json:"group_association,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateGroupAssociationRequest) Reset() {
	*x = UpdateGroupAssociationRequest{}
	mi := &file_groups_association_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupAssociationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupAssociationRequest) ProtoMessage() {}

func (x *UpdateGroupAssociationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_groups_association_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupAssociationRequest.ProtoReflect.Descriptor instead.
func (*UpdateGroupAssociationRequest) Descriptor() ([]byte, []int) {
	return file_groups_association_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateGroupAssociationRequest) GetGroupAssociation() *GroupAssociation {
	if x != nil {
		return x.GroupAssociation
	}
	return nil
}

type UpdateGroupAssociationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupAssociationResponse) Reset() {
	*x = UpdateGroupAssociationResponse{}
	mi := &file_groups_association_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupAssociationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupAssociationResponse) ProtoMessage() {}

func (x *UpdateGroupAssociationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_groups_association_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupAssociationResponse.ProtoReflect.Descriptor instead.
func (*UpdateGroupAssociationResponse) Descriptor() ([]byte, []int) {
	return file_groups_association_proto_rawDescGZIP(), []int{6}
}

type DeleteGroupAssociationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContactId     string                 `protobuf:"bytes,1,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	GroupId       string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGroupAssociationRequest) Reset() {
	*x = DeleteGroupAssociationRequest{}
	mi := &file_groups_association_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupAssociationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupAssociationRequest) ProtoMessage() {}

func (x *DeleteGroupAssociationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_groups_association_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupAssociationRequest.ProtoReflect.Descriptor instead.
func (*DeleteGroupAssociationRequest) Descriptor() ([]byte, []int) {
	return file_groups_association_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteGroupAssociationRequest) GetContactId() string {
	if x != nil {
		return x.ContactId
	}
	return ""
}

func (x *DeleteGroupAssociationRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type DeleteGroupAssociationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGroupAssociationResponse) Reset() {
	*x = DeleteGroupAssociationResponse{}
	mi := &file_groups_association_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupAssociationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupAssociationResponse) ProtoMessage() {}

func (x *DeleteGroupAssociationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_groups_association_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupAssociationResponse.ProtoReflect.Descriptor instead.
func (*DeleteGroupAssociationResponse) Descriptor() ([]byte, []int) {
	return file_groups_association_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteGroupAssociationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_groups_association_proto protoreflect.FileDescriptor

const file_groups_association_proto_rawDesc = "" +
	"\n" +
	"\x18groups_association.proto\x12\bda.proto\"\\\n" +
	"\x10GroupAssociation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x12\x1d\n" +
	"\n" +
	"contact_id\x18\x03 \x01(\tR\tcontactId\"h\n" +
	"\x1dCreateGroupAssociationRequest\x12G\n" +
	"\x11group_association\x18\x01 \x01(\v2\x1a.da.proto.GroupAssociationR\x10groupAssociation\"i\n" +
	"\x1eCreateGroupAssociationResponse\x12G\n" +
	"\x11group_association\x18\x01 \x01(\v2\x1a.da.proto.GroupAssociationR\x10groupAssociation\"<\n" +
	"\x1bReadGroupAssociationRequest\x12\x1d\n" +
	"\n" +
	"contact_id\x18\x01 \x01(\tR\tcontactId\"i\n" +
	"\x1cReadGroupAssociationResponse\x12I\n" +
	"\x12group_associations\x18\x01 \x03(\v2\x1a.da.proto.GroupAssociationR\x11groupAssociations\"h\n" +
	"\x1dUpdateGroupAssociationRequest\x12G\n" +
	"\x11group_association\x18\x01 \x01(\v2\x1a.da.proto.GroupAssociationR\x10groupAssociation\" \n" +
	"\x1eUpdateGroupAssociationResponse\"Y\n" +
	"\x1dDeleteGroupAssociationRequest\x12\x1d\n" +
	"\n" +
	"contact_id\x18\x01 \x01(\tR\tcontactId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\":\n" +
	"\x1eDeleteGroupAssociationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccessB\x06Z\x04./pbb\x06proto3"

var (
	file_groups_association_proto_rawDescOnce sync.Once
	file_groups_association_proto_rawDescData []byte
)

func file_groups_association_proto_rawDescGZIP() []byte {
	file_groups_association_proto_rawDescOnce.Do(func() {
		file_groups_association_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_groups_association_proto_rawDesc), len(file_groups_association_proto_rawDesc)))
	})
	return file_groups_association_proto_rawDescData
}

var file_groups_association_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_groups_association_proto_goTypes = []any{
	(*GroupAssociation)(nil),               // 0: da.proto.GroupAssociation
	(*CreateGroupAssociationRequest)(nil),  // 1: da.proto.CreateGroupAssociationRequest
	(*CreateGroupAssociationResponse)(nil), // 2: da.proto.CreateGroupAssociationResponse
	(*ReadGroupAssociationRequest)(nil),    // 3: da.proto.ReadGroupAssociationRequest
	(*ReadGroupAssociationResponse)(nil),   // 4: da.proto.ReadGroupAssociationResponse
	(*UpdateGroupAssociationRequest)(nil),  // 5: da.proto.UpdateGroupAssociationRequest
	(*UpdateGroupAssociationResponse)(nil), // 6: da.proto.UpdateGroupAssociationResponse
	(*DeleteGroupAssociationRequest)(nil),  // 7: da.proto.DeleteGroupAssociationRequest
	(*DeleteGroupAssociationResponse)(nil), // 8: da.proto.DeleteGroupAssociationResponse
}
var file_groups_association_proto_depIdxs = []int32{
	0, // 0: da.proto.CreateGroupAssociationRequest.group_association:type_name -> da.proto.GroupAssociation
	0, // 1: da.proto.CreateGroupAssociationResponse.group_association:type_name -> da.proto.GroupAssociation
	0, // 2: da.proto.ReadGroupAssociationResponse.group_associations:type_name -> da.proto.GroupAssociation
	0, // 3: da.proto.UpdateGroupAssociationRequest.group_association:type_name -> da.proto.GroupAssociation
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_groups_association_proto_init() }
func file_groups_association_proto_init() {
	if File_groups_association_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_groups_association_proto_rawDesc), len(file_groups_association_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_groups_association_proto_goTypes,
		DependencyIndexes: file_groups_association_proto_depIdxs,
		MessageInfos:      file_groups_association_proto_msgTypes,
	}.Build()
	File_groups_association_proto = out.File
	file_groups_association_proto_goTypes = nil
	file_groups_association_proto_depIdxs = nil
}
