// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.4
// source: invitation.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InvitationType represents the type of invitation
type InvitationType int32

const (
	InvitationType_INVITATION_TYPE_UNSPECIFIED   InvitationType = 0
	InvitationType_INVITATION_TYPE_NEW_USER      InvitationType = 1 // For new users to join the platform
	InvitationType_INVITATION_TYPE_EXISTING_USER InvitationType = 2 // For existing users to join another org/branch/dept/team
)

// Enum value maps for InvitationType.
var (
	InvitationType_name = map[int32]string{
		0: "INVITATION_TYPE_UNSPECIFIED",
		1: "INVITATION_TYPE_NEW_USER",
		2: "INVITATION_TYPE_EXISTING_USER",
	}
	InvitationType_value = map[string]int32{
		"INVITATION_TYPE_UNSPECIFIED":   0,
		"INVITATION_TYPE_NEW_USER":      1,
		"INVITATION_TYPE_EXISTING_USER": 2,
	}
)

func (x InvitationType) Enum() *InvitationType {
	p := new(InvitationType)
	*p = x
	return p
}

func (x InvitationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InvitationType) Descriptor() protoreflect.EnumDescriptor {
	return file_invitation_proto_enumTypes[0].Descriptor()
}

func (InvitationType) Type() protoreflect.EnumType {
	return &file_invitation_proto_enumTypes[0]
}

func (x InvitationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InvitationType.Descriptor instead.
func (InvitationType) EnumDescriptor() ([]byte, []int) {
	return file_invitation_proto_rawDescGZIP(), []int{0}
}

// InvitationStatus represents the current status of an invitation
type InvitationStatus int32

const (
	InvitationStatus_INVITATION_STATUS_UNSPECIFIED InvitationStatus = 0
	InvitationStatus_INVITATION_STATUS_PENDING     InvitationStatus = 1
	InvitationStatus_INVITATION_STATUS_ACCEPTED    InvitationStatus = 2
	InvitationStatus_INVITATION_STATUS_REJECTED    InvitationStatus = 3
	InvitationStatus_INVITATION_STATUS_EXPIRED     InvitationStatus = 4
)

// Enum value maps for InvitationStatus.
var (
	InvitationStatus_name = map[int32]string{
		0: "INVITATION_STATUS_UNSPECIFIED",
		1: "INVITATION_STATUS_PENDING",
		2: "INVITATION_STATUS_ACCEPTED",
		3: "INVITATION_STATUS_REJECTED",
		4: "INVITATION_STATUS_EXPIRED",
	}
	InvitationStatus_value = map[string]int32{
		"INVITATION_STATUS_UNSPECIFIED": 0,
		"INVITATION_STATUS_PENDING":     1,
		"INVITATION_STATUS_ACCEPTED":    2,
		"INVITATION_STATUS_REJECTED":    3,
		"INVITATION_STATUS_EXPIRED":     4,
	}
)

func (x InvitationStatus) Enum() *InvitationStatus {
	p := new(InvitationStatus)
	*p = x
	return p
}

func (x InvitationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InvitationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_invitation_proto_enumTypes[1].Descriptor()
}

func (InvitationStatus) Type() protoreflect.EnumType {
	return &file_invitation_proto_enumTypes[1]
}

func (x InvitationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InvitationStatus.Descriptor instead.
func (InvitationStatus) EnumDescriptor() ([]byte, []int) {
	return file_invitation_proto_rawDescGZIP(), []int{1}
}

// Invitation represents a user invitation in the system
type Invitation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email          string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	InvitedBy      string                 `protobuf:"bytes,3,opt,name=invited_by,json=invitedBy,proto3" json:"invited_by,omitempty"` // ID of the user who sent the invitation
	Type           InvitationType         `protobuf:"varint,4,opt,name=type,proto3,enum=da.proto.InvitationType" json:"type,omitempty"`
	Status         InvitationStatus       `protobuf:"varint,5,opt,name=status,proto3,enum=da.proto.InvitationStatus" json:"status,omitempty"`
	OrganisationId string                 `protobuf:"bytes,6,opt,name=organisation_id,json=organisationId,proto3" json:"organisation_id,omitempty"`
	BranchId       string                 `protobuf:"bytes,7,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"`             // Optional
	DepartmentId   string                 `protobuf:"bytes,8,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"` // Optional
	TeamId         string                 `protobuf:"bytes,9,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`                   // Optional
	UserId         string                 `protobuf:"bytes,10,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                  // Only set for INVITATION_TYPE_EXISTING_USER
	RoleIds        []string               `protobuf:"bytes,11,rep,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ExpiresAt      *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Invitation) Reset() {
	*x = Invitation{}
	mi := &file_invitation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Invitation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Invitation) ProtoMessage() {}

func (x *Invitation) ProtoReflect() protoreflect.Message {
	mi := &file_invitation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Invitation.ProtoReflect.Descriptor instead.
func (*Invitation) Descriptor() ([]byte, []int) {
	return file_invitation_proto_rawDescGZIP(), []int{0}
}

func (x *Invitation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Invitation) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Invitation) GetInvitedBy() string {
	if x != nil {
		return x.InvitedBy
	}
	return ""
}

func (x *Invitation) GetType() InvitationType {
	if x != nil {
		return x.Type
	}
	return InvitationType_INVITATION_TYPE_UNSPECIFIED
}

func (x *Invitation) GetStatus() InvitationStatus {
	if x != nil {
		return x.Status
	}
	return InvitationStatus_INVITATION_STATUS_UNSPECIFIED
}

func (x *Invitation) GetOrganisationId() string {
	if x != nil {
		return x.OrganisationId
	}
	return ""
}

func (x *Invitation) GetBranchId() string {
	if x != nil {
		return x.BranchId
	}
	return ""
}

func (x *Invitation) GetDepartmentId() string {
	if x != nil {
		return x.DepartmentId
	}
	return ""
}

func (x *Invitation) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *Invitation) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Invitation) GetRoleIds() []string {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

func (x *Invitation) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Invitation) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Invitation) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// CreateInviteRequest represents a request to create a new invitation
type CreateInviteRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Email     string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	InvitedBy string                 `protobuf:"bytes,2,opt,name=invited_by,json=invitedBy,proto3" json:"invited_by,omitempty"`
	Type      InvitationType         `protobuf:"varint,3,opt,name=type,proto3,enum=da.proto.InvitationType" json:"type,omitempty"`
	// Target organization details
	OrganisationId string `protobuf:"bytes,4,opt,name=organisation_id,json=organisationId,proto3" json:"organisation_id,omitempty"`
	BranchId       string `protobuf:"bytes,5,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"`             // Optional
	DepartmentId   string `protobuf:"bytes,6,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"` // Optional
	TeamId         string `protobuf:"bytes,7,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`                   // Optional
	// For existing users
	UserId string `protobuf:"bytes,8,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // Only set for INVITATION_TYPE_EXISTING_USER
	// Assigned roles
	RoleIds []string `protobuf:"bytes,9,rep,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	// Expiration in hours (default 72 hours)
	ExpirationHours int32 `protobuf:"varint,10,opt,name=expiration_hours,json=expirationHours,proto3" json:"expiration_hours,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateInviteRequest) Reset() {
	*x = CreateInviteRequest{}
	mi := &file_invitation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInviteRequest) ProtoMessage() {}

func (x *CreateInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invitation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInviteRequest.ProtoReflect.Descriptor instead.
func (*CreateInviteRequest) Descriptor() ([]byte, []int) {
	return file_invitation_proto_rawDescGZIP(), []int{1}
}

func (x *CreateInviteRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateInviteRequest) GetInvitedBy() string {
	if x != nil {
		return x.InvitedBy
	}
	return ""
}

func (x *CreateInviteRequest) GetType() InvitationType {
	if x != nil {
		return x.Type
	}
	return InvitationType_INVITATION_TYPE_UNSPECIFIED
}

func (x *CreateInviteRequest) GetOrganisationId() string {
	if x != nil {
		return x.OrganisationId
	}
	return ""
}

func (x *CreateInviteRequest) GetBranchId() string {
	if x != nil {
		return x.BranchId
	}
	return ""
}

func (x *CreateInviteRequest) GetDepartmentId() string {
	if x != nil {
		return x.DepartmentId
	}
	return ""
}

func (x *CreateInviteRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *CreateInviteRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateInviteRequest) GetRoleIds() []string {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

func (x *CreateInviteRequest) GetExpirationHours() int32 {
	if x != nil {
		return x.ExpirationHours
	}
	return 0
}

// GetInviteRequest represents a request to get an invitation by ID
type GetInviteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInviteRequest) Reset() {
	*x = GetInviteRequest{}
	mi := &file_invitation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInviteRequest) ProtoMessage() {}

func (x *GetInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invitation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInviteRequest.ProtoReflect.Descriptor instead.
func (*GetInviteRequest) Descriptor() ([]byte, []int) {
	return file_invitation_proto_rawDescGZIP(), []int{2}
}

func (x *GetInviteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ListInvitationsRequest represents a request to list invitations with filters
type ListInvitationsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Email          string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	InvitedBy      string                 `protobuf:"bytes,2,opt,name=invited_by,json=invitedBy,proto3" json:"invited_by,omitempty"`
	Type           InvitationType         `protobuf:"varint,3,opt,name=type,proto3,enum=da.proto.InvitationType" json:"type,omitempty"`
	Status         InvitationStatus       `protobuf:"varint,4,opt,name=status,proto3,enum=da.proto.InvitationStatus" json:"status,omitempty"`
	OrganisationId string                 `protobuf:"bytes,5,opt,name=organisation_id,json=organisationId,proto3" json:"organisation_id,omitempty"`
	BranchId       string                 `protobuf:"bytes,6,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"`
	DepartmentId   string                 `protobuf:"bytes,7,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	TeamId         string                 `protobuf:"bytes,8,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	UserId         string                 `protobuf:"bytes,9,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PageSize       int32                  `protobuf:"varint,10,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken      string                 `protobuf:"bytes,11,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListInvitationsRequest) Reset() {
	*x = ListInvitationsRequest{}
	mi := &file_invitation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInvitationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInvitationsRequest) ProtoMessage() {}

func (x *ListInvitationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invitation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInvitationsRequest.ProtoReflect.Descriptor instead.
func (*ListInvitationsRequest) Descriptor() ([]byte, []int) {
	return file_invitation_proto_rawDescGZIP(), []int{3}
}

func (x *ListInvitationsRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ListInvitationsRequest) GetInvitedBy() string {
	if x != nil {
		return x.InvitedBy
	}
	return ""
}

func (x *ListInvitationsRequest) GetType() InvitationType {
	if x != nil {
		return x.Type
	}
	return InvitationType_INVITATION_TYPE_UNSPECIFIED
}

func (x *ListInvitationsRequest) GetStatus() InvitationStatus {
	if x != nil {
		return x.Status
	}
	return InvitationStatus_INVITATION_STATUS_UNSPECIFIED
}

func (x *ListInvitationsRequest) GetOrganisationId() string {
	if x != nil {
		return x.OrganisationId
	}
	return ""
}

func (x *ListInvitationsRequest) GetBranchId() string {
	if x != nil {
		return x.BranchId
	}
	return ""
}

func (x *ListInvitationsRequest) GetDepartmentId() string {
	if x != nil {
		return x.DepartmentId
	}
	return ""
}

func (x *ListInvitationsRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *ListInvitationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListInvitationsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListInvitationsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

// ListInvitationsResponse represents a response containing a list of invitations
type ListInvitationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Invitations   []*Invitation          `protobuf:"bytes,1,rep,name=invitations,proto3" json:"invitations,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInvitationsResponse) Reset() {
	*x = ListInvitationsResponse{}
	mi := &file_invitation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInvitationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInvitationsResponse) ProtoMessage() {}

func (x *ListInvitationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_invitation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInvitationsResponse.ProtoReflect.Descriptor instead.
func (*ListInvitationsResponse) Descriptor() ([]byte, []int) {
	return file_invitation_proto_rawDescGZIP(), []int{4}
}

func (x *ListInvitationsResponse) GetInvitations() []*Invitation {
	if x != nil {
		return x.Invitations
	}
	return nil
}

func (x *ListInvitationsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListInvitationsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// UpdateInviteRequest represents a request to update an invitation
type UpdateInviteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email          string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Type           InvitationType         `protobuf:"varint,3,opt,name=type,proto3,enum=da.proto.InvitationType" json:"type,omitempty"`
	Status         InvitationStatus       `protobuf:"varint,4,opt,name=status,proto3,enum=da.proto.InvitationStatus" json:"status,omitempty"`
	OrganisationId string                 `protobuf:"bytes,5,opt,name=organisation_id,json=organisationId,proto3" json:"organisation_id,omitempty"`
	BranchId       string                 `protobuf:"bytes,6,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"`
	DepartmentId   string                 `protobuf:"bytes,7,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	TeamId         string                 `protobuf:"bytes,8,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	UserId         string                 `protobuf:"bytes,9,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RoleIds        []string               `protobuf:"bytes,10,rep,name=role_ids,json=roleIds,proto3" json:"role_ids,omitempty"`
	ExpiresAt      *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateInviteRequest) Reset() {
	*x = UpdateInviteRequest{}
	mi := &file_invitation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInviteRequest) ProtoMessage() {}

func (x *UpdateInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invitation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInviteRequest.ProtoReflect.Descriptor instead.
func (*UpdateInviteRequest) Descriptor() ([]byte, []int) {
	return file_invitation_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateInviteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateInviteRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateInviteRequest) GetType() InvitationType {
	if x != nil {
		return x.Type
	}
	return InvitationType_INVITATION_TYPE_UNSPECIFIED
}

func (x *UpdateInviteRequest) GetStatus() InvitationStatus {
	if x != nil {
		return x.Status
	}
	return InvitationStatus_INVITATION_STATUS_UNSPECIFIED
}

func (x *UpdateInviteRequest) GetOrganisationId() string {
	if x != nil {
		return x.OrganisationId
	}
	return ""
}

func (x *UpdateInviteRequest) GetBranchId() string {
	if x != nil {
		return x.BranchId
	}
	return ""
}

func (x *UpdateInviteRequest) GetDepartmentId() string {
	if x != nil {
		return x.DepartmentId
	}
	return ""
}

func (x *UpdateInviteRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *UpdateInviteRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UpdateInviteRequest) GetRoleIds() []string {
	if x != nil {
		return x.RoleIds
	}
	return nil
}

func (x *UpdateInviteRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// DeleteInviteRequest represents a request to delete an invitation
type DeleteInviteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteInviteRequest) Reset() {
	*x = DeleteInviteRequest{}
	mi := &file_invitation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInviteRequest) ProtoMessage() {}

func (x *DeleteInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invitation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInviteRequest.ProtoReflect.Descriptor instead.
func (*DeleteInviteRequest) Descriptor() ([]byte, []int) {
	return file_invitation_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteInviteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// AcceptInviteRequest represents a request to accept an invitation
type AcceptInviteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrganisationId string                 `protobuf:"bytes,3,opt,name=organisation_id,json=organisationId,proto3" json:"organisation_id,omitempty"` // Organisation ID to join
	FirstName      string                 `protobuf:"bytes,4,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`                // Optional first name for new users
	LastName       string                 `protobuf:"bytes,5,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`                   // Optional last name for new users
	PhoneNumber    string                 `protobuf:"bytes,6,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`          // Optional phone number for new users
	Password       string                 `protobuf:"bytes,7,opt,name=password,proto3" json:"password,omitempty"`                                   // Optional password for new users
	Username       string                 `protobuf:"bytes,8,opt,name=username,proto3" json:"username,omitempty"`                                   // Optional username for new users
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AcceptInviteRequest) Reset() {
	*x = AcceptInviteRequest{}
	mi := &file_invitation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptInviteRequest) ProtoMessage() {}

func (x *AcceptInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invitation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptInviteRequest.ProtoReflect.Descriptor instead.
func (*AcceptInviteRequest) Descriptor() ([]byte, []int) {
	return file_invitation_proto_rawDescGZIP(), []int{7}
}

func (x *AcceptInviteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AcceptInviteRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AcceptInviteRequest) GetOrganisationId() string {
	if x != nil {
		return x.OrganisationId
	}
	return ""
}

func (x *AcceptInviteRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *AcceptInviteRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *AcceptInviteRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *AcceptInviteRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AcceptInviteRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// RejectInviteRequest represents a request to reject an invitation
type RejectInviteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectInviteRequest) Reset() {
	*x = RejectInviteRequest{}
	mi := &file_invitation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectInviteRequest) ProtoMessage() {}

func (x *RejectInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invitation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectInviteRequest.ProtoReflect.Descriptor instead.
func (*RejectInviteRequest) Descriptor() ([]byte, []int) {
	return file_invitation_proto_rawDescGZIP(), []int{8}
}

func (x *RejectInviteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// CancelInviteRequest represents a request to cancel an invitation
type CancelInviteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelInviteRequest) Reset() {
	*x = CancelInviteRequest{}
	mi := &file_invitation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelInviteRequest) ProtoMessage() {}

func (x *CancelInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invitation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelInviteRequest.ProtoReflect.Descriptor instead.
func (*CancelInviteRequest) Descriptor() ([]byte, []int) {
	return file_invitation_proto_rawDescGZIP(), []int{9}
}

func (x *CancelInviteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_invitation_proto protoreflect.FileDescriptor

const file_invitation_proto_rawDesc = "" +
	"\n" +
	"\x10invitation.proto\x12\bda.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x9c\x04\n" +
	"\n" +
	"Invitation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"invited_by\x18\x03 \x01(\tR\tinvitedBy\x12,\n" +
	"\x04type\x18\x04 \x01(\x0e2\x18.da.proto.InvitationTypeR\x04type\x122\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1a.da.proto.InvitationStatusR\x06status\x12'\n" +
	"\x0forganisation_id\x18\x06 \x01(\tR\x0eorganisationId\x12\x1b\n" +
	"\tbranch_id\x18\a \x01(\tR\bbranchId\x12#\n" +
	"\rdepartment_id\x18\b \x01(\tR\fdepartmentId\x12\x17\n" +
	"\ateam_id\x18\t \x01(\tR\x06teamId\x12\x17\n" +
	"\auser_id\x18\n" +
	" \x01(\tR\x06userId\x12\x19\n" +
	"\brole_ids\x18\v \x03(\tR\aroleIds\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"expires_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\xdb\x02\n" +
	"\x13CreateInviteRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"invited_by\x18\x02 \x01(\tR\tinvitedBy\x12,\n" +
	"\x04type\x18\x03 \x01(\x0e2\x18.da.proto.InvitationTypeR\x04type\x12'\n" +
	"\x0forganisation_id\x18\x04 \x01(\tR\x0eorganisationId\x12\x1b\n" +
	"\tbranch_id\x18\x05 \x01(\tR\bbranchId\x12#\n" +
	"\rdepartment_id\x18\x06 \x01(\tR\fdepartmentId\x12\x17\n" +
	"\ateam_id\x18\a \x01(\tR\x06teamId\x12\x17\n" +
	"\auser_id\x18\b \x01(\tR\x06userId\x12\x19\n" +
	"\brole_ids\x18\t \x03(\tR\aroleIds\x12)\n" +
	"\x10expiration_hours\x18\n" +
	" \x01(\x05R\x0fexpirationHours\"\"\n" +
	"\x10GetInviteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x88\x03\n" +
	"\x16ListInvitationsRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"invited_by\x18\x02 \x01(\tR\tinvitedBy\x12,\n" +
	"\x04type\x18\x03 \x01(\x0e2\x18.da.proto.InvitationTypeR\x04type\x122\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1a.da.proto.InvitationStatusR\x06status\x12'\n" +
	"\x0forganisation_id\x18\x05 \x01(\tR\x0eorganisationId\x12\x1b\n" +
	"\tbranch_id\x18\x06 \x01(\tR\bbranchId\x12#\n" +
	"\rdepartment_id\x18\a \x01(\tR\fdepartmentId\x12\x17\n" +
	"\ateam_id\x18\b \x01(\tR\x06teamId\x12\x17\n" +
	"\auser_id\x18\t \x01(\tR\x06userId\x12\x1b\n" +
	"\tpage_size\x18\n" +
	" \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\v \x01(\tR\tpageToken\"\x9a\x01\n" +
	"\x17ListInvitationsResponse\x126\n" +
	"\vinvitations\x18\x01 \x03(\v2\x14.da.proto.InvitationR\vinvitations\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"\x90\x03\n" +
	"\x13UpdateInviteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12,\n" +
	"\x04type\x18\x03 \x01(\x0e2\x18.da.proto.InvitationTypeR\x04type\x122\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1a.da.proto.InvitationStatusR\x06status\x12'\n" +
	"\x0forganisation_id\x18\x05 \x01(\tR\x0eorganisationId\x12\x1b\n" +
	"\tbranch_id\x18\x06 \x01(\tR\bbranchId\x12#\n" +
	"\rdepartment_id\x18\a \x01(\tR\fdepartmentId\x12\x17\n" +
	"\ateam_id\x18\b \x01(\tR\x06teamId\x12\x17\n" +
	"\auser_id\x18\t \x01(\tR\x06userId\x12\x19\n" +
	"\brole_ids\x18\n" +
	" \x03(\tR\aroleIds\x129\n" +
	"\n" +
	"expires_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"%\n" +
	"\x13DeleteInviteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xfe\x01\n" +
	"\x13AcceptInviteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12'\n" +
	"\x0forganisation_id\x18\x03 \x01(\tR\x0eorganisationId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x04 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x05 \x01(\tR\blastName\x12!\n" +
	"\fphone_number\x18\x06 \x01(\tR\vphoneNumber\x12\x1a\n" +
	"\bpassword\x18\a \x01(\tR\bpassword\x12\x1a\n" +
	"\busername\x18\b \x01(\tR\busername\"%\n" +
	"\x13RejectInviteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"%\n" +
	"\x13CancelInviteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id*r\n" +
	"\x0eInvitationType\x12\x1f\n" +
	"\x1bINVITATION_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18INVITATION_TYPE_NEW_USER\x10\x01\x12!\n" +
	"\x1dINVITATION_TYPE_EXISTING_USER\x10\x02*\xb3\x01\n" +
	"\x10InvitationStatus\x12!\n" +
	"\x1dINVITATION_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19INVITATION_STATUS_PENDING\x10\x01\x12\x1e\n" +
	"\x1aINVITATION_STATUS_ACCEPTED\x10\x02\x12\x1e\n" +
	"\x1aINVITATION_STATUS_REJECTED\x10\x03\x12\x1d\n" +
	"\x19INVITATION_STATUS_EXPIRED\x10\x042\xe6\x04\n" +
	"\x11InvitationService\x12G\n" +
	"\x10CreateInvitation\x12\x1d.da.proto.CreateInviteRequest\x1a\x14.da.proto.Invitation\x12A\n" +
	"\rGetInvitation\x12\x1a.da.proto.GetInviteRequest\x1a\x14.da.proto.Invitation\x12V\n" +
	"\x0fListInvitations\x12 .da.proto.ListInvitationsRequest\x1a!.da.proto.ListInvitationsResponse\x12G\n" +
	"\x10UpdateInvitation\x12\x1d.da.proto.UpdateInviteRequest\x1a\x14.da.proto.Invitation\x12I\n" +
	"\x10DeleteInvitation\x12\x1d.da.proto.DeleteInviteRequest\x1a\x16.google.protobuf.Empty\x12G\n" +
	"\x10AcceptInvitation\x12\x1d.da.proto.AcceptInviteRequest\x1a\x14.da.proto.Invitation\x12G\n" +
	"\x10RejectInvitation\x12\x1d.da.proto.RejectInviteRequest\x1a\x14.da.proto.Invitation\x12G\n" +
	"\x10CancelInvitation\x12\x1d.da.proto.CancelInviteRequest\x1a\x14.da.proto.InvitationB\x06Z\x04./pbb\x06proto3"

var (
	file_invitation_proto_rawDescOnce sync.Once
	file_invitation_proto_rawDescData []byte
)

func file_invitation_proto_rawDescGZIP() []byte {
	file_invitation_proto_rawDescOnce.Do(func() {
		file_invitation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_invitation_proto_rawDesc), len(file_invitation_proto_rawDesc)))
	})
	return file_invitation_proto_rawDescData
}

var file_invitation_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_invitation_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_invitation_proto_goTypes = []any{
	(InvitationType)(0),             // 0: da.proto.InvitationType
	(InvitationStatus)(0),           // 1: da.proto.InvitationStatus
	(*Invitation)(nil),              // 2: da.proto.Invitation
	(*CreateInviteRequest)(nil),     // 3: da.proto.CreateInviteRequest
	(*GetInviteRequest)(nil),        // 4: da.proto.GetInviteRequest
	(*ListInvitationsRequest)(nil),  // 5: da.proto.ListInvitationsRequest
	(*ListInvitationsResponse)(nil), // 6: da.proto.ListInvitationsResponse
	(*UpdateInviteRequest)(nil),     // 7: da.proto.UpdateInviteRequest
	(*DeleteInviteRequest)(nil),     // 8: da.proto.DeleteInviteRequest
	(*AcceptInviteRequest)(nil),     // 9: da.proto.AcceptInviteRequest
	(*RejectInviteRequest)(nil),     // 10: da.proto.RejectInviteRequest
	(*CancelInviteRequest)(nil),     // 11: da.proto.CancelInviteRequest
	(*timestamppb.Timestamp)(nil),   // 12: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),           // 13: google.protobuf.Empty
}
var file_invitation_proto_depIdxs = []int32{
	0,  // 0: da.proto.Invitation.type:type_name -> da.proto.InvitationType
	1,  // 1: da.proto.Invitation.status:type_name -> da.proto.InvitationStatus
	12, // 2: da.proto.Invitation.created_at:type_name -> google.protobuf.Timestamp
	12, // 3: da.proto.Invitation.updated_at:type_name -> google.protobuf.Timestamp
	12, // 4: da.proto.Invitation.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 5: da.proto.CreateInviteRequest.type:type_name -> da.proto.InvitationType
	0,  // 6: da.proto.ListInvitationsRequest.type:type_name -> da.proto.InvitationType
	1,  // 7: da.proto.ListInvitationsRequest.status:type_name -> da.proto.InvitationStatus
	2,  // 8: da.proto.ListInvitationsResponse.invitations:type_name -> da.proto.Invitation
	0,  // 9: da.proto.UpdateInviteRequest.type:type_name -> da.proto.InvitationType
	1,  // 10: da.proto.UpdateInviteRequest.status:type_name -> da.proto.InvitationStatus
	12, // 11: da.proto.UpdateInviteRequest.expires_at:type_name -> google.protobuf.Timestamp
	3,  // 12: da.proto.InvitationService.CreateInvitation:input_type -> da.proto.CreateInviteRequest
	4,  // 13: da.proto.InvitationService.GetInvitation:input_type -> da.proto.GetInviteRequest
	5,  // 14: da.proto.InvitationService.ListInvitations:input_type -> da.proto.ListInvitationsRequest
	7,  // 15: da.proto.InvitationService.UpdateInvitation:input_type -> da.proto.UpdateInviteRequest
	8,  // 16: da.proto.InvitationService.DeleteInvitation:input_type -> da.proto.DeleteInviteRequest
	9,  // 17: da.proto.InvitationService.AcceptInvitation:input_type -> da.proto.AcceptInviteRequest
	10, // 18: da.proto.InvitationService.RejectInvitation:input_type -> da.proto.RejectInviteRequest
	11, // 19: da.proto.InvitationService.CancelInvitation:input_type -> da.proto.CancelInviteRequest
	2,  // 20: da.proto.InvitationService.CreateInvitation:output_type -> da.proto.Invitation
	2,  // 21: da.proto.InvitationService.GetInvitation:output_type -> da.proto.Invitation
	6,  // 22: da.proto.InvitationService.ListInvitations:output_type -> da.proto.ListInvitationsResponse
	2,  // 23: da.proto.InvitationService.UpdateInvitation:output_type -> da.proto.Invitation
	13, // 24: da.proto.InvitationService.DeleteInvitation:output_type -> google.protobuf.Empty
	2,  // 25: da.proto.InvitationService.AcceptInvitation:output_type -> da.proto.Invitation
	2,  // 26: da.proto.InvitationService.RejectInvitation:output_type -> da.proto.Invitation
	2,  // 27: da.proto.InvitationService.CancelInvitation:output_type -> da.proto.Invitation
	20, // [20:28] is the sub-list for method output_type
	12, // [12:20] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_invitation_proto_init() }
func file_invitation_proto_init() {
	if File_invitation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_invitation_proto_rawDesc), len(file_invitation_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_invitation_proto_goTypes,
		DependencyIndexes: file_invitation_proto_depIdxs,
		EnumInfos:         file_invitation_proto_enumTypes,
		MessageInfos:      file_invitation_proto_msgTypes,
	}.Build()
	File_invitation_proto = out.File
	file_invitation_proto_goTypes = nil
	file_invitation_proto_depIdxs = nil
}
