// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.4
// source: rag_agents.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RAGAgentService_AskQuestion_FullMethodName = "/da.proto.RAGAgentService/AskQuestion"
)

// RAGAgentServiceClient is the client API for RAGAgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RAGAgentServiceClient interface {
	AskQuestion(ctx context.Context, in *AskQuestionRequest, opts ...grpc.CallOption) (*AskQuestionResponse, error)
}

type rAGAgentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRAGAgentServiceClient(cc grpc.ClientConnInterface) RAGAgentServiceClient {
	return &rAGAgentServiceClient{cc}
}

func (c *rAGAgentServiceClient) AskQuestion(ctx context.Context, in *AskQuestionRequest, opts ...grpc.CallOption) (*AskQuestionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AskQuestionResponse)
	err := c.cc.Invoke(ctx, RAGAgentService_AskQuestion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RAGAgentServiceServer is the server API for RAGAgentService service.
// All implementations must embed UnimplementedRAGAgentServiceServer
// for forward compatibility.
type RAGAgentServiceServer interface {
	AskQuestion(context.Context, *AskQuestionRequest) (*AskQuestionResponse, error)
	mustEmbedUnimplementedRAGAgentServiceServer()
}

// UnimplementedRAGAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRAGAgentServiceServer struct{}

func (UnimplementedRAGAgentServiceServer) AskQuestion(context.Context, *AskQuestionRequest) (*AskQuestionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AskQuestion not implemented")
}
func (UnimplementedRAGAgentServiceServer) mustEmbedUnimplementedRAGAgentServiceServer() {}
func (UnimplementedRAGAgentServiceServer) testEmbeddedByValue()                         {}

// UnsafeRAGAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RAGAgentServiceServer will
// result in compilation errors.
type UnsafeRAGAgentServiceServer interface {
	mustEmbedUnimplementedRAGAgentServiceServer()
}

func RegisterRAGAgentServiceServer(s grpc.ServiceRegistrar, srv RAGAgentServiceServer) {
	// If the following call pancis, it indicates UnimplementedRAGAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RAGAgentService_ServiceDesc, srv)
}

func _RAGAgentService_AskQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AskQuestionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RAGAgentServiceServer).AskQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RAGAgentService_AskQuestion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RAGAgentServiceServer).AskQuestion(ctx, req.(*AskQuestionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RAGAgentService_ServiceDesc is the grpc.ServiceDesc for RAGAgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RAGAgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "da.proto.RAGAgentService",
	HandlerType: (*RAGAgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AskQuestion",
			Handler:    _RAGAgentService_AskQuestion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rag_agents.proto",
}
