// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.4
// source: status_code.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusCode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusCode) Reset() {
	*x = StatusCode{}
	mi := &file_status_code_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusCode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusCode) ProtoMessage() {}

func (x *StatusCode) ProtoReflect() protoreflect.Message {
	mi := &file_status_code_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusCode.ProtoReflect.Descriptor instead.
func (*StatusCode) Descriptor() ([]byte, []int) {
	return file_status_code_proto_rawDescGZIP(), []int{0}
}

func (x *StatusCode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StatusCode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StatusCode) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateStatusCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    *StatusCode            `protobuf:"bytes,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStatusCodeRequest) Reset() {
	*x = CreateStatusCodeRequest{}
	mi := &file_status_code_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStatusCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStatusCodeRequest) ProtoMessage() {}

func (x *CreateStatusCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_status_code_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStatusCodeRequest.ProtoReflect.Descriptor instead.
func (*CreateStatusCodeRequest) Descriptor() ([]byte, []int) {
	return file_status_code_proto_rawDescGZIP(), []int{1}
}

func (x *CreateStatusCodeRequest) GetStatusCode() *StatusCode {
	if x != nil {
		return x.StatusCode
	}
	return nil
}

type CreateStatusCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    *StatusCode            `protobuf:"bytes,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStatusCodeResponse) Reset() {
	*x = CreateStatusCodeResponse{}
	mi := &file_status_code_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStatusCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStatusCodeResponse) ProtoMessage() {}

func (x *CreateStatusCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_status_code_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStatusCodeResponse.ProtoReflect.Descriptor instead.
func (*CreateStatusCodeResponse) Descriptor() ([]byte, []int) {
	return file_status_code_proto_rawDescGZIP(), []int{2}
}

func (x *CreateStatusCodeResponse) GetStatusCode() *StatusCode {
	if x != nil {
		return x.StatusCode
	}
	return nil
}

type ReadStatusCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadStatusCodeRequest) Reset() {
	*x = ReadStatusCodeRequest{}
	mi := &file_status_code_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadStatusCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadStatusCodeRequest) ProtoMessage() {}

func (x *ReadStatusCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_status_code_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadStatusCodeRequest.ProtoReflect.Descriptor instead.
func (*ReadStatusCodeRequest) Descriptor() ([]byte, []int) {
	return file_status_code_proto_rawDescGZIP(), []int{3}
}

func (x *ReadStatusCodeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ReadStatusCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    []*StatusCode          `protobuf:"bytes,1,rep,name=statusCode,proto3" json:"statusCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadStatusCodeResponse) Reset() {
	*x = ReadStatusCodeResponse{}
	mi := &file_status_code_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadStatusCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadStatusCodeResponse) ProtoMessage() {}

func (x *ReadStatusCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_status_code_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadStatusCodeResponse.ProtoReflect.Descriptor instead.
func (*ReadStatusCodeResponse) Descriptor() ([]byte, []int) {
	return file_status_code_proto_rawDescGZIP(), []int{4}
}

func (x *ReadStatusCodeResponse) GetStatusCode() []*StatusCode {
	if x != nil {
		return x.StatusCode
	}
	return nil
}

type ReadStatusCodesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganisationId string                 `protobuf:"bytes,1,opt,name=organisation_id,json=organisationId,proto3" json:"organisation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReadStatusCodesRequest) Reset() {
	*x = ReadStatusCodesRequest{}
	mi := &file_status_code_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadStatusCodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadStatusCodesRequest) ProtoMessage() {}

func (x *ReadStatusCodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_status_code_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadStatusCodesRequest.ProtoReflect.Descriptor instead.
func (*ReadStatusCodesRequest) Descriptor() ([]byte, []int) {
	return file_status_code_proto_rawDescGZIP(), []int{5}
}

func (x *ReadStatusCodesRequest) GetOrganisationId() string {
	if x != nil {
		return x.OrganisationId
	}
	return ""
}

type ReadStatusCodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCodes   []*StatusCode          `protobuf:"bytes,1,rep,name=statusCodes,proto3" json:"statusCodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadStatusCodesResponse) Reset() {
	*x = ReadStatusCodesResponse{}
	mi := &file_status_code_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadStatusCodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadStatusCodesResponse) ProtoMessage() {}

func (x *ReadStatusCodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_status_code_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadStatusCodesResponse.ProtoReflect.Descriptor instead.
func (*ReadStatusCodesResponse) Descriptor() ([]byte, []int) {
	return file_status_code_proto_rawDescGZIP(), []int{6}
}

func (x *ReadStatusCodesResponse) GetStatusCodes() []*StatusCode {
	if x != nil {
		return x.StatusCodes
	}
	return nil
}

type UpdateStatusCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    *StatusCode            `protobuf:"bytes,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusCodeRequest) Reset() {
	*x = UpdateStatusCodeRequest{}
	mi := &file_status_code_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusCodeRequest) ProtoMessage() {}

func (x *UpdateStatusCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_status_code_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusCodeRequest.ProtoReflect.Descriptor instead.
func (*UpdateStatusCodeRequest) Descriptor() ([]byte, []int) {
	return file_status_code_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateStatusCodeRequest) GetStatusCode() *StatusCode {
	if x != nil {
		return x.StatusCode
	}
	return nil
}

type UpdateStatusCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    *StatusCode            `protobuf:"bytes,1,opt,name=statusCode,proto3" json:"statusCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusCodeResponse) Reset() {
	*x = UpdateStatusCodeResponse{}
	mi := &file_status_code_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusCodeResponse) ProtoMessage() {}

func (x *UpdateStatusCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_status_code_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusCodeResponse.ProtoReflect.Descriptor instead.
func (*UpdateStatusCodeResponse) Descriptor() ([]byte, []int) {
	return file_status_code_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateStatusCodeResponse) GetStatusCode() *StatusCode {
	if x != nil {
		return x.StatusCode
	}
	return nil
}

type DeleteStatusCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStatusCodeRequest) Reset() {
	*x = DeleteStatusCodeRequest{}
	mi := &file_status_code_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStatusCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStatusCodeRequest) ProtoMessage() {}

func (x *DeleteStatusCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_status_code_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStatusCodeRequest.ProtoReflect.Descriptor instead.
func (*DeleteStatusCodeRequest) Descriptor() ([]byte, []int) {
	return file_status_code_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteStatusCodeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteStatusCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStatusCodeResponse) Reset() {
	*x = DeleteStatusCodeResponse{}
	mi := &file_status_code_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStatusCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStatusCodeResponse) ProtoMessage() {}

func (x *DeleteStatusCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_status_code_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStatusCodeResponse.ProtoReflect.Descriptor instead.
func (*DeleteStatusCodeResponse) Descriptor() ([]byte, []int) {
	return file_status_code_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteStatusCodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_status_code_proto protoreflect.FileDescriptor

const file_status_code_proto_rawDesc = "" +
	"\n" +
	"\x11status_code.proto\x12\bda.proto\"R\n" +
	"\n" +
	"StatusCode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"O\n" +
	"\x17CreateStatusCodeRequest\x124\n" +
	"\n" +
	"statusCode\x18\x01 \x01(\v2\x14.da.proto.StatusCodeR\n" +
	"statusCode\"P\n" +
	"\x18CreateStatusCodeResponse\x124\n" +
	"\n" +
	"statusCode\x18\x01 \x01(\v2\x14.da.proto.StatusCodeR\n" +
	"statusCode\"'\n" +
	"\x15ReadStatusCodeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"N\n" +
	"\x16ReadStatusCodeResponse\x124\n" +
	"\n" +
	"statusCode\x18\x01 \x03(\v2\x14.da.proto.StatusCodeR\n" +
	"statusCode\"A\n" +
	"\x16ReadStatusCodesRequest\x12'\n" +
	"\x0forganisation_id\x18\x01 \x01(\tR\x0eorganisationId\"Q\n" +
	"\x17ReadStatusCodesResponse\x126\n" +
	"\vstatusCodes\x18\x01 \x03(\v2\x14.da.proto.StatusCodeR\vstatusCodes\"O\n" +
	"\x17UpdateStatusCodeRequest\x124\n" +
	"\n" +
	"statusCode\x18\x01 \x01(\v2\x14.da.proto.StatusCodeR\n" +
	"statusCode\"P\n" +
	"\x18UpdateStatusCodeResponse\x124\n" +
	"\n" +
	"statusCode\x18\x01 \x01(\v2\x14.da.proto.StatusCodeR\n" +
	"statusCode\")\n" +
	"\x17DeleteStatusCodeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"4\n" +
	"\x18DeleteStatusCodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xd1\x03\n" +
	"\x11StatusCodeService\x12Y\n" +
	"\x10CreateStatusCode\x12!.da.proto.CreateStatusCodeRequest\x1a\".da.proto.CreateStatusCodeResponse\x12S\n" +
	"\x0eReadStatusCode\x12\x1f.da.proto.ReadStatusCodeRequest\x1a .da.proto.ReadStatusCodeResponse\x12V\n" +
	"\x0fReadStatusCodes\x12 .da.proto.ReadStatusCodesRequest\x1a!.da.proto.ReadStatusCodesResponse\x12Y\n" +
	"\x10UpdateStatusCode\x12!.da.proto.UpdateStatusCodeRequest\x1a\".da.proto.UpdateStatusCodeResponse\x12Y\n" +
	"\x10DeleteStatusCode\x12!.da.proto.DeleteStatusCodeRequest\x1a\".da.proto.DeleteStatusCodeResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_status_code_proto_rawDescOnce sync.Once
	file_status_code_proto_rawDescData []byte
)

func file_status_code_proto_rawDescGZIP() []byte {
	file_status_code_proto_rawDescOnce.Do(func() {
		file_status_code_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_status_code_proto_rawDesc), len(file_status_code_proto_rawDesc)))
	})
	return file_status_code_proto_rawDescData
}

var file_status_code_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_status_code_proto_goTypes = []any{
	(*StatusCode)(nil),               // 0: da.proto.StatusCode
	(*CreateStatusCodeRequest)(nil),  // 1: da.proto.CreateStatusCodeRequest
	(*CreateStatusCodeResponse)(nil), // 2: da.proto.CreateStatusCodeResponse
	(*ReadStatusCodeRequest)(nil),    // 3: da.proto.ReadStatusCodeRequest
	(*ReadStatusCodeResponse)(nil),   // 4: da.proto.ReadStatusCodeResponse
	(*ReadStatusCodesRequest)(nil),   // 5: da.proto.ReadStatusCodesRequest
	(*ReadStatusCodesResponse)(nil),  // 6: da.proto.ReadStatusCodesResponse
	(*UpdateStatusCodeRequest)(nil),  // 7: da.proto.UpdateStatusCodeRequest
	(*UpdateStatusCodeResponse)(nil), // 8: da.proto.UpdateStatusCodeResponse
	(*DeleteStatusCodeRequest)(nil),  // 9: da.proto.DeleteStatusCodeRequest
	(*DeleteStatusCodeResponse)(nil), // 10: da.proto.DeleteStatusCodeResponse
}
var file_status_code_proto_depIdxs = []int32{
	0,  // 0: da.proto.CreateStatusCodeRequest.statusCode:type_name -> da.proto.StatusCode
	0,  // 1: da.proto.CreateStatusCodeResponse.statusCode:type_name -> da.proto.StatusCode
	0,  // 2: da.proto.ReadStatusCodeResponse.statusCode:type_name -> da.proto.StatusCode
	0,  // 3: da.proto.ReadStatusCodesResponse.statusCodes:type_name -> da.proto.StatusCode
	0,  // 4: da.proto.UpdateStatusCodeRequest.statusCode:type_name -> da.proto.StatusCode
	0,  // 5: da.proto.UpdateStatusCodeResponse.statusCode:type_name -> da.proto.StatusCode
	1,  // 6: da.proto.StatusCodeService.CreateStatusCode:input_type -> da.proto.CreateStatusCodeRequest
	3,  // 7: da.proto.StatusCodeService.ReadStatusCode:input_type -> da.proto.ReadStatusCodeRequest
	5,  // 8: da.proto.StatusCodeService.ReadStatusCodes:input_type -> da.proto.ReadStatusCodesRequest
	7,  // 9: da.proto.StatusCodeService.UpdateStatusCode:input_type -> da.proto.UpdateStatusCodeRequest
	9,  // 10: da.proto.StatusCodeService.DeleteStatusCode:input_type -> da.proto.DeleteStatusCodeRequest
	2,  // 11: da.proto.StatusCodeService.CreateStatusCode:output_type -> da.proto.CreateStatusCodeResponse
	4,  // 12: da.proto.StatusCodeService.ReadStatusCode:output_type -> da.proto.ReadStatusCodeResponse
	6,  // 13: da.proto.StatusCodeService.ReadStatusCodes:output_type -> da.proto.ReadStatusCodesResponse
	8,  // 14: da.proto.StatusCodeService.UpdateStatusCode:output_type -> da.proto.UpdateStatusCodeResponse
	10, // 15: da.proto.StatusCodeService.DeleteStatusCode:output_type -> da.proto.DeleteStatusCodeResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_status_code_proto_init() }
func file_status_code_proto_init() {
	if File_status_code_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_status_code_proto_rawDesc), len(file_status_code_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_status_code_proto_goTypes,
		DependencyIndexes: file_status_code_proto_depIdxs,
		MessageInfos:      file_status_code_proto_msgTypes,
	}.Build()
	File_status_code_proto = out.File
	file_status_code_proto_goTypes = nil
	file_status_code_proto_depIdxs = nil
}
