// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies,ts_nocheck,optimize_code_size
// @generated from protobuf file "ai.proto" (package "da.proto", syntax proto3)
// tslint:disable
// @ts-nocheck
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { AIService } from "./ai";
import type { GenerateReplyResponse } from "./ai";
import type { GenerateReplyRequest } from "./ai";
import type { SummarizeTextResponse } from "./ai";
import type { SummarizeTextRequest } from "./ai";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { ClassifyTextResponse } from "./ai";
import type { ClassifyTextRequest } from "./ai";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service da.proto.AIService
 */
export interface IAIServiceClient {
    /**
     * @generated from protobuf rpc: ClassifyText
     */
    classifyText(input: ClassifyTextRequest, options?: RpcOptions): UnaryCall<ClassifyTextRequest, ClassifyTextResponse>;
    /**
     * @generated from protobuf rpc: SummarizeText
     */
    summarizeText(input: SummarizeTextRequest, options?: RpcOptions): UnaryCall<SummarizeTextRequest, SummarizeTextResponse>;
    /**
     * @generated from protobuf rpc: GenerateReply
     */
    generateReply(input: GenerateReplyRequest, options?: RpcOptions): UnaryCall<GenerateReplyRequest, GenerateReplyResponse>;
}
/**
 * @generated from protobuf service da.proto.AIService
 */
export class AIServiceClient implements IAIServiceClient, ServiceInfo {
    typeName = AIService.typeName;
    methods = AIService.methods;
    options = AIService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: ClassifyText
     */
    classifyText(input: ClassifyTextRequest, options?: RpcOptions): UnaryCall<ClassifyTextRequest, ClassifyTextResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<ClassifyTextRequest, ClassifyTextResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SummarizeText
     */
    summarizeText(input: SummarizeTextRequest, options?: RpcOptions): UnaryCall<SummarizeTextRequest, SummarizeTextResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<SummarizeTextRequest, SummarizeTextResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GenerateReply
     */
    generateReply(input: GenerateReplyRequest, options?: RpcOptions): UnaryCall<GenerateReplyRequest, GenerateReplyResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GenerateReplyRequest, GenerateReplyResponse>("unary", this._transport, method, opt, input);
    }
}
