// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies,ts_nocheck,optimize_code_size
// @generated from protobuf file "audio.proto" (package "da.proto", syntax proto3)
// tslint:disable
// @ts-nocheck
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { AudioManagerService } from "./audio";
import type { DownloadAudioResponse } from "./audio";
import type { DownloadAudioRequest } from "./audio";
import type { ReadAudioListResponse } from "./audio";
import type { ReadAudioListRequest } from "./audio";
import type { DeleteAudioResponse } from "./audio";
import type { DeleteAudioRequest } from "./audio";
import type { ReadAudioResponse } from "./audio";
import type { ReadAudioRequest } from "./audio";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { UploadAudioChunkResponse } from "./audio";
import type { UploadAudioChunkRequest } from "./audio";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service da.proto.AudioManagerService
 */
export interface IAudioManagerServiceClient {
    /**
     * @generated from protobuf rpc: UploadAudioChunk
     */
    uploadAudioChunk(input: UploadAudioChunkRequest, options?: RpcOptions): UnaryCall<UploadAudioChunkRequest, UploadAudioChunkResponse>;
    /**
     * @generated from protobuf rpc: ReadAudio
     */
    readAudio(input: ReadAudioRequest, options?: RpcOptions): UnaryCall<ReadAudioRequest, ReadAudioResponse>;
    /**
     * @generated from protobuf rpc: DeleteAudio
     */
    deleteAudio(input: DeleteAudioRequest, options?: RpcOptions): UnaryCall<DeleteAudioRequest, DeleteAudioResponse>;
    /**
     * @generated from protobuf rpc: ReadAudioList
     */
    readAudioList(input: ReadAudioListRequest, options?: RpcOptions): UnaryCall<ReadAudioListRequest, ReadAudioListResponse>;
    /**
     * @generated from protobuf rpc: DownloadAudio
     */
    downloadAudio(input: DownloadAudioRequest, options?: RpcOptions): UnaryCall<DownloadAudioRequest, DownloadAudioResponse>;
}
/**
 * @generated from protobuf service da.proto.AudioManagerService
 */
export class AudioManagerServiceClient implements IAudioManagerServiceClient, ServiceInfo {
    typeName = AudioManagerService.typeName;
    methods = AudioManagerService.methods;
    options = AudioManagerService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: UploadAudioChunk
     */
    uploadAudioChunk(input: UploadAudioChunkRequest, options?: RpcOptions): UnaryCall<UploadAudioChunkRequest, UploadAudioChunkResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<UploadAudioChunkRequest, UploadAudioChunkResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ReadAudio
     */
    readAudio(input: ReadAudioRequest, options?: RpcOptions): UnaryCall<ReadAudioRequest, ReadAudioResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<ReadAudioRequest, ReadAudioResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteAudio
     */
    deleteAudio(input: DeleteAudioRequest, options?: RpcOptions): UnaryCall<DeleteAudioRequest, DeleteAudioResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteAudioRequest, DeleteAudioResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ReadAudioList
     */
    readAudioList(input: ReadAudioListRequest, options?: RpcOptions): UnaryCall<ReadAudioListRequest, ReadAudioListResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<ReadAudioListRequest, ReadAudioListResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DownloadAudio
     */
    downloadAudio(input: DownloadAudioRequest, options?: RpcOptions): UnaryCall<DownloadAudioRequest, DownloadAudioResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<DownloadAudioRequest, DownloadAudioResponse>("unary", this._transport, method, opt, input);
    }
}
