// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies,ts_nocheck,optimize_code_size
// @generated from protobuf file "automation.proto" (package "da.proto", syntax proto3)
// tslint:disable
// @ts-nocheck
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { AutomationService } from "./automation";
import type { AutomationActionsResponse } from "./automation";
import type { AutomationActionRequest } from "./automation";
import type { AutomationTriggersResponse } from "./automation";
import type { Empty } from "./google/protobuf/empty";
import type { AutomationTriggerRequest } from "./automation";
import type { ReadAutomationsResponse } from "./automation";
import type { ReadAutomationsRequest } from "./automation";
import type { SuccessAutomationResponse } from "./automation";
import type { ReadAutomationRequest } from "./automation";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { AutomationResponse } from "./automation";
import type { AutomationRequest } from "./automation";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service da.proto.AutomationService
 */
export interface IAutomationServiceClient {
    /**
     * @generated from protobuf rpc: CreateAutomation
     */
    createAutomation(input: AutomationRequest, options?: RpcOptions): UnaryCall<AutomationRequest, AutomationResponse>;
    /**
     * @generated from protobuf rpc: ReadAutomation
     */
    readAutomation(input: ReadAutomationRequest, options?: RpcOptions): UnaryCall<ReadAutomationRequest, AutomationResponse>;
    /**
     * @generated from protobuf rpc: UpdateAutomation
     */
    updateAutomation(input: AutomationRequest, options?: RpcOptions): UnaryCall<AutomationRequest, AutomationResponse>;
    /**
     * @generated from protobuf rpc: DeleteAutomation
     */
    deleteAutomation(input: ReadAutomationRequest, options?: RpcOptions): UnaryCall<ReadAutomationRequest, SuccessAutomationResponse>;
    /**
     * @generated from protobuf rpc: ReadAutomations
     */
    readAutomations(input: ReadAutomationsRequest, options?: RpcOptions): UnaryCall<ReadAutomationsRequest, ReadAutomationsResponse>;
    /**
     * @generated from protobuf rpc: SaveTrigger
     */
    saveTrigger(input: AutomationTriggerRequest, options?: RpcOptions): UnaryCall<AutomationTriggerRequest, SuccessAutomationResponse>;
    /**
     * @generated from protobuf rpc: ReadTriggers
     */
    readTriggers(input: Empty, options?: RpcOptions): UnaryCall<Empty, AutomationTriggersResponse>;
    /**
     * @generated from protobuf rpc: SaveAction
     */
    saveAction(input: AutomationActionRequest, options?: RpcOptions): UnaryCall<AutomationActionRequest, SuccessAutomationResponse>;
    /**
     * @generated from protobuf rpc: ReadActions
     */
    readActions(input: Empty, options?: RpcOptions): UnaryCall<Empty, AutomationActionsResponse>;
}
/**
 * @generated from protobuf service da.proto.AutomationService
 */
export class AutomationServiceClient implements IAutomationServiceClient, ServiceInfo {
    typeName = AutomationService.typeName;
    methods = AutomationService.methods;
    options = AutomationService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: CreateAutomation
     */
    createAutomation(input: AutomationRequest, options?: RpcOptions): UnaryCall<AutomationRequest, AutomationResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<AutomationRequest, AutomationResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ReadAutomation
     */
    readAutomation(input: ReadAutomationRequest, options?: RpcOptions): UnaryCall<ReadAutomationRequest, AutomationResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<ReadAutomationRequest, AutomationResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateAutomation
     */
    updateAutomation(input: AutomationRequest, options?: RpcOptions): UnaryCall<AutomationRequest, AutomationResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<AutomationRequest, AutomationResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteAutomation
     */
    deleteAutomation(input: ReadAutomationRequest, options?: RpcOptions): UnaryCall<ReadAutomationRequest, SuccessAutomationResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<ReadAutomationRequest, SuccessAutomationResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ReadAutomations
     */
    readAutomations(input: ReadAutomationsRequest, options?: RpcOptions): UnaryCall<ReadAutomationsRequest, ReadAutomationsResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<ReadAutomationsRequest, ReadAutomationsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SaveTrigger
     */
    saveTrigger(input: AutomationTriggerRequest, options?: RpcOptions): UnaryCall<AutomationTriggerRequest, SuccessAutomationResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<AutomationTriggerRequest, SuccessAutomationResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ReadTriggers
     */
    readTriggers(input: Empty, options?: RpcOptions): UnaryCall<Empty, AutomationTriggersResponse> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, AutomationTriggersResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SaveAction
     */
    saveAction(input: AutomationActionRequest, options?: RpcOptions): UnaryCall<AutomationActionRequest, SuccessAutomationResponse> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<AutomationActionRequest, SuccessAutomationResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ReadActions
     */
    readActions(input: Empty, options?: RpcOptions): UnaryCall<Empty, AutomationActionsResponse> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, AutomationActionsResponse>("unary", this._transport, method, opt, input);
    }
}
