// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies,ts_nocheck,optimize_code_size
// @generated from protobuf file "call_session.proto" (package "da.proto", syntax proto3)
// tslint:disable
// @ts-nocheck
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { CallSessionService } from "./call_session";
import type { SuccessDestinationResponse } from "./call_session";
import type { AddDestinationRequest } from "./call_session";
import type { SuccessNoteResponse } from "./call_session";
import type { AddNoteRequest } from "./call_session";
import type { RemoveFromHoldRequest } from "./call_session";
import type { SuccessHoldResponse } from "./call_session";
import type { PlaceOnHoldRequest } from "./call_session";
import type { RemoveParticipantRequest } from "./call_session";
import type { SuccessParticipantResponse } from "./call_session";
import type { AddParticipantRequest } from "./call_session";
import type { CallSession } from "./call_session";
import type { ReadCallSessionRequest } from "./call_session";
import type { EndCallSessionRequest } from "./call_session";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { SuccessCallSessionResponse } from "./call_session";
import type { StartCallSessionRequest } from "./call_session";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service da.proto.CallSessionService
 */
export interface ICallSessionServiceClient {
    /**
     * @generated from protobuf rpc: StartSession
     */
    startSession(input: StartCallSessionRequest, options?: RpcOptions): UnaryCall<StartCallSessionRequest, SuccessCallSessionResponse>;
    /**
     * @generated from protobuf rpc: EndSession
     */
    endSession(input: EndCallSessionRequest, options?: RpcOptions): UnaryCall<EndCallSessionRequest, SuccessCallSessionResponse>;
    /**
     * @generated from protobuf rpc: ReadSession
     */
    readSession(input: ReadCallSessionRequest, options?: RpcOptions): UnaryCall<ReadCallSessionRequest, CallSession>;
    /**
     * @generated from protobuf rpc: AddParticipant
     */
    addParticipant(input: AddParticipantRequest, options?: RpcOptions): UnaryCall<AddParticipantRequest, SuccessParticipantResponse>;
    /**
     * @generated from protobuf rpc: RemoveParticipant
     */
    removeParticipant(input: RemoveParticipantRequest, options?: RpcOptions): UnaryCall<RemoveParticipantRequest, SuccessParticipantResponse>;
    /**
     * @generated from protobuf rpc: PlaceOnHold
     */
    placeOnHold(input: PlaceOnHoldRequest, options?: RpcOptions): UnaryCall<PlaceOnHoldRequest, SuccessHoldResponse>;
    /**
     * @generated from protobuf rpc: RemoveFromHold
     */
    removeFromHold(input: RemoveFromHoldRequest, options?: RpcOptions): UnaryCall<RemoveFromHoldRequest, SuccessHoldResponse>;
    /**
     * @generated from protobuf rpc: AddNote
     */
    addNote(input: AddNoteRequest, options?: RpcOptions): UnaryCall<AddNoteRequest, SuccessNoteResponse>;
    /**
     * @generated from protobuf rpc: AddDestination
     */
    addDestination(input: AddDestinationRequest, options?: RpcOptions): UnaryCall<AddDestinationRequest, SuccessDestinationResponse>;
}
/**
 * @generated from protobuf service da.proto.CallSessionService
 */
export class CallSessionServiceClient implements ICallSessionServiceClient, ServiceInfo {
    typeName = CallSessionService.typeName;
    methods = CallSessionService.methods;
    options = CallSessionService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: StartSession
     */
    startSession(input: StartCallSessionRequest, options?: RpcOptions): UnaryCall<StartCallSessionRequest, SuccessCallSessionResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<StartCallSessionRequest, SuccessCallSessionResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: EndSession
     */
    endSession(input: EndCallSessionRequest, options?: RpcOptions): UnaryCall<EndCallSessionRequest, SuccessCallSessionResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<EndCallSessionRequest, SuccessCallSessionResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ReadSession
     */
    readSession(input: ReadCallSessionRequest, options?: RpcOptions): UnaryCall<ReadCallSessionRequest, CallSession> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<ReadCallSessionRequest, CallSession>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AddParticipant
     */
    addParticipant(input: AddParticipantRequest, options?: RpcOptions): UnaryCall<AddParticipantRequest, SuccessParticipantResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<AddParticipantRequest, SuccessParticipantResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RemoveParticipant
     */
    removeParticipant(input: RemoveParticipantRequest, options?: RpcOptions): UnaryCall<RemoveParticipantRequest, SuccessParticipantResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<RemoveParticipantRequest, SuccessParticipantResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: PlaceOnHold
     */
    placeOnHold(input: PlaceOnHoldRequest, options?: RpcOptions): UnaryCall<PlaceOnHoldRequest, SuccessHoldResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<PlaceOnHoldRequest, SuccessHoldResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RemoveFromHold
     */
    removeFromHold(input: RemoveFromHoldRequest, options?: RpcOptions): UnaryCall<RemoveFromHoldRequest, SuccessHoldResponse> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<RemoveFromHoldRequest, SuccessHoldResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AddNote
     */
    addNote(input: AddNoteRequest, options?: RpcOptions): UnaryCall<AddNoteRequest, SuccessNoteResponse> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<AddNoteRequest, SuccessNoteResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AddDestination
     */
    addDestination(input: AddDestinationRequest, options?: RpcOptions): UnaryCall<AddDestinationRequest, SuccessDestinationResponse> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<AddDestinationRequest, SuccessDestinationResponse>("unary", this._transport, method, opt, input);
    }
}
