// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies,ts_nocheck,optimize_code_size
// @generated from protobuf file "call_analytics_export.proto" (package "da.proto", syntax proto3)
// tslint:disable
// @ts-nocheck
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Timestamp } from "./google/protobuf/timestamp";
/**
 * @generated from protobuf message da.proto.ExportAnalyticsRequest
 */
export interface ExportAnalyticsRequest {
    /**
     * @generated from protobuf field: string membership_id = 1
     */
    membershipId: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp start_date = 2
     */
    startDate?: Timestamp;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp end_date = 3
     */
    endDate?: Timestamp;
    /**
     * @generated from protobuf field: string date_range = 4
     */
    dateRange: string;
    /**
     * @generated from protobuf field: repeated string queue_ids = 5
     */
    queueIds: string[];
    /**
     * @generated from protobuf field: repeated string agent_ids = 6
     */
    agentIds: string[];
    /**
     * @generated from protobuf field: repeated string campaign_ids = 7
     */
    campaignIds: string[];
    /**
     * @generated from protobuf field: da.proto.ExportFormat format = 8
     */
    format: ExportFormat;
    /**
     * @generated from protobuf field: da.proto.ExportType export_type = 9
     */
    exportType: ExportType;
}
/**
 * @generated from protobuf message da.proto.ExportChunk
 */
export interface ExportChunk {
    /**
     * @generated from protobuf field: bytes data = 1
     */
    data: Uint8Array;
    /**
     * @generated from protobuf field: int32 progress = 2
     */
    progress: number;
    /**
     * @generated from protobuf field: bool is_complete = 3
     */
    isComplete: boolean;
    /**
     * @generated from protobuf field: string filename = 4
     */
    filename: string;
    /**
     * @generated from protobuf field: string mime_type = 5
     */
    mimeType: string;
    /**
     * @generated from protobuf field: int64 total_size = 6
     */
    totalSize: bigint;
    /**
     * @generated from protobuf field: int64 current_size = 7
     */
    currentSize: bigint;
}
/**
 * @generated from protobuf enum da.proto.ExportFormat
 */
export enum ExportFormat {
    /**
     * @generated from protobuf enum value: CSV = 0;
     */
    CSV = 0,
    /**
     * @generated from protobuf enum value: EXCEL = 1;
     */
    EXCEL = 1,
    /**
     * @generated from protobuf enum value: PDF = 2;
     */
    PDF = 2
}
/**
 * @generated from protobuf enum da.proto.ExportType
 */
export enum ExportType {
    /**
     * @generated from protobuf enum value: ANALYTICS_OVERVIEW = 0;
     */
    ANALYTICS_OVERVIEW = 0,
    /**
     * @generated from protobuf enum value: CALL_TRAFFIC = 1;
     */
    CALL_TRAFFIC = 1,
    /**
     * @generated from protobuf enum value: CALL_HANDLING = 2;
     */
    CALL_HANDLING = 2,
    /**
     * @generated from protobuf enum value: QUEUE_IVR = 3;
     */
    QUEUE_IVR = 3,
    /**
     * @generated from protobuf enum value: CAMPAIGN = 4;
     */
    CAMPAIGN = 4,
    /**
     * @generated from protobuf enum value: CUSTOMER_EXPERIENCE = 5;
     */
    CUSTOMER_EXPERIENCE = 5
}
// @generated message type with reflection information, may provide speed optimized methods
class ExportAnalyticsRequest$Type extends MessageType<ExportAnalyticsRequest> {
    constructor() {
        super("da.proto.ExportAnalyticsRequest", [
            { no: 1, name: "membership_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "start_date", kind: "message", T: () => Timestamp },
            { no: 3, name: "end_date", kind: "message", T: () => Timestamp },
            { no: 4, name: "date_range", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "queue_ids", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "agent_ids", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "campaign_ids", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "format", kind: "enum", T: () => ["da.proto.ExportFormat", ExportFormat] },
            { no: 9, name: "export_type", kind: "enum", T: () => ["da.proto.ExportType", ExportType] }
        ]);
    }
    create(value?: PartialMessage<ExportAnalyticsRequest>): ExportAnalyticsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.membershipId = "";
        message.dateRange = "";
        message.queueIds = [];
        message.agentIds = [];
        message.campaignIds = [];
        message.format = 0;
        message.exportType = 0;
        if (value !== undefined)
            reflectionMergePartial<ExportAnalyticsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ExportAnalyticsRequest): ExportAnalyticsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string membership_id */ 1:
                    message.membershipId = reader.string();
                    break;
                case /* google.protobuf.Timestamp start_date */ 2:
                    message.startDate = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.startDate);
                    break;
                case /* google.protobuf.Timestamp end_date */ 3:
                    message.endDate = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.endDate);
                    break;
                case /* string date_range */ 4:
                    message.dateRange = reader.string();
                    break;
                case /* repeated string queue_ids */ 5:
                    message.queueIds.push(reader.string());
                    break;
                case /* repeated string agent_ids */ 6:
                    message.agentIds.push(reader.string());
                    break;
                case /* repeated string campaign_ids */ 7:
                    message.campaignIds.push(reader.string());
                    break;
                case /* da.proto.ExportFormat format */ 8:
                    message.format = reader.int32();
                    break;
                case /* da.proto.ExportType export_type */ 9:
                    message.exportType = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ExportAnalyticsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string membership_id = 1; */
        if (message.membershipId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.membershipId);
        /* google.protobuf.Timestamp start_date = 2; */
        if (message.startDate)
            Timestamp.internalBinaryWrite(message.startDate, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Timestamp end_date = 3; */
        if (message.endDate)
            Timestamp.internalBinaryWrite(message.endDate, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* string date_range = 4; */
        if (message.dateRange !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.dateRange);
        /* repeated string queue_ids = 5; */
        for (let i = 0; i < message.queueIds.length; i++)
            writer.tag(5, WireType.LengthDelimited).string(message.queueIds[i]);
        /* repeated string agent_ids = 6; */
        for (let i = 0; i < message.agentIds.length; i++)
            writer.tag(6, WireType.LengthDelimited).string(message.agentIds[i]);
        /* repeated string campaign_ids = 7; */
        for (let i = 0; i < message.campaignIds.length; i++)
            writer.tag(7, WireType.LengthDelimited).string(message.campaignIds[i]);
        /* da.proto.ExportFormat format = 8; */
        if (message.format !== 0)
            writer.tag(8, WireType.Varint).int32(message.format);
        /* da.proto.ExportType export_type = 9; */
        if (message.exportType !== 0)
            writer.tag(9, WireType.Varint).int32(message.exportType);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.ExportAnalyticsRequest
 */
export const ExportAnalyticsRequest = new ExportAnalyticsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ExportChunk$Type extends MessageType<ExportChunk> {
    constructor() {
        super("da.proto.ExportChunk", [
            { no: 1, name: "data", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 2, name: "progress", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "is_complete", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 4, name: "filename", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "mime_type", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "total_size", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 7, name: "current_size", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 0 /*LongType.BIGINT*/ }
        ]);
    }
    create(value?: PartialMessage<ExportChunk>): ExportChunk {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.data = new Uint8Array(0);
        message.progress = 0;
        message.isComplete = false;
        message.filename = "";
        message.mimeType = "";
        message.totalSize = 0n;
        message.currentSize = 0n;
        if (value !== undefined)
            reflectionMergePartial<ExportChunk>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ExportChunk): ExportChunk {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bytes data */ 1:
                    message.data = reader.bytes();
                    break;
                case /* int32 progress */ 2:
                    message.progress = reader.int32();
                    break;
                case /* bool is_complete */ 3:
                    message.isComplete = reader.bool();
                    break;
                case /* string filename */ 4:
                    message.filename = reader.string();
                    break;
                case /* string mime_type */ 5:
                    message.mimeType = reader.string();
                    break;
                case /* int64 total_size */ 6:
                    message.totalSize = reader.int64().toBigInt();
                    break;
                case /* int64 current_size */ 7:
                    message.currentSize = reader.int64().toBigInt();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ExportChunk, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bytes data = 1; */
        if (message.data.length)
            writer.tag(1, WireType.LengthDelimited).bytes(message.data);
        /* int32 progress = 2; */
        if (message.progress !== 0)
            writer.tag(2, WireType.Varint).int32(message.progress);
        /* bool is_complete = 3; */
        if (message.isComplete !== false)
            writer.tag(3, WireType.Varint).bool(message.isComplete);
        /* string filename = 4; */
        if (message.filename !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.filename);
        /* string mime_type = 5; */
        if (message.mimeType !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.mimeType);
        /* int64 total_size = 6; */
        if (message.totalSize !== 0n)
            writer.tag(6, WireType.Varint).int64(message.totalSize);
        /* int64 current_size = 7; */
        if (message.currentSize !== 0n)
            writer.tag(7, WireType.Varint).int64(message.currentSize);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.ExportChunk
 */
export const ExportChunk = new ExportChunk$Type();
/**
 * @generated ServiceType for protobuf service da.proto.CallAnalyticsExportService
 */
export const CallAnalyticsExportService = new ServiceType("da.proto.CallAnalyticsExportService", [
    { name: "ExportAnalytics", serverStreaming: true, options: {}, I: ExportAnalyticsRequest, O: ExportChunk }
]);
