// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies,ts_nocheck,optimize_code_size
// @generated from protobuf file "category.proto" (package "da.proto", syntax proto3)
// tslint:disable
// @ts-nocheck
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { OwnerType } from "./owner_type";
/**
 * @generated from protobuf message da.proto.CategoryCustomField
 */
export interface CategoryCustomField {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string category_id = 2
     */
    categoryId: string;
    /**
     * @generated from protobuf field: string custom_field_definition_id = 3
     */
    customFieldDefinitionId: string;
    /**
     * @generated from protobuf field: string value = 4
     */
    value: string;
    /**
     * @generated from protobuf field: string created_at = 5
     */
    createdAt: string;
    /**
     * @generated from protobuf field: string updated_at = 6
     */
    updatedAt: string;
}
/**
 * @generated from protobuf message da.proto.TicketCategory
 */
export interface TicketCategory {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string name = 2
     */
    name: string;
    /**
     * @generated from protobuf field: string description = 3
     */
    description: string;
    /**
     * @generated from protobuf field: repeated string keywords = 4
     */
    keywords: string[];
    /**
     * @generated from protobuf field: string created_at = 5
     */
    createdAt: string;
    /**
     * @generated from protobuf field: string updated_at = 6
     */
    updatedAt: string;
    /**
     * @generated from protobuf field: string created_by = 7
     */
    createdBy: string;
    /**
     * @generated from protobuf field: string owner_id = 8
     */
    ownerId: string;
    /**
     * @generated from protobuf field: da.proto.OwnerType owner_type = 9
     */
    ownerType: OwnerType;
    /**
     * @generated from protobuf field: repeated da.proto.CategoryCustomField custom_fields = 10
     */
    customFields: CategoryCustomField[];
}
/**
 * @generated from protobuf message da.proto.CreateTicketCategoryRequest
 */
export interface CreateTicketCategoryRequest {
    /**
     * @generated from protobuf field: da.proto.TicketCategory data = 1
     */
    data?: TicketCategory;
}
/**
 * @generated from protobuf message da.proto.CreateTicketCategoryResponse
 */
export interface CreateTicketCategoryResponse {
    /**
     * @generated from protobuf field: da.proto.TicketCategory data = 1
     */
    data?: TicketCategory;
}
/**
 * @generated from protobuf message da.proto.ReadTicketCategoryRequest
 */
export interface ReadTicketCategoryRequest {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
}
/**
 * @generated from protobuf message da.proto.ReadTicketCategoryResponse
 */
export interface ReadTicketCategoryResponse {
    /**
     * @generated from protobuf field: da.proto.TicketCategory data = 1
     */
    data?: TicketCategory;
}
/**
 * @generated from protobuf message da.proto.UpdateTicketCategoryRequest
 */
export interface UpdateTicketCategoryRequest {
    /**
     * @generated from protobuf field: da.proto.TicketCategory data = 1
     */
    data?: TicketCategory;
}
/**
 * @generated from protobuf message da.proto.UpdateTicketCategoryResponse
 */
export interface UpdateTicketCategoryResponse {
    /**
     * @generated from protobuf field: da.proto.TicketCategory data = 1
     */
    data?: TicketCategory;
}
/**
 * @generated from protobuf message da.proto.DeleteTicketCategoryRequest
 */
export interface DeleteTicketCategoryRequest {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
}
/**
 * @generated from protobuf message da.proto.DeleteTicketCategoryResponse
 */
export interface DeleteTicketCategoryResponse {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
}
/**
 * @generated from protobuf message da.proto.ReadTicketCategoriesRequest
 */
export interface ReadTicketCategoriesRequest {
    /**
     * @generated from protobuf field: int32 page = 1
     */
    page: number;
    /**
     * @generated from protobuf field: int32 per_page = 2
     */
    perPage: number;
    /**
     * @generated from protobuf field: string owner_id = 3
     */
    ownerId: string;
    /**
     * @generated from protobuf field: da.proto.OwnerType owner_type = 4
     */
    ownerType: OwnerType;
}
/**
 * @generated from protobuf message da.proto.ReadTicketCategoriesResponse
 */
export interface ReadTicketCategoriesResponse {
    /**
     * @generated from protobuf field: int32 total_count = 1
     */
    totalCount: number;
    /**
     * @generated from protobuf field: repeated da.proto.TicketCategory data = 2
     */
    data: TicketCategory[];
}
// @generated message type with reflection information, may provide speed optimized methods
class CategoryCustomField$Type extends MessageType<CategoryCustomField> {
    constructor() {
        super("da.proto.CategoryCustomField", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "category_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "custom_field_definition_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "value", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "created_at", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "updated_at", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CategoryCustomField>): CategoryCustomField {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.categoryId = "";
        message.customFieldDefinitionId = "";
        message.value = "";
        message.createdAt = "";
        message.updatedAt = "";
        if (value !== undefined)
            reflectionMergePartial<CategoryCustomField>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CategoryCustomField): CategoryCustomField {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string category_id */ 2:
                    message.categoryId = reader.string();
                    break;
                case /* string custom_field_definition_id */ 3:
                    message.customFieldDefinitionId = reader.string();
                    break;
                case /* string value */ 4:
                    message.value = reader.string();
                    break;
                case /* string created_at */ 5:
                    message.createdAt = reader.string();
                    break;
                case /* string updated_at */ 6:
                    message.updatedAt = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CategoryCustomField, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string category_id = 2; */
        if (message.categoryId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.categoryId);
        /* string custom_field_definition_id = 3; */
        if (message.customFieldDefinitionId !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.customFieldDefinitionId);
        /* string value = 4; */
        if (message.value !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.value);
        /* string created_at = 5; */
        if (message.createdAt !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.createdAt);
        /* string updated_at = 6; */
        if (message.updatedAt !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.updatedAt);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.CategoryCustomField
 */
export const CategoryCustomField = new CategoryCustomField$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TicketCategory$Type extends MessageType<TicketCategory> {
    constructor() {
        super("da.proto.TicketCategory", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "keywords", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "created_at", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "updated_at", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "created_by", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "owner_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "owner_type", kind: "enum", T: () => ["da.proto.OwnerType", OwnerType] },
            { no: 10, name: "custom_fields", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => CategoryCustomField }
        ]);
    }
    create(value?: PartialMessage<TicketCategory>): TicketCategory {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.name = "";
        message.description = "";
        message.keywords = [];
        message.createdAt = "";
        message.updatedAt = "";
        message.createdBy = "";
        message.ownerId = "";
        message.ownerType = 0;
        message.customFields = [];
        if (value !== undefined)
            reflectionMergePartial<TicketCategory>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TicketCategory): TicketCategory {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* string description */ 3:
                    message.description = reader.string();
                    break;
                case /* repeated string keywords */ 4:
                    message.keywords.push(reader.string());
                    break;
                case /* string created_at */ 5:
                    message.createdAt = reader.string();
                    break;
                case /* string updated_at */ 6:
                    message.updatedAt = reader.string();
                    break;
                case /* string created_by */ 7:
                    message.createdBy = reader.string();
                    break;
                case /* string owner_id */ 8:
                    message.ownerId = reader.string();
                    break;
                case /* da.proto.OwnerType owner_type */ 9:
                    message.ownerType = reader.int32();
                    break;
                case /* repeated da.proto.CategoryCustomField custom_fields */ 10:
                    message.customFields.push(CategoryCustomField.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TicketCategory, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* string description = 3; */
        if (message.description !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.description);
        /* repeated string keywords = 4; */
        for (let i = 0; i < message.keywords.length; i++)
            writer.tag(4, WireType.LengthDelimited).string(message.keywords[i]);
        /* string created_at = 5; */
        if (message.createdAt !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.createdAt);
        /* string updated_at = 6; */
        if (message.updatedAt !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.updatedAt);
        /* string created_by = 7; */
        if (message.createdBy !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.createdBy);
        /* string owner_id = 8; */
        if (message.ownerId !== "")
            writer.tag(8, WireType.LengthDelimited).string(message.ownerId);
        /* da.proto.OwnerType owner_type = 9; */
        if (message.ownerType !== 0)
            writer.tag(9, WireType.Varint).int32(message.ownerType);
        /* repeated da.proto.CategoryCustomField custom_fields = 10; */
        for (let i = 0; i < message.customFields.length; i++)
            CategoryCustomField.internalBinaryWrite(message.customFields[i], writer.tag(10, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.TicketCategory
 */
export const TicketCategory = new TicketCategory$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateTicketCategoryRequest$Type extends MessageType<CreateTicketCategoryRequest> {
    constructor() {
        super("da.proto.CreateTicketCategoryRequest", [
            { no: 1, name: "data", kind: "message", T: () => TicketCategory }
        ]);
    }
    create(value?: PartialMessage<CreateTicketCategoryRequest>): CreateTicketCategoryRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<CreateTicketCategoryRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateTicketCategoryRequest): CreateTicketCategoryRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* da.proto.TicketCategory data */ 1:
                    message.data = TicketCategory.internalBinaryRead(reader, reader.uint32(), options, message.data);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateTicketCategoryRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* da.proto.TicketCategory data = 1; */
        if (message.data)
            TicketCategory.internalBinaryWrite(message.data, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.CreateTicketCategoryRequest
 */
export const CreateTicketCategoryRequest = new CreateTicketCategoryRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateTicketCategoryResponse$Type extends MessageType<CreateTicketCategoryResponse> {
    constructor() {
        super("da.proto.CreateTicketCategoryResponse", [
            { no: 1, name: "data", kind: "message", T: () => TicketCategory }
        ]);
    }
    create(value?: PartialMessage<CreateTicketCategoryResponse>): CreateTicketCategoryResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<CreateTicketCategoryResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateTicketCategoryResponse): CreateTicketCategoryResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* da.proto.TicketCategory data */ 1:
                    message.data = TicketCategory.internalBinaryRead(reader, reader.uint32(), options, message.data);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateTicketCategoryResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* da.proto.TicketCategory data = 1; */
        if (message.data)
            TicketCategory.internalBinaryWrite(message.data, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.CreateTicketCategoryResponse
 */
export const CreateTicketCategoryResponse = new CreateTicketCategoryResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ReadTicketCategoryRequest$Type extends MessageType<ReadTicketCategoryRequest> {
    constructor() {
        super("da.proto.ReadTicketCategoryRequest", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ReadTicketCategoryRequest>): ReadTicketCategoryRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        if (value !== undefined)
            reflectionMergePartial<ReadTicketCategoryRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ReadTicketCategoryRequest): ReadTicketCategoryRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ReadTicketCategoryRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.ReadTicketCategoryRequest
 */
export const ReadTicketCategoryRequest = new ReadTicketCategoryRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ReadTicketCategoryResponse$Type extends MessageType<ReadTicketCategoryResponse> {
    constructor() {
        super("da.proto.ReadTicketCategoryResponse", [
            { no: 1, name: "data", kind: "message", T: () => TicketCategory }
        ]);
    }
    create(value?: PartialMessage<ReadTicketCategoryResponse>): ReadTicketCategoryResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<ReadTicketCategoryResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ReadTicketCategoryResponse): ReadTicketCategoryResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* da.proto.TicketCategory data */ 1:
                    message.data = TicketCategory.internalBinaryRead(reader, reader.uint32(), options, message.data);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ReadTicketCategoryResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* da.proto.TicketCategory data = 1; */
        if (message.data)
            TicketCategory.internalBinaryWrite(message.data, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.ReadTicketCategoryResponse
 */
export const ReadTicketCategoryResponse = new ReadTicketCategoryResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateTicketCategoryRequest$Type extends MessageType<UpdateTicketCategoryRequest> {
    constructor() {
        super("da.proto.UpdateTicketCategoryRequest", [
            { no: 1, name: "data", kind: "message", T: () => TicketCategory }
        ]);
    }
    create(value?: PartialMessage<UpdateTicketCategoryRequest>): UpdateTicketCategoryRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<UpdateTicketCategoryRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateTicketCategoryRequest): UpdateTicketCategoryRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* da.proto.TicketCategory data */ 1:
                    message.data = TicketCategory.internalBinaryRead(reader, reader.uint32(), options, message.data);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateTicketCategoryRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* da.proto.TicketCategory data = 1; */
        if (message.data)
            TicketCategory.internalBinaryWrite(message.data, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.UpdateTicketCategoryRequest
 */
export const UpdateTicketCategoryRequest = new UpdateTicketCategoryRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateTicketCategoryResponse$Type extends MessageType<UpdateTicketCategoryResponse> {
    constructor() {
        super("da.proto.UpdateTicketCategoryResponse", [
            { no: 1, name: "data", kind: "message", T: () => TicketCategory }
        ]);
    }
    create(value?: PartialMessage<UpdateTicketCategoryResponse>): UpdateTicketCategoryResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<UpdateTicketCategoryResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateTicketCategoryResponse): UpdateTicketCategoryResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* da.proto.TicketCategory data */ 1:
                    message.data = TicketCategory.internalBinaryRead(reader, reader.uint32(), options, message.data);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateTicketCategoryResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* da.proto.TicketCategory data = 1; */
        if (message.data)
            TicketCategory.internalBinaryWrite(message.data, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.UpdateTicketCategoryResponse
 */
export const UpdateTicketCategoryResponse = new UpdateTicketCategoryResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteTicketCategoryRequest$Type extends MessageType<DeleteTicketCategoryRequest> {
    constructor() {
        super("da.proto.DeleteTicketCategoryRequest", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<DeleteTicketCategoryRequest>): DeleteTicketCategoryRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        if (value !== undefined)
            reflectionMergePartial<DeleteTicketCategoryRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteTicketCategoryRequest): DeleteTicketCategoryRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeleteTicketCategoryRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.DeleteTicketCategoryRequest
 */
export const DeleteTicketCategoryRequest = new DeleteTicketCategoryRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteTicketCategoryResponse$Type extends MessageType<DeleteTicketCategoryResponse> {
    constructor() {
        super("da.proto.DeleteTicketCategoryResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<DeleteTicketCategoryResponse>): DeleteTicketCategoryResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        if (value !== undefined)
            reflectionMergePartial<DeleteTicketCategoryResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteTicketCategoryResponse): DeleteTicketCategoryResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeleteTicketCategoryResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.DeleteTicketCategoryResponse
 */
export const DeleteTicketCategoryResponse = new DeleteTicketCategoryResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ReadTicketCategoriesRequest$Type extends MessageType<ReadTicketCategoriesRequest> {
    constructor() {
        super("da.proto.ReadTicketCategoriesRequest", [
            { no: 1, name: "page", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "per_page", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "owner_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "owner_type", kind: "enum", T: () => ["da.proto.OwnerType", OwnerType] }
        ]);
    }
    create(value?: PartialMessage<ReadTicketCategoriesRequest>): ReadTicketCategoriesRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.page = 0;
        message.perPage = 0;
        message.ownerId = "";
        message.ownerType = 0;
        if (value !== undefined)
            reflectionMergePartial<ReadTicketCategoriesRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ReadTicketCategoriesRequest): ReadTicketCategoriesRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 page */ 1:
                    message.page = reader.int32();
                    break;
                case /* int32 per_page */ 2:
                    message.perPage = reader.int32();
                    break;
                case /* string owner_id */ 3:
                    message.ownerId = reader.string();
                    break;
                case /* da.proto.OwnerType owner_type */ 4:
                    message.ownerType = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ReadTicketCategoriesRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 page = 1; */
        if (message.page !== 0)
            writer.tag(1, WireType.Varint).int32(message.page);
        /* int32 per_page = 2; */
        if (message.perPage !== 0)
            writer.tag(2, WireType.Varint).int32(message.perPage);
        /* string owner_id = 3; */
        if (message.ownerId !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.ownerId);
        /* da.proto.OwnerType owner_type = 4; */
        if (message.ownerType !== 0)
            writer.tag(4, WireType.Varint).int32(message.ownerType);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.ReadTicketCategoriesRequest
 */
export const ReadTicketCategoriesRequest = new ReadTicketCategoriesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ReadTicketCategoriesResponse$Type extends MessageType<ReadTicketCategoriesResponse> {
    constructor() {
        super("da.proto.ReadTicketCategoriesResponse", [
            { no: 1, name: "total_count", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "data", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => TicketCategory }
        ]);
    }
    create(value?: PartialMessage<ReadTicketCategoriesResponse>): ReadTicketCategoriesResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.totalCount = 0;
        message.data = [];
        if (value !== undefined)
            reflectionMergePartial<ReadTicketCategoriesResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ReadTicketCategoriesResponse): ReadTicketCategoriesResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 total_count */ 1:
                    message.totalCount = reader.int32();
                    break;
                case /* repeated da.proto.TicketCategory data */ 2:
                    message.data.push(TicketCategory.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ReadTicketCategoriesResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 total_count = 1; */
        if (message.totalCount !== 0)
            writer.tag(1, WireType.Varint).int32(message.totalCount);
        /* repeated da.proto.TicketCategory data = 2; */
        for (let i = 0; i < message.data.length; i++)
            TicketCategory.internalBinaryWrite(message.data[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.ReadTicketCategoriesResponse
 */
export const ReadTicketCategoriesResponse = new ReadTicketCategoriesResponse$Type();
/**
 * @generated ServiceType for protobuf service da.proto.TicketCategoryService
 */
export const TicketCategoryService = new ServiceType("da.proto.TicketCategoryService", [
    { name: "CreateTicketCategory", options: {}, I: CreateTicketCategoryRequest, O: CreateTicketCategoryResponse },
    { name: "ReadTicketCategory", options: {}, I: ReadTicketCategoryRequest, O: ReadTicketCategoryResponse },
    { name: "UpdateTicketCategory", options: {}, I: UpdateTicketCategoryRequest, O: UpdateTicketCategoryResponse },
    { name: "DeleteTicketCategory", options: {}, I: DeleteTicketCategoryRequest, O: DeleteTicketCategoryResponse },
    { name: "ReadTicketCategories", options: {}, I: ReadTicketCategoriesRequest, O: ReadTicketCategoriesResponse }
]);
