// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies,ts_nocheck,optimize_code_size
// @generated from protobuf file "owner_type.proto" (package "da.proto", syntax proto3)
// tslint:disable
// @ts-nocheck
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message da.proto.Status
 */
export interface Status {
    /**
     * @generated from protobuf field: int32 code = 1
     */
    code: number;
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string;
}
/**
 * @generated from protobuf message da.proto.Scope
 */
export interface Scope {
    /**
     * @generated from protobuf field: da.proto.OwnerType ownerType = 1
     */
    ownerType: OwnerType;
    /**
     * @generated from protobuf field: string ownerId = 2
     */
    ownerId: string;
}
/**
 * @generated from protobuf message da.proto.AuthScope
 */
export interface AuthScope {
    /**
     * @generated from protobuf field: string user_id = 1
     */
    userId: string;
    /**
     * @generated from protobuf field: repeated string teams = 2
     */
    teams: string[];
    /**
     * @generated from protobuf field: repeated string departments = 3
     */
    departments: string[];
    /**
     * @generated from protobuf field: repeated string branches = 4
     */
    branches: string[];
    /**
     * @generated from protobuf field: string current_branch = 5
     */
    currentBranch: string;
    /**
     * @generated from protobuf field: string organisation_id = 6
     */
    organisationId: string;
}
/**
 * @generated from protobuf enum da.proto.OwnerType
 */
export enum OwnerType {
    /**
     * @generated from protobuf enum value: USERS = 0;
     */
    USERS = 0,
    /**
     * @generated from protobuf enum value: TEAMS = 1;
     */
    TEAMS = 1,
    /**
     * @generated from protobuf enum value: DEPARTMENTS = 2;
     */
    DEPARTMENTS = 2,
    /**
     * @generated from protobuf enum value: BRANCHES = 3;
     */
    BRANCHES = 3,
    /**
     * @generated from protobuf enum value: ORGANISATIONS = 4;
     */
    ORGANISATIONS = 4
}
/**
 * @generated from protobuf enum da.proto.RequirementOwnerType
 */
export enum RequirementOwnerType {
    /**
     * @generated from protobuf enum value: STAGES = 0;
     */
    STAGES = 0,
    /**
     * @generated from protobuf enum value: AUTOMATIONS = 1;
     */
    AUTOMATIONS = 1
}
/**
 * @generated from protobuf enum da.proto.TimeUnits
 */
export enum TimeUnits {
    /**
     * @generated from protobuf enum value: UNKNOWN_OVERTIME_LIMIT_UNIT = 0;
     */
    UNKNOWN_OVERTIME_LIMIT_UNIT = 0,
    /**
     * @generated from protobuf enum value: MINUTES = 1;
     */
    MINUTES = 1,
    /**
     * @generated from protobuf enum value: HOURS = 2;
     */
    HOURS = 2,
    /**
     * @generated from protobuf enum value: DAYS = 3;
     */
    DAYS = 3,
    /**
     * @generated from protobuf enum value: WEEKS = 4;
     */
    WEEKS = 4,
    /**
     * @generated from protobuf enum value: MONTHS = 5;
     */
    MONTHS = 5,
    /**
     * @generated from protobuf enum value: YEARS = 6;
     */
    YEARS = 6
}
// @generated message type with reflection information, may provide speed optimized methods
class Status$Type extends MessageType<Status> {
    constructor() {
        super("da.proto.Status", [
            { no: 1, name: "code", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Status>): Status {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.code = 0;
        message.message = "";
        if (value !== undefined)
            reflectionMergePartial<Status>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Status): Status {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 code */ 1:
                    message.code = reader.int32();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Status, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 code = 1; */
        if (message.code !== 0)
            writer.tag(1, WireType.Varint).int32(message.code);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.Status
 */
export const Status = new Status$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Scope$Type extends MessageType<Scope> {
    constructor() {
        super("da.proto.Scope", [
            { no: 1, name: "ownerType", kind: "enum", T: () => ["da.proto.OwnerType", OwnerType] },
            { no: 2, name: "ownerId", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Scope>): Scope {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.ownerType = 0;
        message.ownerId = "";
        if (value !== undefined)
            reflectionMergePartial<Scope>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Scope): Scope {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* da.proto.OwnerType ownerType */ 1:
                    message.ownerType = reader.int32();
                    break;
                case /* string ownerId */ 2:
                    message.ownerId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Scope, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* da.proto.OwnerType ownerType = 1; */
        if (message.ownerType !== 0)
            writer.tag(1, WireType.Varint).int32(message.ownerType);
        /* string ownerId = 2; */
        if (message.ownerId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.ownerId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.Scope
 */
export const Scope = new Scope$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AuthScope$Type extends MessageType<AuthScope> {
    constructor() {
        super("da.proto.AuthScope", [
            { no: 1, name: "user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "teams", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "departments", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "branches", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "current_branch", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "organisation_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<AuthScope>): AuthScope {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.userId = "";
        message.teams = [];
        message.departments = [];
        message.branches = [];
        message.currentBranch = "";
        message.organisationId = "";
        if (value !== undefined)
            reflectionMergePartial<AuthScope>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AuthScope): AuthScope {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string user_id */ 1:
                    message.userId = reader.string();
                    break;
                case /* repeated string teams */ 2:
                    message.teams.push(reader.string());
                    break;
                case /* repeated string departments */ 3:
                    message.departments.push(reader.string());
                    break;
                case /* repeated string branches */ 4:
                    message.branches.push(reader.string());
                    break;
                case /* string current_branch */ 5:
                    message.currentBranch = reader.string();
                    break;
                case /* string organisation_id */ 6:
                    message.organisationId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AuthScope, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string user_id = 1; */
        if (message.userId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.userId);
        /* repeated string teams = 2; */
        for (let i = 0; i < message.teams.length; i++)
            writer.tag(2, WireType.LengthDelimited).string(message.teams[i]);
        /* repeated string departments = 3; */
        for (let i = 0; i < message.departments.length; i++)
            writer.tag(3, WireType.LengthDelimited).string(message.departments[i]);
        /* repeated string branches = 4; */
        for (let i = 0; i < message.branches.length; i++)
            writer.tag(4, WireType.LengthDelimited).string(message.branches[i]);
        /* string current_branch = 5; */
        if (message.currentBranch !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.currentBranch);
        /* string organisation_id = 6; */
        if (message.organisationId !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.organisationId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.AuthScope
 */
export const AuthScope = new AuthScope$Type();
