// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies,ts_nocheck,optimize_code_size
// @generated from protobuf file "ticket_dashboards.proto" (package "da.proto", syntax proto3)
// tslint:disable
// @ts-nocheck
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { OwnerType } from "./owner_type";
/**
 * Dashboard metric configuration with type safety
 *
 * @generated from protobuf message da.proto.DashboardMetricConfig
 */
export interface DashboardMetricConfig {
    /**
     * @generated from protobuf field: da.proto.MetricType metric_type = 1
     */
    metricType: MetricType; // Strongly typed metric type
}
/**
 * @generated from protobuf message da.proto.Dashboard
 */
export interface Dashboard {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string name = 2
     */
    name: string;
    /**
     * @generated from protobuf field: string description = 3
     */
    description: string;
    /**
     * @generated from protobuf field: string owner_id = 4
     */
    ownerId: string;
    /**
     * @generated from protobuf field: da.proto.OwnerType owner_type = 5
     */
    ownerType: OwnerType;
    /**
     * @generated from protobuf field: repeated da.proto.DashboardMetricConfig metrics = 6
     */
    metrics: DashboardMetricConfig[]; // Dynamic list of metrics
    /**
     * @generated from protobuf field: string created_at = 7
     */
    createdAt: string; // ISO 8601 timestamp
    /**
     * @generated from protobuf field: string updated_at = 8
     */
    updatedAt: string; // ISO 8601 timestamp
    /**
     * @generated from protobuf field: string created_by = 9
     */
    createdBy: string; // User ID who created
    /**
     * @generated from protobuf field: string last_modified_by = 10
     */
    lastModifiedBy: string; // User ID who last modified
}
/**
 * Dashboard requests
 *
 * @generated from protobuf message da.proto.CreateDashboardRequest
 */
export interface CreateDashboardRequest {
    /**
     * @generated from protobuf field: da.proto.Dashboard dashboard = 1
     */
    dashboard?: Dashboard;
}
/**
 * @generated from protobuf message da.proto.UpdateDashboardRequest
 */
export interface UpdateDashboardRequest {
    /**
     * @generated from protobuf field: da.proto.Dashboard dashboard = 1
     */
    dashboard?: Dashboard;
}
/**
 * @generated from protobuf message da.proto.GetDashboardRequest
 */
export interface GetDashboardRequest {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
}
/**
 * @generated from protobuf message da.proto.ListDashboardsRequest
 */
export interface ListDashboardsRequest {
    /**
     * @generated from protobuf field: int32 page = 1
     */
    page: number;
    /**
     * @generated from protobuf field: int32 per_page = 2
     */
    perPage: number;
    /**
     * @generated from protobuf field: string search = 3
     */
    search: string; // Search in name/description
}
/**
 * @generated from protobuf message da.proto.DeleteDashboardRequest
 */
export interface DeleteDashboardRequest {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
}
/**
 * @generated from protobuf message da.proto.DuplicateDashboardRequest
 */
export interface DuplicateDashboardRequest {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string new_name = 2
     */
    newName: string;
    /**
     * @generated from protobuf field: string new_description = 3
     */
    newDescription: string;
}
/**
 * Dashboard responses
 *
 * @generated from protobuf message da.proto.DashboardResponse
 */
export interface DashboardResponse {
    /**
     * @generated from protobuf field: da.proto.Dashboard dashboard = 1
     */
    dashboard?: Dashboard;
}
/**
 * @generated from protobuf message da.proto.ListDashboardsResponse
 */
export interface ListDashboardsResponse {
    /**
     * @generated from protobuf field: repeated da.proto.Dashboard dashboards = 1
     */
    dashboards: Dashboard[];
    /**
     * @generated from protobuf field: int32 total_count = 2
     */
    totalCount: number;
    /**
     * @generated from protobuf field: int32 page = 3
     */
    page: number;
    /**
     * @generated from protobuf field: int32 per_page = 4
     */
    perPage: number;
}
/**
 * @generated from protobuf message da.proto.DeleteDashboardResponse
 */
export interface DeleteDashboardResponse {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
}
/**
 * Configuration requirements for each metric type
 *
 * @generated from protobuf message da.proto.MetricConfigRequirements
 */
export interface MetricConfigRequirements {
    /**
     * @generated from protobuf field: bool requires_granularity = 1
     */
    requiresGranularity: boolean; // Whether this metric supports/requires granularity config
}
/**
 * Available metrics catalog with comprehensive type information
 *
 * @generated from protobuf message da.proto.AvailableMetric
 */
export interface AvailableMetric {
    /**
     * @generated from protobuf field: da.proto.MetricType metric_type = 1
     */
    metricType: MetricType; // Strongly typed metric type
    /**
     * @generated from protobuf field: string name = 2
     */
    name: string; // Display name
    /**
     * @generated from protobuf field: string description = 3
     */
    description: string; // Description for UI
    /**
     * @generated from protobuf field: da.proto.MetricConfigRequirements config_requirements = 4
     */
    configRequirements?: MetricConfigRequirements; // Configuration requirements
    /**
     * @generated from protobuf field: string category = 5
     */
    category: string; // Category for grouping (e.g., "Performance", "Distribution")
}
/**
 * @generated from protobuf message da.proto.GetAvailableMetricsRequest
 */
export interface GetAvailableMetricsRequest {
}
/**
 * @generated from protobuf message da.proto.GetAvailableMetricsResponse
 */
export interface GetAvailableMetricsResponse {
    /**
     * @generated from protobuf field: repeated da.proto.AvailableMetric metrics = 1
     */
    metrics: AvailableMetric[];
}
/**
 * Validation requests and responses
 *
 * @generated from protobuf message da.proto.ValidateDashboardRequest
 */
export interface ValidateDashboardRequest {
    /**
     * @generated from protobuf field: da.proto.Dashboard dashboard = 1
     */
    dashboard?: Dashboard;
}
/**
 * @generated from protobuf message da.proto.ValidateMetricConfigRequest
 */
export interface ValidateMetricConfigRequest {
    /**
     * @generated from protobuf field: da.proto.DashboardMetricConfig metric_config = 1
     */
    metricConfig?: DashboardMetricConfig;
}
/**
 * @generated from protobuf message da.proto.ValidationError
 */
export interface ValidationError {
    /**
     * @generated from protobuf field: string field = 1
     */
    field: string; // Field path (e.g., "metrics[0].size")
    /**
     * @generated from protobuf field: string message = 2
     */
    message: string; // Error message
    /**
     * @generated from protobuf field: string error_code = 3
     */
    errorCode: string; // Machine-readable error code
}
/**
 * @generated from protobuf message da.proto.ValidateDashboardResponse
 */
export interface ValidateDashboardResponse {
    /**
     * @generated from protobuf field: bool is_valid = 1
     */
    isValid: boolean;
    /**
     * @generated from protobuf field: repeated da.proto.ValidationError errors = 2
     */
    errors: ValidationError[];
}
/**
 * @generated from protobuf message da.proto.ValidateMetricConfigResponse
 */
export interface ValidateMetricConfigResponse {
    /**
     * @generated from protobuf field: bool is_valid = 1
     */
    isValid: boolean;
    /**
     * @generated from protobuf field: repeated da.proto.ValidationError errors = 2
     */
    errors: ValidationError[];
    /**
     * @generated from protobuf field: da.proto.AvailableMetric metric_info = 3
     */
    metricInfo?: AvailableMetric; // Information about the metric for reference
}
/**
 * Supported metric types based on actual analytics implementation
 *
 * @generated from protobuf enum da.proto.MetricType
 */
export enum MetricType {
    /**
     * @generated from protobuf enum value: METRIC_TYPE_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * KPI Dashboard
     *
     * @generated from protobuf enum value: METRIC_TYPE_KPI = 1;
     */
    KPI = 1,
    /**
     * Ticket Volume - config: granularity
     *
     * @generated from protobuf enum value: METRIC_TYPE_TICKET_VOLUME = 2;
     */
    TICKET_VOLUME = 2,
    /**
     * Channel Distribution
     *
     * @generated from protobuf enum value: METRIC_TYPE_CHANNEL_DISTRIBUTION = 3;
     */
    CHANNEL_DISTRIBUTION = 3,
    /**
     * Integration Distribution
     *
     * @generated from protobuf enum value: METRIC_TYPE_INTEGRATION_DISTRIBUTION = 4;
     */
    INTEGRATION_DISTRIBUTION = 4,
    /**
     * Agent Performance
     *
     * @generated from protobuf enum value: METRIC_TYPE_AGENT_PERFORMANCE = 5;
     */
    AGENT_PERFORMANCE = 5,
    /**
     * Status Distribution
     *
     * @generated from protobuf enum value: METRIC_TYPE_STATUS_DISTRIBUTION = 6;
     */
    STATUS_DISTRIBUTION = 6,
    /**
     * Priority Distribution
     *
     * @generated from protobuf enum value: METRIC_TYPE_PRIORITY_DISTRIBUTION = 7;
     */
    PRIORITY_DISTRIBUTION = 7,
    /**
     * SLA Compliance
     *
     * @generated from protobuf enum value: METRIC_TYPE_SLA_COMPLIANCE = 8;
     */
    SLA_COMPLIANCE = 8,
    /**
     * Activity Heatmap
     *
     * @generated from protobuf enum value: METRIC_TYPE_ACTIVITY_HEATMAP = 9;
     */
    ACTIVITY_HEATMAP = 9,
    /**
     * Resolution Time Analytics
     *
     * @generated from protobuf enum value: METRIC_TYPE_RESOLUTION_TIME_ANALYTICS = 10;
     */
    RESOLUTION_TIME_ANALYTICS = 10,
    /**
     * Escalation Metrics
     *
     * @generated from protobuf enum value: METRIC_TYPE_ESCALATION_METRICS = 11;
     */
    ESCALATION_METRICS = 11,
    /**
     * Live Ticket Tracking
     *
     * @generated from protobuf enum value: METRIC_TYPE_LIVE_TICKET_TRACKING = 12;
     */
    LIVE_TICKET_TRACKING = 12,
    /**
     * Trend Analysis - config: granularity
     *
     * @generated from protobuf enum value: METRIC_TYPE_TREND_ANALYSIS = 13;
     */
    TREND_ANALYSIS = 13,
    /**
     * Sentiment Analytics
     *
     * @generated from protobuf enum value: METRIC_TYPE_SENTIMENT_ANALYTICS = 14;
     */
    SENTIMENT_ANALYTICS = 14
}
/**
 * Valid granularity options for time-based metrics
 *
 * @generated from protobuf enum da.proto.Granularity
 */
export enum Granularity {
    /**
     * @generated from protobuf enum value: GRANULARITY_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: GRANULARITY_HOURLY = 1;
     */
    HOURLY = 1,
    /**
     * @generated from protobuf enum value: GRANULARITY_DAILY = 2;
     */
    DAILY = 2,
    /**
     * @generated from protobuf enum value: GRANULARITY_WEEKLY = 3;
     */
    WEEKLY = 3,
    /**
     * @generated from protobuf enum value: GRANULARITY_MONTHLY = 4;
     */
    MONTHLY = 4
}
// @generated message type with reflection information, may provide speed optimized methods
class DashboardMetricConfig$Type extends MessageType<DashboardMetricConfig> {
    constructor() {
        super("da.proto.DashboardMetricConfig", [
            { no: 1, name: "metric_type", kind: "enum", T: () => ["da.proto.MetricType", MetricType, "METRIC_TYPE_"] }
        ]);
    }
    create(value?: PartialMessage<DashboardMetricConfig>): DashboardMetricConfig {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.metricType = 0;
        if (value !== undefined)
            reflectionMergePartial<DashboardMetricConfig>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DashboardMetricConfig): DashboardMetricConfig {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* da.proto.MetricType metric_type */ 1:
                    message.metricType = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DashboardMetricConfig, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* da.proto.MetricType metric_type = 1; */
        if (message.metricType !== 0)
            writer.tag(1, WireType.Varint).int32(message.metricType);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.DashboardMetricConfig
 */
export const DashboardMetricConfig = new DashboardMetricConfig$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Dashboard$Type extends MessageType<Dashboard> {
    constructor() {
        super("da.proto.Dashboard", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "owner_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "owner_type", kind: "enum", T: () => ["da.proto.OwnerType", OwnerType] },
            { no: 6, name: "metrics", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => DashboardMetricConfig },
            { no: 7, name: "created_at", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "updated_at", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "created_by", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 10, name: "last_modified_by", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<Dashboard>): Dashboard {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.name = "";
        message.description = "";
        message.ownerId = "";
        message.ownerType = 0;
        message.metrics = [];
        message.createdAt = "";
        message.updatedAt = "";
        message.createdBy = "";
        message.lastModifiedBy = "";
        if (value !== undefined)
            reflectionMergePartial<Dashboard>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Dashboard): Dashboard {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* string description */ 3:
                    message.description = reader.string();
                    break;
                case /* string owner_id */ 4:
                    message.ownerId = reader.string();
                    break;
                case /* da.proto.OwnerType owner_type */ 5:
                    message.ownerType = reader.int32();
                    break;
                case /* repeated da.proto.DashboardMetricConfig metrics */ 6:
                    message.metrics.push(DashboardMetricConfig.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* string created_at */ 7:
                    message.createdAt = reader.string();
                    break;
                case /* string updated_at */ 8:
                    message.updatedAt = reader.string();
                    break;
                case /* string created_by */ 9:
                    message.createdBy = reader.string();
                    break;
                case /* string last_modified_by */ 10:
                    message.lastModifiedBy = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Dashboard, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* string description = 3; */
        if (message.description !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.description);
        /* string owner_id = 4; */
        if (message.ownerId !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.ownerId);
        /* da.proto.OwnerType owner_type = 5; */
        if (message.ownerType !== 0)
            writer.tag(5, WireType.Varint).int32(message.ownerType);
        /* repeated da.proto.DashboardMetricConfig metrics = 6; */
        for (let i = 0; i < message.metrics.length; i++)
            DashboardMetricConfig.internalBinaryWrite(message.metrics[i], writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* string created_at = 7; */
        if (message.createdAt !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.createdAt);
        /* string updated_at = 8; */
        if (message.updatedAt !== "")
            writer.tag(8, WireType.LengthDelimited).string(message.updatedAt);
        /* string created_by = 9; */
        if (message.createdBy !== "")
            writer.tag(9, WireType.LengthDelimited).string(message.createdBy);
        /* string last_modified_by = 10; */
        if (message.lastModifiedBy !== "")
            writer.tag(10, WireType.LengthDelimited).string(message.lastModifiedBy);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.Dashboard
 */
export const Dashboard = new Dashboard$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateDashboardRequest$Type extends MessageType<CreateDashboardRequest> {
    constructor() {
        super("da.proto.CreateDashboardRequest", [
            { no: 1, name: "dashboard", kind: "message", T: () => Dashboard }
        ]);
    }
    create(value?: PartialMessage<CreateDashboardRequest>): CreateDashboardRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<CreateDashboardRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateDashboardRequest): CreateDashboardRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* da.proto.Dashboard dashboard */ 1:
                    message.dashboard = Dashboard.internalBinaryRead(reader, reader.uint32(), options, message.dashboard);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateDashboardRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* da.proto.Dashboard dashboard = 1; */
        if (message.dashboard)
            Dashboard.internalBinaryWrite(message.dashboard, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.CreateDashboardRequest
 */
export const CreateDashboardRequest = new CreateDashboardRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateDashboardRequest$Type extends MessageType<UpdateDashboardRequest> {
    constructor() {
        super("da.proto.UpdateDashboardRequest", [
            { no: 1, name: "dashboard", kind: "message", T: () => Dashboard }
        ]);
    }
    create(value?: PartialMessage<UpdateDashboardRequest>): UpdateDashboardRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<UpdateDashboardRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateDashboardRequest): UpdateDashboardRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* da.proto.Dashboard dashboard */ 1:
                    message.dashboard = Dashboard.internalBinaryRead(reader, reader.uint32(), options, message.dashboard);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateDashboardRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* da.proto.Dashboard dashboard = 1; */
        if (message.dashboard)
            Dashboard.internalBinaryWrite(message.dashboard, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.UpdateDashboardRequest
 */
export const UpdateDashboardRequest = new UpdateDashboardRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetDashboardRequest$Type extends MessageType<GetDashboardRequest> {
    constructor() {
        super("da.proto.GetDashboardRequest", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetDashboardRequest>): GetDashboardRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        if (value !== undefined)
            reflectionMergePartial<GetDashboardRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetDashboardRequest): GetDashboardRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetDashboardRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.GetDashboardRequest
 */
export const GetDashboardRequest = new GetDashboardRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListDashboardsRequest$Type extends MessageType<ListDashboardsRequest> {
    constructor() {
        super("da.proto.ListDashboardsRequest", [
            { no: 1, name: "page", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "per_page", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "search", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ListDashboardsRequest>): ListDashboardsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.page = 0;
        message.perPage = 0;
        message.search = "";
        if (value !== undefined)
            reflectionMergePartial<ListDashboardsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListDashboardsRequest): ListDashboardsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 page */ 1:
                    message.page = reader.int32();
                    break;
                case /* int32 per_page */ 2:
                    message.perPage = reader.int32();
                    break;
                case /* string search */ 3:
                    message.search = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListDashboardsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 page = 1; */
        if (message.page !== 0)
            writer.tag(1, WireType.Varint).int32(message.page);
        /* int32 per_page = 2; */
        if (message.perPage !== 0)
            writer.tag(2, WireType.Varint).int32(message.perPage);
        /* string search = 3; */
        if (message.search !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.search);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.ListDashboardsRequest
 */
export const ListDashboardsRequest = new ListDashboardsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteDashboardRequest$Type extends MessageType<DeleteDashboardRequest> {
    constructor() {
        super("da.proto.DeleteDashboardRequest", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<DeleteDashboardRequest>): DeleteDashboardRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        if (value !== undefined)
            reflectionMergePartial<DeleteDashboardRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteDashboardRequest): DeleteDashboardRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeleteDashboardRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.DeleteDashboardRequest
 */
export const DeleteDashboardRequest = new DeleteDashboardRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DuplicateDashboardRequest$Type extends MessageType<DuplicateDashboardRequest> {
    constructor() {
        super("da.proto.DuplicateDashboardRequest", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "new_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "new_description", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<DuplicateDashboardRequest>): DuplicateDashboardRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.newName = "";
        message.newDescription = "";
        if (value !== undefined)
            reflectionMergePartial<DuplicateDashboardRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DuplicateDashboardRequest): DuplicateDashboardRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string new_name */ 2:
                    message.newName = reader.string();
                    break;
                case /* string new_description */ 3:
                    message.newDescription = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DuplicateDashboardRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string new_name = 2; */
        if (message.newName !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.newName);
        /* string new_description = 3; */
        if (message.newDescription !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.newDescription);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.DuplicateDashboardRequest
 */
export const DuplicateDashboardRequest = new DuplicateDashboardRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DashboardResponse$Type extends MessageType<DashboardResponse> {
    constructor() {
        super("da.proto.DashboardResponse", [
            { no: 1, name: "dashboard", kind: "message", T: () => Dashboard }
        ]);
    }
    create(value?: PartialMessage<DashboardResponse>): DashboardResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<DashboardResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DashboardResponse): DashboardResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* da.proto.Dashboard dashboard */ 1:
                    message.dashboard = Dashboard.internalBinaryRead(reader, reader.uint32(), options, message.dashboard);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DashboardResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* da.proto.Dashboard dashboard = 1; */
        if (message.dashboard)
            Dashboard.internalBinaryWrite(message.dashboard, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.DashboardResponse
 */
export const DashboardResponse = new DashboardResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListDashboardsResponse$Type extends MessageType<ListDashboardsResponse> {
    constructor() {
        super("da.proto.ListDashboardsResponse", [
            { no: 1, name: "dashboards", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => Dashboard },
            { no: 2, name: "total_count", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "page", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "per_page", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<ListDashboardsResponse>): ListDashboardsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.dashboards = [];
        message.totalCount = 0;
        message.page = 0;
        message.perPage = 0;
        if (value !== undefined)
            reflectionMergePartial<ListDashboardsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListDashboardsResponse): ListDashboardsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated da.proto.Dashboard dashboards */ 1:
                    message.dashboards.push(Dashboard.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* int32 total_count */ 2:
                    message.totalCount = reader.int32();
                    break;
                case /* int32 page */ 3:
                    message.page = reader.int32();
                    break;
                case /* int32 per_page */ 4:
                    message.perPage = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListDashboardsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated da.proto.Dashboard dashboards = 1; */
        for (let i = 0; i < message.dashboards.length; i++)
            Dashboard.internalBinaryWrite(message.dashboards[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* int32 total_count = 2; */
        if (message.totalCount !== 0)
            writer.tag(2, WireType.Varint).int32(message.totalCount);
        /* int32 page = 3; */
        if (message.page !== 0)
            writer.tag(3, WireType.Varint).int32(message.page);
        /* int32 per_page = 4; */
        if (message.perPage !== 0)
            writer.tag(4, WireType.Varint).int32(message.perPage);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.ListDashboardsResponse
 */
export const ListDashboardsResponse = new ListDashboardsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteDashboardResponse$Type extends MessageType<DeleteDashboardResponse> {
    constructor() {
        super("da.proto.DeleteDashboardResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<DeleteDashboardResponse>): DeleteDashboardResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        if (value !== undefined)
            reflectionMergePartial<DeleteDashboardResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteDashboardResponse): DeleteDashboardResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeleteDashboardResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.DeleteDashboardResponse
 */
export const DeleteDashboardResponse = new DeleteDashboardResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MetricConfigRequirements$Type extends MessageType<MetricConfigRequirements> {
    constructor() {
        super("da.proto.MetricConfigRequirements", [
            { no: 1, name: "requires_granularity", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<MetricConfigRequirements>): MetricConfigRequirements {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.requiresGranularity = false;
        if (value !== undefined)
            reflectionMergePartial<MetricConfigRequirements>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MetricConfigRequirements): MetricConfigRequirements {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool requires_granularity */ 1:
                    message.requiresGranularity = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MetricConfigRequirements, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool requires_granularity = 1; */
        if (message.requiresGranularity !== false)
            writer.tag(1, WireType.Varint).bool(message.requiresGranularity);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.MetricConfigRequirements
 */
export const MetricConfigRequirements = new MetricConfigRequirements$Type();
// @generated message type with reflection information, may provide speed optimized methods
class AvailableMetric$Type extends MessageType<AvailableMetric> {
    constructor() {
        super("da.proto.AvailableMetric", [
            { no: 1, name: "metric_type", kind: "enum", T: () => ["da.proto.MetricType", MetricType, "METRIC_TYPE_"] },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "config_requirements", kind: "message", T: () => MetricConfigRequirements },
            { no: 5, name: "category", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<AvailableMetric>): AvailableMetric {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.metricType = 0;
        message.name = "";
        message.description = "";
        message.category = "";
        if (value !== undefined)
            reflectionMergePartial<AvailableMetric>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: AvailableMetric): AvailableMetric {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* da.proto.MetricType metric_type */ 1:
                    message.metricType = reader.int32();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* string description */ 3:
                    message.description = reader.string();
                    break;
                case /* da.proto.MetricConfigRequirements config_requirements */ 4:
                    message.configRequirements = MetricConfigRequirements.internalBinaryRead(reader, reader.uint32(), options, message.configRequirements);
                    break;
                case /* string category */ 5:
                    message.category = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: AvailableMetric, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* da.proto.MetricType metric_type = 1; */
        if (message.metricType !== 0)
            writer.tag(1, WireType.Varint).int32(message.metricType);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* string description = 3; */
        if (message.description !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.description);
        /* da.proto.MetricConfigRequirements config_requirements = 4; */
        if (message.configRequirements)
            MetricConfigRequirements.internalBinaryWrite(message.configRequirements, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* string category = 5; */
        if (message.category !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.category);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.AvailableMetric
 */
export const AvailableMetric = new AvailableMetric$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetAvailableMetricsRequest$Type extends MessageType<GetAvailableMetricsRequest> {
    constructor() {
        super("da.proto.GetAvailableMetricsRequest", []);
    }
    create(value?: PartialMessage<GetAvailableMetricsRequest>): GetAvailableMetricsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetAvailableMetricsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetAvailableMetricsRequest): GetAvailableMetricsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetAvailableMetricsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.GetAvailableMetricsRequest
 */
export const GetAvailableMetricsRequest = new GetAvailableMetricsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetAvailableMetricsResponse$Type extends MessageType<GetAvailableMetricsResponse> {
    constructor() {
        super("da.proto.GetAvailableMetricsResponse", [
            { no: 1, name: "metrics", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => AvailableMetric }
        ]);
    }
    create(value?: PartialMessage<GetAvailableMetricsResponse>): GetAvailableMetricsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.metrics = [];
        if (value !== undefined)
            reflectionMergePartial<GetAvailableMetricsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetAvailableMetricsResponse): GetAvailableMetricsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated da.proto.AvailableMetric metrics */ 1:
                    message.metrics.push(AvailableMetric.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetAvailableMetricsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated da.proto.AvailableMetric metrics = 1; */
        for (let i = 0; i < message.metrics.length; i++)
            AvailableMetric.internalBinaryWrite(message.metrics[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.GetAvailableMetricsResponse
 */
export const GetAvailableMetricsResponse = new GetAvailableMetricsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ValidateDashboardRequest$Type extends MessageType<ValidateDashboardRequest> {
    constructor() {
        super("da.proto.ValidateDashboardRequest", [
            { no: 1, name: "dashboard", kind: "message", T: () => Dashboard }
        ]);
    }
    create(value?: PartialMessage<ValidateDashboardRequest>): ValidateDashboardRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<ValidateDashboardRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ValidateDashboardRequest): ValidateDashboardRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* da.proto.Dashboard dashboard */ 1:
                    message.dashboard = Dashboard.internalBinaryRead(reader, reader.uint32(), options, message.dashboard);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ValidateDashboardRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* da.proto.Dashboard dashboard = 1; */
        if (message.dashboard)
            Dashboard.internalBinaryWrite(message.dashboard, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.ValidateDashboardRequest
 */
export const ValidateDashboardRequest = new ValidateDashboardRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ValidateMetricConfigRequest$Type extends MessageType<ValidateMetricConfigRequest> {
    constructor() {
        super("da.proto.ValidateMetricConfigRequest", [
            { no: 1, name: "metric_config", kind: "message", T: () => DashboardMetricConfig }
        ]);
    }
    create(value?: PartialMessage<ValidateMetricConfigRequest>): ValidateMetricConfigRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<ValidateMetricConfigRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ValidateMetricConfigRequest): ValidateMetricConfigRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* da.proto.DashboardMetricConfig metric_config */ 1:
                    message.metricConfig = DashboardMetricConfig.internalBinaryRead(reader, reader.uint32(), options, message.metricConfig);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ValidateMetricConfigRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* da.proto.DashboardMetricConfig metric_config = 1; */
        if (message.metricConfig)
            DashboardMetricConfig.internalBinaryWrite(message.metricConfig, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.ValidateMetricConfigRequest
 */
export const ValidateMetricConfigRequest = new ValidateMetricConfigRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ValidationError$Type extends MessageType<ValidationError> {
    constructor() {
        super("da.proto.ValidationError", [
            { no: 1, name: "field", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "error_code", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ValidationError>): ValidationError {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.field = "";
        message.message = "";
        message.errorCode = "";
        if (value !== undefined)
            reflectionMergePartial<ValidationError>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ValidationError): ValidationError {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string field */ 1:
                    message.field = reader.string();
                    break;
                case /* string message */ 2:
                    message.message = reader.string();
                    break;
                case /* string error_code */ 3:
                    message.errorCode = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ValidationError, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string field = 1; */
        if (message.field !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.field);
        /* string message = 2; */
        if (message.message !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.message);
        /* string error_code = 3; */
        if (message.errorCode !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.errorCode);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.ValidationError
 */
export const ValidationError = new ValidationError$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ValidateDashboardResponse$Type extends MessageType<ValidateDashboardResponse> {
    constructor() {
        super("da.proto.ValidateDashboardResponse", [
            { no: 1, name: "is_valid", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "errors", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => ValidationError }
        ]);
    }
    create(value?: PartialMessage<ValidateDashboardResponse>): ValidateDashboardResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.isValid = false;
        message.errors = [];
        if (value !== undefined)
            reflectionMergePartial<ValidateDashboardResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ValidateDashboardResponse): ValidateDashboardResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool is_valid */ 1:
                    message.isValid = reader.bool();
                    break;
                case /* repeated da.proto.ValidationError errors */ 2:
                    message.errors.push(ValidationError.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ValidateDashboardResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool is_valid = 1; */
        if (message.isValid !== false)
            writer.tag(1, WireType.Varint).bool(message.isValid);
        /* repeated da.proto.ValidationError errors = 2; */
        for (let i = 0; i < message.errors.length; i++)
            ValidationError.internalBinaryWrite(message.errors[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.ValidateDashboardResponse
 */
export const ValidateDashboardResponse = new ValidateDashboardResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ValidateMetricConfigResponse$Type extends MessageType<ValidateMetricConfigResponse> {
    constructor() {
        super("da.proto.ValidateMetricConfigResponse", [
            { no: 1, name: "is_valid", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "errors", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => ValidationError },
            { no: 3, name: "metric_info", kind: "message", T: () => AvailableMetric }
        ]);
    }
    create(value?: PartialMessage<ValidateMetricConfigResponse>): ValidateMetricConfigResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.isValid = false;
        message.errors = [];
        if (value !== undefined)
            reflectionMergePartial<ValidateMetricConfigResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ValidateMetricConfigResponse): ValidateMetricConfigResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool is_valid */ 1:
                    message.isValid = reader.bool();
                    break;
                case /* repeated da.proto.ValidationError errors */ 2:
                    message.errors.push(ValidationError.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* da.proto.AvailableMetric metric_info */ 3:
                    message.metricInfo = AvailableMetric.internalBinaryRead(reader, reader.uint32(), options, message.metricInfo);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ValidateMetricConfigResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool is_valid = 1; */
        if (message.isValid !== false)
            writer.tag(1, WireType.Varint).bool(message.isValid);
        /* repeated da.proto.ValidationError errors = 2; */
        for (let i = 0; i < message.errors.length; i++)
            ValidationError.internalBinaryWrite(message.errors[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* da.proto.AvailableMetric metric_info = 3; */
        if (message.metricInfo)
            AvailableMetric.internalBinaryWrite(message.metricInfo, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.ValidateMetricConfigResponse
 */
export const ValidateMetricConfigResponse = new ValidateMetricConfigResponse$Type();
/**
 * @generated ServiceType for protobuf service da.proto.TicketDashboardService
 */
export const TicketDashboardService = new ServiceType("da.proto.TicketDashboardService", [
    { name: "CreateDashboard", options: {}, I: CreateDashboardRequest, O: DashboardResponse },
    { name: "GetDashboard", options: {}, I: GetDashboardRequest, O: DashboardResponse },
    { name: "UpdateDashboard", options: {}, I: UpdateDashboardRequest, O: DashboardResponse },
    { name: "DeleteDashboard", options: {}, I: DeleteDashboardRequest, O: DeleteDashboardResponse },
    { name: "ListDashboards", options: {}, I: ListDashboardsRequest, O: ListDashboardsResponse },
    { name: "DuplicateDashboard", options: {}, I: DuplicateDashboardRequest, O: DashboardResponse },
    { name: "GetAvailableMetrics", options: {}, I: GetAvailableMetricsRequest, O: GetAvailableMetricsResponse },
    { name: "ValidateDashboard", options: {}, I: ValidateDashboardRequest, O: ValidateDashboardResponse },
    { name: "ValidateMetricConfig", options: {}, I: ValidateMetricConfigRequest, O: ValidateMetricConfigResponse }
]);
