// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies,ts_nocheck,optimize_code_size
// @generated from protobuf file "ticket_note.proto" (package "da.proto", syntax proto3)
// tslint:disable
// @ts-nocheck
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message da.proto.TicketNote
 */
export interface TicketNote {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string description = 2
     */
    description: string;
    /**
     * @generated from protobuf field: string ticket_id = 3
     */
    ticketId: string;
    /**
     * @generated from protobuf field: string created_by = 4
     */
    createdBy: string;
    /**
     * @generated from protobuf field: string created_at = 5
     */
    createdAt: string;
    /**
     * @generated from protobuf field: string updated_at = 6
     */
    updatedAt: string;
}
/**
 * @generated from protobuf message da.proto.CreateTicketNoteRequest
 */
export interface CreateTicketNoteRequest {
    /**
     * @generated from protobuf field: da.proto.TicketNote data = 1
     */
    data?: TicketNote;
}
/**
 * @generated from protobuf message da.proto.CreateTicketNoteResponse
 */
export interface CreateTicketNoteResponse {
    /**
     * @generated from protobuf field: da.proto.TicketNote data = 1
     */
    data?: TicketNote;
}
/**
 * @generated from protobuf message da.proto.ReadTicketNoteRequest
 */
export interface ReadTicketNoteRequest {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
}
/**
 * @generated from protobuf message da.proto.ReadTicketNoteResponse
 */
export interface ReadTicketNoteResponse {
    /**
     * @generated from protobuf field: da.proto.TicketNote data = 1
     */
    data?: TicketNote;
}
/**
 * @generated from protobuf message da.proto.UpdateTicketNoteRequest
 */
export interface UpdateTicketNoteRequest {
    /**
     * @generated from protobuf field: da.proto.TicketNote data = 1
     */
    data?: TicketNote;
}
/**
 * @generated from protobuf message da.proto.UpdateTicketNoteResponse
 */
export interface UpdateTicketNoteResponse {
    /**
     * @generated from protobuf field: da.proto.TicketNote data = 1
     */
    data?: TicketNote;
}
/**
 * @generated from protobuf message da.proto.DeleteTicketNoteRequest
 */
export interface DeleteTicketNoteRequest {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
}
/**
 * @generated from protobuf message da.proto.DeleteTicketNoteResponse
 */
export interface DeleteTicketNoteResponse {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
}
/**
 * @generated from protobuf message da.proto.ReadTicketNotesRequest
 */
export interface ReadTicketNotesRequest {
    /**
     * @generated from protobuf field: string ticket_id = 1
     */
    ticketId: string;
}
/**
 * @generated from protobuf message da.proto.ReadTicketNotesResponse
 */
export interface ReadTicketNotesResponse {
    /**
     * @generated from protobuf field: repeated da.proto.TicketNote data = 2
     */
    data: TicketNote[];
}
// @generated message type with reflection information, may provide speed optimized methods
class TicketNote$Type extends MessageType<TicketNote> {
    constructor() {
        super("da.proto.TicketNote", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "ticket_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "created_by", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "created_at", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "updated_at", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<TicketNote>): TicketNote {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.description = "";
        message.ticketId = "";
        message.createdBy = "";
        message.createdAt = "";
        message.updatedAt = "";
        if (value !== undefined)
            reflectionMergePartial<TicketNote>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TicketNote): TicketNote {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string description */ 2:
                    message.description = reader.string();
                    break;
                case /* string ticket_id */ 3:
                    message.ticketId = reader.string();
                    break;
                case /* string created_by */ 4:
                    message.createdBy = reader.string();
                    break;
                case /* string created_at */ 5:
                    message.createdAt = reader.string();
                    break;
                case /* string updated_at */ 6:
                    message.updatedAt = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TicketNote, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string description = 2; */
        if (message.description !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.description);
        /* string ticket_id = 3; */
        if (message.ticketId !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.ticketId);
        /* string created_by = 4; */
        if (message.createdBy !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.createdBy);
        /* string created_at = 5; */
        if (message.createdAt !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.createdAt);
        /* string updated_at = 6; */
        if (message.updatedAt !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.updatedAt);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.TicketNote
 */
export const TicketNote = new TicketNote$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateTicketNoteRequest$Type extends MessageType<CreateTicketNoteRequest> {
    constructor() {
        super("da.proto.CreateTicketNoteRequest", [
            { no: 1, name: "data", kind: "message", T: () => TicketNote }
        ]);
    }
    create(value?: PartialMessage<CreateTicketNoteRequest>): CreateTicketNoteRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<CreateTicketNoteRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateTicketNoteRequest): CreateTicketNoteRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* da.proto.TicketNote data */ 1:
                    message.data = TicketNote.internalBinaryRead(reader, reader.uint32(), options, message.data);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateTicketNoteRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* da.proto.TicketNote data = 1; */
        if (message.data)
            TicketNote.internalBinaryWrite(message.data, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.CreateTicketNoteRequest
 */
export const CreateTicketNoteRequest = new CreateTicketNoteRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateTicketNoteResponse$Type extends MessageType<CreateTicketNoteResponse> {
    constructor() {
        super("da.proto.CreateTicketNoteResponse", [
            { no: 1, name: "data", kind: "message", T: () => TicketNote }
        ]);
    }
    create(value?: PartialMessage<CreateTicketNoteResponse>): CreateTicketNoteResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<CreateTicketNoteResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateTicketNoteResponse): CreateTicketNoteResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* da.proto.TicketNote data */ 1:
                    message.data = TicketNote.internalBinaryRead(reader, reader.uint32(), options, message.data);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateTicketNoteResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* da.proto.TicketNote data = 1; */
        if (message.data)
            TicketNote.internalBinaryWrite(message.data, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.CreateTicketNoteResponse
 */
export const CreateTicketNoteResponse = new CreateTicketNoteResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ReadTicketNoteRequest$Type extends MessageType<ReadTicketNoteRequest> {
    constructor() {
        super("da.proto.ReadTicketNoteRequest", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ReadTicketNoteRequest>): ReadTicketNoteRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        if (value !== undefined)
            reflectionMergePartial<ReadTicketNoteRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ReadTicketNoteRequest): ReadTicketNoteRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ReadTicketNoteRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.ReadTicketNoteRequest
 */
export const ReadTicketNoteRequest = new ReadTicketNoteRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ReadTicketNoteResponse$Type extends MessageType<ReadTicketNoteResponse> {
    constructor() {
        super("da.proto.ReadTicketNoteResponse", [
            { no: 1, name: "data", kind: "message", T: () => TicketNote }
        ]);
    }
    create(value?: PartialMessage<ReadTicketNoteResponse>): ReadTicketNoteResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<ReadTicketNoteResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ReadTicketNoteResponse): ReadTicketNoteResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* da.proto.TicketNote data */ 1:
                    message.data = TicketNote.internalBinaryRead(reader, reader.uint32(), options, message.data);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ReadTicketNoteResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* da.proto.TicketNote data = 1; */
        if (message.data)
            TicketNote.internalBinaryWrite(message.data, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.ReadTicketNoteResponse
 */
export const ReadTicketNoteResponse = new ReadTicketNoteResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateTicketNoteRequest$Type extends MessageType<UpdateTicketNoteRequest> {
    constructor() {
        super("da.proto.UpdateTicketNoteRequest", [
            { no: 1, name: "data", kind: "message", T: () => TicketNote }
        ]);
    }
    create(value?: PartialMessage<UpdateTicketNoteRequest>): UpdateTicketNoteRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<UpdateTicketNoteRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateTicketNoteRequest): UpdateTicketNoteRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* da.proto.TicketNote data */ 1:
                    message.data = TicketNote.internalBinaryRead(reader, reader.uint32(), options, message.data);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateTicketNoteRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* da.proto.TicketNote data = 1; */
        if (message.data)
            TicketNote.internalBinaryWrite(message.data, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.UpdateTicketNoteRequest
 */
export const UpdateTicketNoteRequest = new UpdateTicketNoteRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateTicketNoteResponse$Type extends MessageType<UpdateTicketNoteResponse> {
    constructor() {
        super("da.proto.UpdateTicketNoteResponse", [
            { no: 1, name: "data", kind: "message", T: () => TicketNote }
        ]);
    }
    create(value?: PartialMessage<UpdateTicketNoteResponse>): UpdateTicketNoteResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<UpdateTicketNoteResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateTicketNoteResponse): UpdateTicketNoteResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* da.proto.TicketNote data */ 1:
                    message.data = TicketNote.internalBinaryRead(reader, reader.uint32(), options, message.data);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateTicketNoteResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* da.proto.TicketNote data = 1; */
        if (message.data)
            TicketNote.internalBinaryWrite(message.data, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.UpdateTicketNoteResponse
 */
export const UpdateTicketNoteResponse = new UpdateTicketNoteResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteTicketNoteRequest$Type extends MessageType<DeleteTicketNoteRequest> {
    constructor() {
        super("da.proto.DeleteTicketNoteRequest", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<DeleteTicketNoteRequest>): DeleteTicketNoteRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        if (value !== undefined)
            reflectionMergePartial<DeleteTicketNoteRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteTicketNoteRequest): DeleteTicketNoteRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeleteTicketNoteRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.DeleteTicketNoteRequest
 */
export const DeleteTicketNoteRequest = new DeleteTicketNoteRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteTicketNoteResponse$Type extends MessageType<DeleteTicketNoteResponse> {
    constructor() {
        super("da.proto.DeleteTicketNoteResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<DeleteTicketNoteResponse>): DeleteTicketNoteResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        if (value !== undefined)
            reflectionMergePartial<DeleteTicketNoteResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteTicketNoteResponse): DeleteTicketNoteResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeleteTicketNoteResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.DeleteTicketNoteResponse
 */
export const DeleteTicketNoteResponse = new DeleteTicketNoteResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ReadTicketNotesRequest$Type extends MessageType<ReadTicketNotesRequest> {
    constructor() {
        super("da.proto.ReadTicketNotesRequest", [
            { no: 1, name: "ticket_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ReadTicketNotesRequest>): ReadTicketNotesRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.ticketId = "";
        if (value !== undefined)
            reflectionMergePartial<ReadTicketNotesRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ReadTicketNotesRequest): ReadTicketNotesRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string ticket_id */ 1:
                    message.ticketId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ReadTicketNotesRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string ticket_id = 1; */
        if (message.ticketId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.ticketId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.ReadTicketNotesRequest
 */
export const ReadTicketNotesRequest = new ReadTicketNotesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ReadTicketNotesResponse$Type extends MessageType<ReadTicketNotesResponse> {
    constructor() {
        super("da.proto.ReadTicketNotesResponse", [
            { no: 2, name: "data", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => TicketNote }
        ]);
    }
    create(value?: PartialMessage<ReadTicketNotesResponse>): ReadTicketNotesResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.data = [];
        if (value !== undefined)
            reflectionMergePartial<ReadTicketNotesResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ReadTicketNotesResponse): ReadTicketNotesResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated da.proto.TicketNote data */ 2:
                    message.data.push(TicketNote.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ReadTicketNotesResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated da.proto.TicketNote data = 2; */
        for (let i = 0; i < message.data.length; i++)
            TicketNote.internalBinaryWrite(message.data[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.ReadTicketNotesResponse
 */
export const ReadTicketNotesResponse = new ReadTicketNotesResponse$Type();
/**
 * @generated ServiceType for protobuf service da.proto.TicketNoteService
 */
export const TicketNoteService = new ServiceType("da.proto.TicketNoteService", [
    { name: "CreateTicketNote", options: {}, I: CreateTicketNoteRequest, O: CreateTicketNoteResponse },
    { name: "ReadTicketNote", options: {}, I: ReadTicketNoteRequest, O: ReadTicketNoteResponse },
    { name: "UpdateTicketNote", options: {}, I: UpdateTicketNoteRequest, O: UpdateTicketNoteResponse },
    { name: "DeleteTicketNote", options: {}, I: DeleteTicketNoteRequest, O: DeleteTicketNoteResponse },
    { name: "ReadTicketNotes", options: {}, I: ReadTicketNotesRequest, O: ReadTicketNotesResponse }
]);
