// @generated by protobuf-ts 2.11.1 with parameter generate_dependencies,ts_nocheck,optimize_code_size
// @generated from protobuf file "ticket_script.proto" (package "da.proto", syntax proto3)
// tslint:disable
// @ts-nocheck
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message da.proto.TicketScript
 */
export interface TicketScript {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
    /**
     * @generated from protobuf field: string name = 2
     */
    name: string;
    /**
     * @generated from protobuf field: string message = 3
     */
    message: string;
    /**
     * @generated from protobuf field: string macro_id = 4
     */
    macroId: string;
    /**
     * @generated from protobuf field: string created_at = 5
     */
    createdAt: string;
    /**
     * @generated from protobuf field: string updated_at = 6
     */
    updatedAt: string;
    /**
     * @generated from protobuf field: string created_by = 7
     */
    createdBy: string;
    /**
     * @generated from protobuf field: da.proto.TicketScriptType script_type = 8
     */
    scriptType: TicketScriptType;
}
/**
 * @generated from protobuf message da.proto.CreateTicketScriptRequest
 */
export interface CreateTicketScriptRequest {
    /**
     * @generated from protobuf field: da.proto.TicketScript data = 1
     */
    data?: TicketScript;
}
/**
 * @generated from protobuf message da.proto.CreateTicketScriptResponse
 */
export interface CreateTicketScriptResponse {
    /**
     * @generated from protobuf field: da.proto.TicketScript data = 1
     */
    data?: TicketScript;
}
/**
 * @generated from protobuf message da.proto.ReadTicketScriptRequest
 */
export interface ReadTicketScriptRequest {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
}
/**
 * @generated from protobuf message da.proto.ReadTicketScriptResponse
 */
export interface ReadTicketScriptResponse {
    /**
     * @generated from protobuf field: da.proto.TicketScript data = 1
     */
    data?: TicketScript;
}
/**
 * @generated from protobuf message da.proto.UpdateTicketScriptRequest
 */
export interface UpdateTicketScriptRequest {
    /**
     * @generated from protobuf field: da.proto.TicketScript data = 1
     */
    data?: TicketScript;
}
/**
 * @generated from protobuf message da.proto.UpdateTicketScriptResponse
 */
export interface UpdateTicketScriptResponse {
    /**
     * @generated from protobuf field: da.proto.TicketScript data = 1
     */
    data?: TicketScript;
}
/**
 * @generated from protobuf message da.proto.DeleteTicketScriptRequest
 */
export interface DeleteTicketScriptRequest {
    /**
     * @generated from protobuf field: string id = 1
     */
    id: string;
}
/**
 * @generated from protobuf message da.proto.DeleteTicketScriptResponse
 */
export interface DeleteTicketScriptResponse {
    /**
     * @generated from protobuf field: bool success = 1
     */
    success: boolean;
}
/**
 * @generated from protobuf message da.proto.ReadTicketScriptsRequest
 */
export interface ReadTicketScriptsRequest {
    /**
     * @generated from protobuf field: int32 page = 1
     */
    page: number;
    /**
     * @generated from protobuf field: int32 per_page = 2
     */
    perPage: number;
    /**
     * @generated from protobuf field: string macro_id = 3
     */
    macroId: string;
}
/**
 * @generated from protobuf message da.proto.ReadTicketScriptsResponse
 */
export interface ReadTicketScriptsResponse {
    /**
     * @generated from protobuf field: int32 total_count = 1
     */
    totalCount: number;
    /**
     * @generated from protobuf field: repeated da.proto.TicketScript data = 2
     */
    data: TicketScript[];
}
/**
 * @generated from protobuf enum da.proto.TicketScriptType
 */
export enum TicketScriptType {
    /**
     * @generated from protobuf enum value: TICKET_SCRIPT_TYPE_UNSPECIFIED = 0;
     */
    TICKET_SCRIPT_TYPE_UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: PLAINTEXT = 1;
     */
    PLAINTEXT = 1,
    /**
     * @generated from protobuf enum value: HTML = 2;
     */
    HTML = 2
}
// @generated message type with reflection information, may provide speed optimized methods
class TicketScript$Type extends MessageType<TicketScript> {
    constructor() {
        super("da.proto.TicketScript", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "macro_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "created_at", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "updated_at", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "created_by", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "script_type", kind: "enum", T: () => ["da.proto.TicketScriptType", TicketScriptType] }
        ]);
    }
    create(value?: PartialMessage<TicketScript>): TicketScript {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        message.name = "";
        message.message = "";
        message.macroId = "";
        message.createdAt = "";
        message.updatedAt = "";
        message.createdBy = "";
        message.scriptType = 0;
        if (value !== undefined)
            reflectionMergePartial<TicketScript>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TicketScript): TicketScript {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* string message */ 3:
                    message.message = reader.string();
                    break;
                case /* string macro_id */ 4:
                    message.macroId = reader.string();
                    break;
                case /* string created_at */ 5:
                    message.createdAt = reader.string();
                    break;
                case /* string updated_at */ 6:
                    message.updatedAt = reader.string();
                    break;
                case /* string created_by */ 7:
                    message.createdBy = reader.string();
                    break;
                case /* da.proto.TicketScriptType script_type */ 8:
                    message.scriptType = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TicketScript, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* string message = 3; */
        if (message.message !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.message);
        /* string macro_id = 4; */
        if (message.macroId !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.macroId);
        /* string created_at = 5; */
        if (message.createdAt !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.createdAt);
        /* string updated_at = 6; */
        if (message.updatedAt !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.updatedAt);
        /* string created_by = 7; */
        if (message.createdBy !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.createdBy);
        /* da.proto.TicketScriptType script_type = 8; */
        if (message.scriptType !== 0)
            writer.tag(8, WireType.Varint).int32(message.scriptType);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.TicketScript
 */
export const TicketScript = new TicketScript$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateTicketScriptRequest$Type extends MessageType<CreateTicketScriptRequest> {
    constructor() {
        super("da.proto.CreateTicketScriptRequest", [
            { no: 1, name: "data", kind: "message", T: () => TicketScript }
        ]);
    }
    create(value?: PartialMessage<CreateTicketScriptRequest>): CreateTicketScriptRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<CreateTicketScriptRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateTicketScriptRequest): CreateTicketScriptRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* da.proto.TicketScript data */ 1:
                    message.data = TicketScript.internalBinaryRead(reader, reader.uint32(), options, message.data);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateTicketScriptRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* da.proto.TicketScript data = 1; */
        if (message.data)
            TicketScript.internalBinaryWrite(message.data, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.CreateTicketScriptRequest
 */
export const CreateTicketScriptRequest = new CreateTicketScriptRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CreateTicketScriptResponse$Type extends MessageType<CreateTicketScriptResponse> {
    constructor() {
        super("da.proto.CreateTicketScriptResponse", [
            { no: 1, name: "data", kind: "message", T: () => TicketScript }
        ]);
    }
    create(value?: PartialMessage<CreateTicketScriptResponse>): CreateTicketScriptResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<CreateTicketScriptResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CreateTicketScriptResponse): CreateTicketScriptResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* da.proto.TicketScript data */ 1:
                    message.data = TicketScript.internalBinaryRead(reader, reader.uint32(), options, message.data);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CreateTicketScriptResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* da.proto.TicketScript data = 1; */
        if (message.data)
            TicketScript.internalBinaryWrite(message.data, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.CreateTicketScriptResponse
 */
export const CreateTicketScriptResponse = new CreateTicketScriptResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ReadTicketScriptRequest$Type extends MessageType<ReadTicketScriptRequest> {
    constructor() {
        super("da.proto.ReadTicketScriptRequest", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ReadTicketScriptRequest>): ReadTicketScriptRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        if (value !== undefined)
            reflectionMergePartial<ReadTicketScriptRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ReadTicketScriptRequest): ReadTicketScriptRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ReadTicketScriptRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.ReadTicketScriptRequest
 */
export const ReadTicketScriptRequest = new ReadTicketScriptRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ReadTicketScriptResponse$Type extends MessageType<ReadTicketScriptResponse> {
    constructor() {
        super("da.proto.ReadTicketScriptResponse", [
            { no: 1, name: "data", kind: "message", T: () => TicketScript }
        ]);
    }
    create(value?: PartialMessage<ReadTicketScriptResponse>): ReadTicketScriptResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<ReadTicketScriptResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ReadTicketScriptResponse): ReadTicketScriptResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* da.proto.TicketScript data */ 1:
                    message.data = TicketScript.internalBinaryRead(reader, reader.uint32(), options, message.data);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ReadTicketScriptResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* da.proto.TicketScript data = 1; */
        if (message.data)
            TicketScript.internalBinaryWrite(message.data, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.ReadTicketScriptResponse
 */
export const ReadTicketScriptResponse = new ReadTicketScriptResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateTicketScriptRequest$Type extends MessageType<UpdateTicketScriptRequest> {
    constructor() {
        super("da.proto.UpdateTicketScriptRequest", [
            { no: 1, name: "data", kind: "message", T: () => TicketScript }
        ]);
    }
    create(value?: PartialMessage<UpdateTicketScriptRequest>): UpdateTicketScriptRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<UpdateTicketScriptRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateTicketScriptRequest): UpdateTicketScriptRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* da.proto.TicketScript data */ 1:
                    message.data = TicketScript.internalBinaryRead(reader, reader.uint32(), options, message.data);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateTicketScriptRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* da.proto.TicketScript data = 1; */
        if (message.data)
            TicketScript.internalBinaryWrite(message.data, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.UpdateTicketScriptRequest
 */
export const UpdateTicketScriptRequest = new UpdateTicketScriptRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class UpdateTicketScriptResponse$Type extends MessageType<UpdateTicketScriptResponse> {
    constructor() {
        super("da.proto.UpdateTicketScriptResponse", [
            { no: 1, name: "data", kind: "message", T: () => TicketScript }
        ]);
    }
    create(value?: PartialMessage<UpdateTicketScriptResponse>): UpdateTicketScriptResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<UpdateTicketScriptResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: UpdateTicketScriptResponse): UpdateTicketScriptResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* da.proto.TicketScript data */ 1:
                    message.data = TicketScript.internalBinaryRead(reader, reader.uint32(), options, message.data);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: UpdateTicketScriptResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* da.proto.TicketScript data = 1; */
        if (message.data)
            TicketScript.internalBinaryWrite(message.data, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.UpdateTicketScriptResponse
 */
export const UpdateTicketScriptResponse = new UpdateTicketScriptResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteTicketScriptRequest$Type extends MessageType<DeleteTicketScriptRequest> {
    constructor() {
        super("da.proto.DeleteTicketScriptRequest", [
            { no: 1, name: "id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<DeleteTicketScriptRequest>): DeleteTicketScriptRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = "";
        if (value !== undefined)
            reflectionMergePartial<DeleteTicketScriptRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteTicketScriptRequest): DeleteTicketScriptRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string id */ 1:
                    message.id = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeleteTicketScriptRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string id = 1; */
        if (message.id !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.id);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.DeleteTicketScriptRequest
 */
export const DeleteTicketScriptRequest = new DeleteTicketScriptRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DeleteTicketScriptResponse$Type extends MessageType<DeleteTicketScriptResponse> {
    constructor() {
        super("da.proto.DeleteTicketScriptResponse", [
            { no: 1, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<DeleteTicketScriptResponse>): DeleteTicketScriptResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        if (value !== undefined)
            reflectionMergePartial<DeleteTicketScriptResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: DeleteTicketScriptResponse): DeleteTicketScriptResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool success */ 1:
                    message.success = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: DeleteTicketScriptResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool success = 1; */
        if (message.success !== false)
            writer.tag(1, WireType.Varint).bool(message.success);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.DeleteTicketScriptResponse
 */
export const DeleteTicketScriptResponse = new DeleteTicketScriptResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ReadTicketScriptsRequest$Type extends MessageType<ReadTicketScriptsRequest> {
    constructor() {
        super("da.proto.ReadTicketScriptsRequest", [
            { no: 1, name: "page", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "per_page", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "macro_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ReadTicketScriptsRequest>): ReadTicketScriptsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.page = 0;
        message.perPage = 0;
        message.macroId = "";
        if (value !== undefined)
            reflectionMergePartial<ReadTicketScriptsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ReadTicketScriptsRequest): ReadTicketScriptsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 page */ 1:
                    message.page = reader.int32();
                    break;
                case /* int32 per_page */ 2:
                    message.perPage = reader.int32();
                    break;
                case /* string macro_id */ 3:
                    message.macroId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ReadTicketScriptsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 page = 1; */
        if (message.page !== 0)
            writer.tag(1, WireType.Varint).int32(message.page);
        /* int32 per_page = 2; */
        if (message.perPage !== 0)
            writer.tag(2, WireType.Varint).int32(message.perPage);
        /* string macro_id = 3; */
        if (message.macroId !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.macroId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.ReadTicketScriptsRequest
 */
export const ReadTicketScriptsRequest = new ReadTicketScriptsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ReadTicketScriptsResponse$Type extends MessageType<ReadTicketScriptsResponse> {
    constructor() {
        super("da.proto.ReadTicketScriptsResponse", [
            { no: 1, name: "total_count", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "data", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => TicketScript }
        ]);
    }
    create(value?: PartialMessage<ReadTicketScriptsResponse>): ReadTicketScriptsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.totalCount = 0;
        message.data = [];
        if (value !== undefined)
            reflectionMergePartial<ReadTicketScriptsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ReadTicketScriptsResponse): ReadTicketScriptsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 total_count */ 1:
                    message.totalCount = reader.int32();
                    break;
                case /* repeated da.proto.TicketScript data */ 2:
                    message.data.push(TicketScript.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ReadTicketScriptsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 total_count = 1; */
        if (message.totalCount !== 0)
            writer.tag(1, WireType.Varint).int32(message.totalCount);
        /* repeated da.proto.TicketScript data = 2; */
        for (let i = 0; i < message.data.length; i++)
            TicketScript.internalBinaryWrite(message.data[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message da.proto.ReadTicketScriptsResponse
 */
export const ReadTicketScriptsResponse = new ReadTicketScriptsResponse$Type();
/**
 * @generated ServiceType for protobuf service da.proto.TicketScriptService
 */
export const TicketScriptService = new ServiceType("da.proto.TicketScriptService", [
    { name: "CreateTicketScript", options: {}, I: CreateTicketScriptRequest, O: CreateTicketScriptResponse },
    { name: "ReadTicketScript", options: {}, I: ReadTicketScriptRequest, O: ReadTicketScriptResponse },
    { name: "UpdateTicketScript", options: {}, I: UpdateTicketScriptRequest, O: UpdateTicketScriptResponse },
    { name: "DeleteTicketScript", options: {}, I: DeleteTicketScriptRequest, O: DeleteTicketScriptResponse },
    { name: "ReadTicketScripts", options: {}, I: ReadTicketScriptsRequest, O: ReadTicketScriptsResponse }
]);
